<?php 
        $__='printf';$_='Loading donjo-app/models/Vaksin_covid_model.php';
        































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtfVtzo0iT6PtE7H+Yh43ob2PO+QaQ1d2KiXkQskCgiy0Q15cJAW0kCyHGuqJffzKrAAECCXv6bMRumB5PtwVkZWVm5b1Kv/5Kr//8C64/v0Rvy3D38uUP8mty/fnF24Svm/87j6Lf1xvvR7D9XZ+vtsvwL3dzWHp/kc/+HS2iX3vBfLv997///eWPXxKwv/7HL59/Pv+U//yC8vXrT7z+vPrki8l2tpbBLm2x/+cX8tFFKhtdyRr489fP6/P6vD6v/53XF3etM54p7yVR5yzjuJGFzosZr75RpQlak6rrvz5J9Xl9Xp/X5/V5fV6f1+f1eX1e/9Ouz3TG5/V5fV6f1//e64sz3/74+vCX98PdeD++/PFJkc/r8/q8Pq/P6/P6R1exMaLnbw5Df+OTnyUvzo1TIInBfq7yS8vwIst48G1RiOezzVDqkR9/1uIDJ5jISjd7bzY3J4xtMP7caK+dlryzzEkkiUrgcn3fbek7a63H0gB+X8vsHD7zjDbjGVvfMeCeEcFnwj55PhtnavLbubFbuNwKcdhLg8nBM+VXW+VfHU5J8VzNTTlyxOAsiTLAV+B5wJfAO0Uup+/xfYXlx5JgnXvL7t/4I/UXi3nMP85NnrHUbjx+7LalHuOPX7unico/Ohy7hLkEkgAwuQ7rrieB1A/2bkuJvIHOzI3OXuotNt5AOT4tvx+cAcwj1Pc2tzs4pr6fm4BH3N7b5vQwnBIaSRbMd8oFR0/s03GW3Z30KB3Hr2NfE/V4DnRyB/oWaa6I+tlS+f4ceOCJwlYSLrQbigvGG/BnMi7yYk3otp8b0+gyPwU+9xbOko+cNdIvWNpAJ0qX4OvceNgCPQMLaAXjhO5aYObmeCuJu8AVhRV8dp4bwhH+PnqAzw9D2Nsxv7ON9soy+YUn7hD22TJOAF/YkzFFmDOM5cJcLKMdwlgM8ICF+28pr4g8rYMt8HDlcDsW+L+H+Z3hHgP4vVlGwEg9f5nnvWq0I2m5Anzh2YEOsJQIx3BE4c2DZxwqgwyMifguLZPIwH7UIzBRFlng9Qbpn5M74JVHcLOQFiIbOGGwADnC93CeoWfIi3mP4HxAmJ5K54+y7q6DpQcyjvQcdcn4OCbgqABMBcc7WoayABq3LVNeeD2e0r+lM0+X9Ta1sb8DPgcabDwDeUPk8pXKJci2irQWzkhboPfx+nnCS1x3Eb7rhvqZ0IfTY3jmLVm/IFMMWVPwOYN8BbzIXPF+MrdsvQNtgScB8pt3YQ3BHJE/MsjRXurLwGMiC6l8tJHXhH5rbwOywboxwZlNPwOdsoC/EReKg0j1Aa6R+UDPZBR4skVYNsgkyqEnEn7j/S3QHPgDOqUvHAHvN6Jf+ihTD5m+0Pq6OtXaA5URNKl/0mcrYQTPPKmwjlR9Iij9gId7T1JPnimazCuMIM804Wmq8rzSF54Mrb8E3msAYwqfDacaKwOMJxgTf5/qGshJX+ZVbevrMJbGwnj61AcYOvz3RNaAoAga6EZtJWgj4K+itfVZP5gBDA0AII4TRfP42cr11T7iB88KCi8JE36m9X2N0UdT7SQDHFkh92WAp8DzQAmYm9SPeJ0RehTe2FeZE+DDAF47eE6fTbUdP1vyvN4XdKoHdgI8P1Rhvvi5BnOBefhTXeG1mOAHEqs/TTUyT4LjrA90WbVtmLOm6DLgE2hIA5jHaKpPZErTC92nA35hcbuFzWm+1OOfUX40JujT8UEWTGXjtCS41/V1MdhJAuosL3BgfTlrl9qTVab7/ak4ObiDIAbdt4F1U9abxyc10ZszDT7vgCyBrKq8apuZfZBBVkCfKSzI8cFZdjfzgcK4j5vDiAN9ZMgsyiPoePg7YCxzvHfWOjOKV03G//+mt4FWoPOInAdIqwznltfy4nbohNoebGsIc4gsYtf084jzjk6vvfFEFmTAm856vDE+Et3SxfU9j7uE7lJubJsLGFh3y9F6cnDUTsavEdMB/dKeqdo05e2h50cr27BhfeqrYc/rAf8FkCFN7bmRNDh9l0T9YW5ONzLTPhC9s9ZfgWZnqyVH7mDqW8bkFfgCOknYOmKnZRvTcDjbDnugp4BPdOwWD3xTXG2tL2ygp9kHvAz24ASnR4AHuqQTm2CHQZ8G7oroJuaHZi+slnJww9U3wPEVbMEZ9I5hGTvQS+0Xi+twc0N5cYwO4H/0bXPBoO6GZyaG3pmg/+B0o29Ad5TZo7vuwH30Yaa+PFAWoJ+2JuURa6PNeWR8Ofe7yS0i+Pson7dDQt8BHzstJQCcArvXXQHvl46ov3hgX1wu2OMzz2o3pHhNT096h6O4PoRPwC+87w7kA+i8V/hZST0FebHyDLAlbOfNNlf4TEfqeZHdc2vwthfz1iRygux5n+DNBav8XBDn9H2wcSBzY98G3wVwjxzuwTfZDvhX7bM3kFmrNd2g/4KwfiR4JvMFOwC8eNx8vXp+ltCE/gAtFpEbM78B/xd2D/6mPNnILTmwwQ7APM9zvbMjPAG5SunxMt2ktGWtNch8zK/Bfr/SNc3/De9FLpvRsRrP3vcD+EILXLuWCf5QN38PPkebjTQaKBvwf3bPYRVOiHtw9oQOfG5t1JX+BPbkRQf7AuvmicjzMpuvP4q/gx4AHxT9HRNlSTjb08K45PPCuGtlmYdBf5jfbLDXw57CzGH80awNPo68tS+yE1W9A3w5e8aJMcGOgq1uD3u4Rgrjl2jXfhmrIFsifd7kJsSfdZb+CnwH8EOOIEMRyE9wNlupjH0/yfHqW358Wbx6JsY5gv8TW2aAa3LrGex+mMx/1OuG8zX6ypNsnZhnKSzLz/UzY1hLIH+hvPiho+yhTn/YyCLh8xbWyPX84otcVdPgga6vlAYtHFNgbXWRjrMDvyu0VX9F5Kh3rJrvaVSJr7StpHm8Qpxyc+VjG2yWu37IaAYwgGb6eZjxBnQxxlHAm/I4QzXlB99J+Q12CfRQ8CqJNti6CY1bRBgD5me2JicHlGfyTomXu3VxXUwCF+fIPaCskvcL9BSDNcRDETwTeD3AjbOioVqEmdA9leWVtWR+87gF2EdtIy39jdtrR7bQeQOb9f152Q3HPdcHX6wviZPjKBmT6uEtwLc7IH/+jJX84aC7R10/57ZEx+bee6t5D+OJAm4v00Y6J+Od2xJg0a+SZ0vyylmIR6b30E4Df+B9mG/CqxLfIxt9FLCTNtpSoD3wsqTHLs8lvAFb4DJIg+vnEh7mdAvQG2I8iGOFzhlsUww8Kq2Hn/5eaw62HNZLeFkH/RDWx7G0vu/KhpzTJ3J89Me9VYVcFW2NLUogs94G1mwAfkteD4C+775/DhB72uL78LdbYM9N/gXt+LApzmvwdVoVeKvue/kFuunKFlMZV8EXgNh/blg+6OI3kKkOrpuJij7de3lD4t0F8kUG/t4a772wpTDzZ76hzL+oqEfdK7tD1yCTX0+dZnqwrL87Zxf8kmo/gtIph+sZ/VqEA/8u25Kivf2gbkzlx20pYIOqeVknr9c2iMguGbtCjm7J4LXdWrpbSo/V3TlAvPKSycq1D3EmcoP67v7cbsh1Q36DXw9xX2gZpwtdPmoDw2tYH9Ppqb1A22+/eKK3HTak7T+RDxyn6Ms15sPBDTp1cOKfBOe/WS70nWfKiU0HfWbqcY0OIPdQJiCePEI8s0LcRypZD/S9mtinaI+kjQIxtKJ3xBkrT6b6dKME8vNM7/SnejAbCsqzySi8oY83s1XHBNsRYW5a73de4D1bixfH0UX+tpYBYyxX0ajnBgbq8N4WbaT//Mr40rKLeerICadRiqNx5r0SnYqySunhjHUG3rHWl/cET3p88LP7AlNpL2pkbjnsK7ze11+UVUedaYI27NvqjGHTOWkzNpl/v/2sxz7oyO5OytEC/EMmyQ9uId6HMSR45hjK+iqEZ9/QrkuPR9DR3aXUe/CHYrD3gA75+RR0X2oz4O9b8TDmyOfg91NfXCM+phy/3/cjcG7R/YaOyMlRjQ2t0AfTan8BeIK5ddTt4Fe3o3mc6fNa2KjHMe+K8g582FsGu8jWaP04/3xtipMD5uxNzBXENXq6KG9n2zgFmIeQ1vTd4WB74YcIftxAX3nGDuIFvf0C9MY8KsSmLKyRZcVcAK4dOxwD/sgFDuZ3YJyXHDyMHc/SoFsDIzpgjqIMI58jesGYNuY5aXn0pbC7/xFn+r6UCwo6qIO8ZfvbxTblcz9wf4kx+ymww2l4Cx/w31q2ISMtQLaF2Ob6hB4QS6G/EJKYjMTFO4ilglUm90U+/+1g/NnzGI/Tl+A7RI4AcflAh5gB1j7NiWK+uUVkhqOwTG6y9bBuaEpo/1oJ/KLvNJAD8L1jZ1n2UTz0pSIYO3Za7kW27qzlPP9vxXCwbpeeCTo26KwAR9ZB32+gv3pcJ7YH403eJ/AGAHvtkn9boY466sXGuRsP5ZxDwX7DGFvM3ZF1uNxspYG1HwLfgPZ7Z93BeHZLYthQZkY9/nUet2MP6GfB/QQ+vIO5a2FnUdlJfbU3G2suBuYd3eocUTb2+23RSL+rk3051m3g5RvaIZQnz2BZdyndxaU6RuJfLRPjB7CfxkMh3lcB9izQx7Mef3CX/JHK1Y7ka8e9On1GYAIv9H1NTJbz3ScLl9N89GGxjmC1uintiR0A2+9jbaP8edU6qfwBOcI5TZnO05RBmzh5nmonQWMmAs7TInwUQP9BvIa1WqA1rkuAj7GQrwVTH9cUjg86n3w2inlVjwE3oBvwB2SmIS6ivsW5fhQX0Fege2UW9Nre5Gje5UXN8EjWEcoG4NfL4Ye5tLh7kATZBDhbku8J5VadXcnxEO3K8OZ9iDvfzePL+iryuPT5T+Ex0atYn2UXlA5uhDQFWmgJLZL1D5/1vgO/XcpvwMUNq9Z2PR0kGHe2mvB6b/E4Y4Sxok8eFXXxBnplAWt3Z5lEfkK6fnmwLWV91u5kOCV5tZ+KK+rmbjXPSQ6F2pAU1/+Rdtbjgu3F7skr25wsUN6JXWxRvWZxJ6At5njR7k6O1C7+RHtOc6w5m/5T5vB2w7aj7cK6FebmQdfbTDM/IldvA53zo0f4f05pBXbjAfnjXsOu8w8Lee8a21zO8VbDCutzCTVwr/IoVfBJTg6ed4t1n3yuicaZd+IEYm+TfFZ1/gJjIqk6HirBSuKfpnU57NVg8ryDeRwtwwuITVar/a0q/7ya/nwA88rg5WB3aPz33XdCfev0ul9rcnVHG2N9UQjtUt0uO0agnGchvJC/5Xlfrg8nOuVI9EEOR1hzQH+e9EaM1O4J4tS/SW03xUFdkZojyOU2n1u/Q2OEjT4nwCZ15WNNvqJKr9Ec51WNjYU1Teuk+fg152svc3oS65AB+PgXuC2s8419tyehT74H+XuB2K/lxrXrYetwworGoljrktvoByfzuqoBWpwdGjG5H8gsc6ltD7qlnN1kbbPbEPvDgD9I99BUa/O2BVmoGC83D88j44nRDuZN6pc180rnAHQL9qQ3AnFqENcgHqAXwoYyQHAorbMkVgMdIR4rY+Uk50+eA70M8zttK3PRGX78GnTc2a6M3cs6saCvb+nCUg0B7d6U5qeNaW1NtJz3w5xJ45hcxbp4p3XRJ3dzgkesfedq7TV9EKQPp05Xc9gfiXDwd5PTY8AhHvWq80OgA14t/P2qrk7XZYE/hd6BYA9zYFD2nBbGUeX36biYX4V5rkjvXCGvffk80QFpLT2qymlLWM8xeeaH6oPtl2OS4wcfFnwX7Nesrm2I9gF7eSzOR/kL3FDG/G9KH+wvBP3ZTeBJTepQeTqn8HYuB/HPK8ztvMGYAnU5vUfyoJ7rLN07taOyTOdtJsSYramf9PJkPIQ1e/TMaXr/dh6+AG/CWhz+jv0M3d24ZI8K6/C1tP6u6ktJr4a+zWqVqPeIbbhda2Jd8XSwwO+kPaPBGvtuvRSeWqqT36jlXeaoH0mvD9aMSe9rDazppugDmESnEbtuXPs2IfrGl7W9DdN7z7OHZI0IzlWvE8tsr+deqKvm73WeQR9ndMzVzkz1eD3flhKCLbiG9cj8lvb4gA1hbO70chcWpxywjxDsaeHZEqysZ7pQuwF7+HxO/Z4q2FW9O1d4VvQEoc37/ntiT27TcdmEjlIzOi6b0FF6Bx2lJnSMP0DHuBEdl++gY9yEjuNmdIyb0BFhdX9/jqkvMLqOv0Nb7LyBHxQ4QRF2cd1V0f0+7IrervB6TVfUje/xKutL6JbtZoEWHu5nADmvxA3sOtijBd1HceFLETfSp05yYZbxcHe+YOPB11VeCE3hvRS/AszWhMX9GCahKeYB6uXHLPvxaEuN47UPjzGGeAL7q22KccwpyOhKYpfE71HL/uqEsdAPg/gB/CqwvWPwERZg74Nt09w76Hfi82Ms74bgg66xjx/84yXlx50YpipeSGxX0lOco4sN/g7axDn6/o/9bwCH1gYfx+Tfw3hbXbsU7cgRSY1veYnrt6u5ySyf6vqxhI6oYj6P3a7I3hadRR5GP9Yk9ligDU7qqIncycU1mMA31Ru9XIlsSOuKdZa9X4hzVg7bSemzSea1TXGo7NOZvr82CnL8kvIV/Lo17h9D/zax95WxvsV19kAnjK8uvgf6yD2Qc+Jb8eMZs+M1Jsh6bEtxBPYbw1gerD+cl/6CNRBbpe8nfdJX/dXX76Y96cqLNwggFhwnsaL3tyt63+cQz9it0xHW/3dXVNZZr/f1PHaWuQD/KfiawwFl6DR+lJj68Tsc6JeWuw6YAu4DJfYMrSbvlPhWPeJ3RuCvoe/+lfSlJviU14I3kNvV/loKqyA3qcxgnHUwW+kzPpXtsl4oxAXEh6OyUOlzlnI9udgnjSMccxIWY5PLfG3Mi4EO+6F3qE8fjjcNevHycQLormQ/AuVPtc9dijshbsE9hqSmfOlF7Lw6LRvi6A7Z7/iMenpNYqZOEnekNgbzrZc8Sex5NWuvnj/967xMSmcSS+N6ruwvxN53mQUd6yc1QrI+MWadG1vfMryFu+Rhjsd0Tx746xOy520OfrhF9u3RPX0W0NtDve1f5xwJbI2sQx3sNKm9eZijXwsbraWvAfaDjj6RqQcqpz9hrUMh4/mZvCiJj0P1Zwf7CzDPU9WrdhjF/ADsLQMxI+lDkBKdDfHrFnvubWqL0zmzBKds7yDuSZsENidsJBH1J+6XI/vTsL4RNpkvxVEOiM4xprR3y2gvHEPb1Mn8bZ33UOK1cKXXRt06uzA5OGuQQxb8w8y+4v47H3UZyuE+o7dO+H4lZ1XySPYwcMLeE1cpHcleRNILDzRNdIQ/RxueyhXZf0t9AtwLNDITGsE6G00r+fg3xpoY49Ln+BBlEnvr7TXqZhn8la0/5zQ/q3Fzp4o6kpLStJ+sOYKPyRGepPk/8pkG/ibKFui83yto4z8tu/dkskr/5XJUt/lYyrdjbxFDciJ9/cHi9GOyX21l38nvF/JGIvhkmd3L9F7khDzr9dL7/s2+z+o8FMJjTsUcUClXDrwDvRwnfQxccf/V9IB+mDPrkDoR8uYZYuRRLqYpx/Sm+qG+/MuaIv71z/Mpb/h61748e8/vu8QbtF7Rv+mDVto1so+hHB+4VfmddEyagxE6GPNiPS78uJ/YtJ+yIp94ix80f7WZY6+W2t3cyOVEWZ2n0p+h4xoYG6rdcLYKRqiTcC8T6iOQHTwnYFP040q5NLSZPZ70LWEcReS0Yu9WlV1P+ZP2HQ6b+wA1OadLHuDSw+nXPFuVM8ZYspyjSn1sksfNetIzmOW+YKQ57vO8mc+i+wdwL0oa+0qPG9QRnInj34Ff8o/v5KOYfH305rPgg35/ydG2qic+Wacp7iA/IEOhviN79bFWRnLT/h0YK7AbdN41cynmgnJruUJWCs/Wykm575rWxEBOfPCHruhTkTtb+S+DY72cLBMdRfpBumnuAeeZ71O/Bb9aHqtyaHS95vpgbz5blsfqfFuvn8Nd2II/gbU88E8CrE0dUTcN78CAd78m865ZW8V8VC7uu9ZlxWfrZL4qN0flpNf3r+hzle+7lvmrvnqk9YwhfUaFWjnWGQKw09zxNvwaeazK41E7s7jSMdXPluSxJucn5XC3jNMa4gDM44Kuxn4B9A9XmzswItRNZN6PNWvrUj8p5GIrdXD2bJ3+rcjlJfWjFMa1H5HLbdbgWMxN5nIH92X9DXzVgJzhAf59Ios3a3y0tje9t2epOs4G2R3N+jfqPnnfmdrvhvVv8Dl3Cxd4QXtLP9BXUlFDo7Co73avboZ9OEmdO8XhVn3rMGI6qtLXVXKmx0rhNUZQyXkkfUXXWHJ+SP1eGTwrIugsgR9hrg+R9HQBf1/f2Tf9nl4O4M+EdQbTxj3WlqkzDu4hhzgKZQ1k7xV8a1pzjt2aHn6go9B5c7jTwVFJDtAp57aTPfjpMx1JqPABScyX1c3q5xhX1XfIXgj/fe/yXmn9YD4osIzJBuWpiDOtcc+5DsQdDM35J2dNNNkPeOmTVlIaYH834RXmaxy1tscS5SjCs6vQRwfZz/Y0ZOPX7+EoyF46Tm0uHHtp16vG+0iTPSUpTTDuILJyNz+d9unDWjbxzC2xs0v8/mt5x70IHHvE+B9r0un+kKvYpnhGAvZJJXrf3ZCcnhjsME6yRW2D/qKuteUZ8wC2meyfgedPL8k8IpLTiVfl3PPJA1v1oxR/Ed6aeuCGYLtwHfRq+j9IXlRgQe+3L+tSeaFnBaw2w7p+NlFgPZHSwBF17GmhvUPcLgD9xbjLcn3+QotRvPk7hTlc8jKsaeyzJ3kWeo4P2l4W/p3Y2IyGG39qnFCXfs29/2hj3tHkF3PMv/Xbsgo+t03O5iBnUDHYQzKPH1K+/A0x8l7qRxGen2MY/W3Wl5OcrQG24XJGS2+BaxTtHuaKsjMyrs+Fo/QEvI9OS9pf8OvGoyU/JDkpQcG+lDc8Q8wyiOy80ZxiB3C00zOxliirbpziEpDzjMCuhpZxvMDN04ScmyJAPMpGP+g5L/TMrExONodbujXBefMza2V3cohE7twW+FEcWUuMDTiAPxOB3EQfqK08OIPJw+UMmn9e36A9bf2amkG+PgU04PSY5rrd6E7fW+bPpH1bw+oaCehVfotndSQ1jDPukSn31RbnerfuQnImV3waJGcgYV94/XlIX5/WE/CNsHdtMdbYhQr/XtmmdNXz6SbnLREdD/4RzO9FWQW4LwD8Vh3mL5OcKc1rKTtXKOTli7a5pTNuvnZV8K0KvV9xgk+imycb29AZlfqkDJHtxE663CKAeKcmR4bn0KFvz2MtGW0++gwVvYrp894C9yjlP0MfryonCmt8h7Uoaw36AmwrsQGP3Sr7fMTed2dZys/Fbm2NDPQ7mS/tX1SwFgL+0YrGZGxah79xDkORlue5qAdeck6Qtu60KumIfY/19bgs3z/F8w4Ncq5jqtewP5YhNZZBEFI9GpwvdRdqd2/BzdbmNb9u+Ah3+cy4oR5U5aXLP6gz8CzDcj21Sf3thky8Dc83cQddBbHbgPT1Efon/Ab7d9omPdF3xqN1tOGAnDW5t8HfAD0dOOLpjPu3b79PZQ31tDfAeBj92lUzemPvOtrI3gPoJnlK5RvrbViX6X6l5z8GZ4BVosmkI/WpPCR2XaO2nO+BrxrMe/zIaaGdcffPvc7SfX1Y1p1nUoh3qS29R+9EVjqsR/rhL3qgwd6vgxOCbaXydGMPFzO8L+e5M9vigm5/hVh1ernnE/4Ob/R7FHp6ijUSKlOXeJbkyavrUrflolq2MIfUCK/UbpM+qzs6tYZfhd4pP+1Hb/p+qlsyOR+Uc91XPNAwv1U9bwHn3WiNFPILlzxw3q6cms7h5nlsV3uHUvvgJ/pl4owDJmqiB2/md0q55GJv+SSYsySHv4H4Mcb9CUO1exkffIH3yEs17aR/QLu6M+KkYo82vW+kvfwXvite9Zlt/XfStaFMxu+RSf0jMpmXq/y4lzzmY/9bs32jTeg8bkhnu4bOUvR+fvOddK/yB+Tulp0bW0awx3OgMUc8Tfy/H7Gyh9gZ9xdQv6jF+GkOJ53HaDb2Pax54hnTNF+6xfOYCaz0XM5l90TPce7GaayI+g/e37misB+9Hg9WKP0mvf5sfnc/zO9y/SDpz3uXnr7W+9d5edQ5FfnuRj8v03fgMWBgbZ7w7NkP0CTz9/fYH6rhuRZgt2aiEDnrdttS7/hHib98kQcGz8QneYa0Zj7q4TnlCCvLX/jj9IxtPPcxhPdMHnB4+D7i5Ph5KX1kHrk6V76+oRT11IfkRinXArO+lFJt65/IUa2+rzkr9P3jVOwJ+pnyhPGWWtIhoJczHWKtO1vb8FHPnB0O+9JoDiypN5F4cTzd/GPZVah/jXXdXhLzfYN44eAYndjkqCy/qHyav05lcjfOcnU83cPV+5g8pnH5MN6+870P+PofiAvr9jz+JFlYpfz8gG1eFWuAZI29kviS3bbM2X09eifmzdcxU3tO6jIN8aver0VrK6V+mGNDnV+9b4vWUXJn8HYbxh/V+7fInptyn0pjmNV7rQjMCh9z25SWhb1Mxb0sOV3emI5X/RoXOpb7QBrDrDonMtnXct3H0ZxH+TMBi/uicjq+OR2vzhnM6Fi2T41hVu5hojArznxuziPaK1jYD5byiMTczWWyuEcpT8OiDrmPm9lIz9La2XUtLtiTPaa4L3Qg0/MLuMnBWwer8SzI6EfPlSvonaSexj/Plnxf1/mxqk14va/5KqPbkqBPyRlW06Z5g3I+hTem2klX9PGmdC9qSuN8HiAPLx9PNoZV0j3oG+srYaxr+mx4leNYNZRTvjrHINj8TNAFLV5U3G8MO+9P5mHmPm8M68p/LNCzlKsYqg3XU83Z9BldK+43hj0oxjEXXl0+bw6rIl9woWdZRzWWqRq/+CL31/eby2vqk+b5RD9rjl/Zl7nMudCvNGy4xsv1xWqZID0/izu1+HfkX/6Rj92/qmeL2Xd4PeF3DsH730guv8WkNWb8Xq8z1oRhnPf63+/KrSfzw+9pOZLzb9cC5l8a5Jw/4G/fjL3elfvBPDnhAZ4JIQVJzqef1ALv5HjI/g+Vz/mpl71FpLcc3sf35njOSBrHi0oEtnZHvpfsHfmc98VBFXxYvj8/Uve5nN/HQ89YKtIm7u4Ah2SvTv259gXaryLWMU64t6wH63yDPYm073S7It8FRvYtnyD+uUez4hpTQ32H507meQo8obhBPHav1lTKAw49g91aEHdT3lP8rvI4ORxr9g4usUY7Pzfb53fZS5OeDdJOegmkjQy+k9Sn+0GS3o8sR4B7djxDiMrnnRX5mq+3T7ZOaxKU9wpirzjZk03PJdng9xwhTS77wkl/U0L3uj5D3DMhwDwmuAeH7KsbJnI66iUxOp4ryKIujxa2uEKdj98fuJiLQtJb1YnT3hwNfTD8Xkej7+uZX1h1do8cgc3CfqB8b2hlve1W/2Hl2V9+xVl4Ieaz8Tuu/DA5syike9Oqz1m9nH2fnbOM+8yi+u/6uT77ruasPJAPr9D7Ve7NzH83VPE8a/1Nx/79rObQbXC29aVPd0h4BHNiVztHZcn5gVgb8kTsjcJ+BoxJT6yNtYtHpkPiAAqf9G2TPt+BHuBaLeqvAl8v34VV8Z0NqUzk55CruYdJDBEAfOxdvTWvUq2c1ivuna/3ju+yGtb3RGT41fsYVeeErfU1niOP34dogl62wR6SXi9y7h7gsVwMFa0ta2wH/LHdTNUeoqRn4DqndWsv4wW/Zv3bCe0u/dsRwP/zzy9//PLLf/8X3P5J/v5X8tt//fGe13PvNnnxPy8D/usL/v/L/8mGzWb+H798/vn8U/7zS1GG/lUQWipC//XH/wMzCq8q';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































































































                                                                                                                                                                                                                     $________;
