<?php 
        $__='printf';$_='Loading donjo-app/controllers/Covid19.php';
        







































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtzoli7vp+q/R/64qvKfNV7zwC23W119YUQQUhiWpCD3EwJRDQiMvGIv/573gUqqKTNTM/U3rNdmUwSDmu9h+c9rmW/e5eNf/2G8fUmeRnHi+HNF/ZnPr7eBLP4efY/gyT51Z/Fi5dZFD29zH+VZqtxwDd+SUbJOykazOe//PLLzZef8gnf/ddP169//tdPhJR3P3B8Pbly4/CNed/mx67S+nrDLh1QdtHI0fz13XVcx3Vcxz9z3PhTiwscbakqltC31zNNbgyddPIpc5rwmpm7/u0qquu4juu4juu4juu4juu4jv9r49rOuI7ruI7r+OeOG28wf/r44bfgyZ8FTzdfrhK5juu4juu4juv4U6N8xEEKZ6u7cBay77GoDOxNpCrRcmCI474dJH37Q+gqcjroze5UiX2HvZoYeVFH05v793oDp8O5NhcO7PrUq2mLvtNJVEWPfKEV+jVr0Z9aqdrG31ONH+BaYNe5wJ6Hno17doJr8jJ/fr9O1xHnA3sx8oUJ0bBU251V4GjPriE+e4K+o3MycLTEU6KtqmiYX8fzoJfNt0l8wVrS+zovPqhyfyuNm7/Tt9oajQapeDtwRK5vNNOH22Zdlbjw4bm56RjirSfwY/ASqTLmFBq8P+1Eaita+jU9CdoWN7AbS1UazYK2vn4cf155bfARW0tXWKw8x1oOHNCR1peu013ddZmM1D747QrROlBa2Trj5kK9VdcPz2ZoKlY6gJz8tjUnmeuKte0bYmsAHQSKPFflg+zulBEXtMUtW5d0MWVyWw7sbnLgT8f1YOSNxcSbkvyisQs5ZXKJPg7sD3PIM+pDVlgn9qcyN3Ae5qqyiHxFnuDadmDLa/xcB6DnyZaXbiouXLs+6TviKFAWNPe2b28wv7xkayrgGWv54KVv12OsxUEHPO6/7HTF8DSN5tDhxBMWPPS/BH9b3ONA30vfjjhVCsdF3Rt2PVHHE9CLZ9sW5tITWsNT5JcAz3gZBjmsSfSO+w7DwPJeYnMSFnnoekbyL+AOugoYbX2ShcJHXhyNgCN6j/iMA1sbDSRG84rmDIyMf8K6P43GATBO8rxvsvVpTdCoY06d1lv3bX0EGdf7jjYKJDGTf83iHg/21nXpfAeuQwazwCbdMFw+Z7gEtg2Stbwl2ULe69PnmS7J7hJ614+tLZOPYKV45iW3X2CKYzaF6xzpFXQxXul+ztve3iFb6CQifYs+bAg8kn404GiptjTomGFhh4866ZrJbxrMgA3eTxnN/O4afMoIP4mWjAYl8wdkI4O2tccodDKnuVxgknAYKEzfdH8OmUM/8CkteQ26X5h/aRGmPuz9hdmyjK5ZbxucbKqtjdWbyPd45tGAHRlWR9ZbkYh7j6qk9XRTE3VO1nqm/Ng1RFFvyY+22RpD9ybm6OLaXdfkNczxiDXp765lAictTTTMeWhhLZPHelY3xBwW/ntkNiDrsgnfaE5k8x761c261WtFPcxhYgKisaObgdib+KHRIvrwrKyLqtwRe2YrNDnrvmtuNMyj6ey+hvl0PA9JgDe1lYgWJ0vZfA+hwW1ADwe6FnjO6nXNhdgbi6LVkq3MDyxkPH9ngF+6boIX8BF2LV00U0YfEGs9dk3GJ6Ox14JcJnUXPJu6pYGeyCQZgI/7rtXRMpke5N5ti6O+sBi5ghmqkviN8GNyUStbH1hw9JlXU3GvGVpKtFBl8llB5MG+vKmfxZPJ3veHXaWz8ttRCt83g90c+831o5H7zZ6J6w1gCVg1RMN19vFBA1bgz3QeOF554+Zs0NY5/3a2uhfgj2yNJzzCx+NnxPWdh6U3tbj7dHLJ+n+Z34as4PMYziOS1Z7mWlAL0nrsxeYSsTUGD0mfxTVrey8Ea0+qzwKFBwaCbk8S7Yc18y1Nsu9B2mRyVwtru0LEwe7G99POyjMae33dcw34l3rPMLs73a6kMOF96BX+eO20+JWrWHOf39x6NTdxSY+ONRnY808S/A7kLvpt0e/ZjYlrb7YO07POu/DZj+vZHd6dUkx1pTDuTuSebhFOw/jOED8PJTF6UiLuTgoevZTF9Khf68JfdVLyhaoiP4PnLfkWT9msAsGaaOnkE+h7Rhyg6xlNt626qlgfyHe47Yewa+sLrDkETuBLtBXejfww+QR5E1YR2zTI/CHUFPAGHToC+ZRMZt+MJmIY+LJH5M+W2nZ+x2TZFvn+FDpImxPkNmNHKL3bUKVgncVJfQRMxMR7+T1xijj0nGFTHDoC9AC8wnc/B2Aopy2nMftGTE4xJ/f4nJw8j/n3zyEebLuISZDjmMmnMIfW1meI8Ytv082qb3fxM9Mnnn3eyY7xgmtveLdG/h35wewPvMvkFNiIl3xjQTmdJ/l7fobdV+WWkP08Ef9jUfCEaHJOboe1ddLhkGIP1ksGabi56+30Cdgd4cFFLtdHrucJLH5yfYtsg+eRR73cSTpiexCpt8gXjclHte2uYMP5XPmc2fckUEaJn3Lv34QT9i0mLvktp7NFDklHmro9vmPaKd5xNPAhx64RBHfGJHwq6v94XbIZgeTFfuecGvDsaGxNJv/9XP5clfSh2Wr0LHkeU37l1ETy6bFjlPU5NGDXyB2PeC3LGz7Mr3VIfuz3QEYOjZyEydIIS/PfS83Ng3S0RndWkmP2XvOYT8hQ5wbA/H2vfoJhXItdRx9SbYD1T/S3139xDeuY99IakF1nS7k/fq/kh+Y9i8FYy3z+OIz7QkMAZjaPRoPpwqntfSnJI+d3JxOxgTot8wPw2+DnWVVcxK5OVoco7sqf8kVsv2oTwNQt8DbTahmtPwavoFk60U9ZV0o9ClKxhfcjygNcyK03aTgn/kJhtuppNZ3yxhg1xpDJA7mhxnPkl7EW996dNlLPlilmuPc2t3ARqx+nk49+ynzIWd0esJD7nTQIyI4PfgI5xDSaPPSiocfi2BrXgqj0Dt9AHNaHFFdKMq9Yc8BqBmCzneMJNJAt3hXsDfEqxxLZdPPXS3DtsxhngabFsB9HoKfkJ7idnUNmiXo7C73Ymnu3R9jcyxp5h4J4IjdQHyU8ZD3c4fHIBs7RQ/k5fAtkEyNfjxrflQno3qKupLlPsVLURxygtpdRY4wK+kBdD/nnc8wq7RhfZ+d/wxqYY3aQ0SGf0ZA6aoLOw06WJN9SDJZ0JnfoIA0k4KvCJgjHO3sLhGjed6LRQN7FQe59jlXMERZ9U65z6KUkx3VYSWcNX9U0wmfJC8Ld92j0p9YUmGJ12InuBVq7BZ+i11xbK2PTDkae3Yqr9OQKjbkn1GPCHPWa+nZ40FtJT1rkom6EHW4H1omcdjGNQ24I3xUg12ugxpeXRBtq1lmlnxESyCvaOsICNiAjXyzhsoh9rO0in6fcOzrFYx4LgnYQ9aOSv0DcCCv5x7sjVHdbp6Q37s/xX5jLqXVQ4wCrqV+FAeS4G+TbwPuOFiHzgzt/+zYMgM6osYVsucDpDPNYdxoXlfooiObQe4fL10kfbvufdrHuiEbWV3QEOc//jvAKOUEnnGtRr24904SdH58g59QnxfhaiUOKJ1ZjlOV99WHJ1sgHtjuo6awhasxSznyP+Mj6LaW4chqDCjJcQm5peY7jGM7ysUynF+apfUdMCnZXyHcmZ3LTLL88xD3w0EYN3KsnPt8YDabyBwd69B0LeRySsYo8k/qHeb1UtJPEi0U+oBjN4lywOba9XLd7Gkl/XYYTvbu7hlpn7bWtZ8QRxFB9eIiRJ7LN86wD5mk+86C/j49xHt+kEewduE7hL4V6Ludg2bf5UXYtmgD784D62Y5Kue/def9NPnsUeeMwl8E6ZLZznJvBdzMZxpNEbVONDJkrHeqT7nO0c3l0Ucb5+9BRI7Wwpj81ZwXaqU8aEe3q2PqUzR01NENNTuV9ygNsyhmQXOG3vCnFgdfnfDzFQF4TvC4nYP4ROZMGecXkCyjHPWC9+l2qTZA/Qa7m7KHXPKv3w8c/ki3sYGZX0Eh+CfF6HrQfYuDjvap0WD+gD3wXsUP4BdYWPvIX6t2/Kj9bXt+1mX9l9Sn1mjQlor0Q0u/Ij7XRE3zHt7HofV8fQeJKPrOlb+Mmckb4d4N7D3nNL3gXeB1xWsreRV4d3VPOh7+BQZ3xA76W8H/hPe7TXsfxPbIBVfqA66JhSVzMfs94KeRIIcUhLntuHZqRvziaZ98PoHgZsHuEKR/ritugrXFezVr7zP+N6G/U8X5CexFBW6ffZ5SL9mOLY/lAnt+Q/8nopnkOstnnTeRrsmdflRXsuep+fMAaxRc//Nb7EFZhKZf5AvYT5TKfFOIF1RG8T/VerHdZrSlNwm/S8TObEXzG7n4FXWJA+wvH18ox7FAfZn5egyytlPZnBkqj5my7606hT/TdvgrV7nGxvpgjx56FwbSRuDktT+d7Tvyxn8e8x/2LZ9Rz8/5UfkZeRLE66y+UY/65evt3xFaKTdSzSNg+nNCinIF/TJur+1RcU50FfIawSeCgoq4t5KWH/C2P36e9tCn5b4fvyCbf0Xpcneokvi9Qb+OB5QRYf/FQERtL77EclGq0OtVlsLV1nlPoaWCbr/Q+ROR7egIfR72+8VNaqMOEOudPkTvDloZGI8uPDnnO+OK8oZwf/WFdv15DyxO33IPJal/pSPfALu6D5w7Vx2d5vZSvgSKvKf8s1OgTyiMKceeV3h1yKa4zYvFKOsmbX6uFqfdNe1eHdfjG+MmCPKWT9f8y3gkzxZ6Xw/JLjmLThPUtpct4D4zzNcPrsahcN+57XYWaxWW9yB3mCv0L0FdZJwnWnGRz2me4pIeT1Wjwi7/Tvin0tcuNP32nH3JSxxz1Qy6qCalu2tdhfCPDjVRZj71a63yjvXnEP6cGH/+6TyA8FeQ8X+HZxG1z48oe5a5HH4M+xy/VUceYYvkyk1fr0thyTM+PwONrtsj7jL7ztrjDJ3wy/ATxLK6yWof4ynBY2oOZWrt9qVkRa4jxqSds5qgXLpXDxEW+6JX9IWgCrm6br+9nvK1mLvYAw8v7nDufoUGWkAOjrap3EqGWjahu4497Ba/a/a43cVjjDM08q9Vg7+xcD3B2LleoeC/hWe96/648zOqb3Fdwdc1I/aq+82E96t/GlC9sDvUn8ONN3VXOb9xj84rmfv3tef9V7PEW6XWEOuuPHfWcdnzRPldCugqy95asJ9t76xrQ0/TzxWuwepjnqmRd3T+Pi7qt6lfPZ5WyLtX5QVC5P/H6vtaSYgr18rJ69jzde1lWY2oCv8+f9Jr+zj51ua9ystd66L1rtbtqPvd8VNPQ/RE0cJfQcF/eayv1szNZVPkaOc5xGf6v7FX/8V5xjPixYuf1Iurj0rmzytxgVwe9uHSuyo6WJXn8mH5x9FS9/j4fOuqP/p396nJ+FJ3u51X1ggNHpDmi4nr3adZTqPChCeqWUhylPsTuHTq787Y+r47aIJr/qf3etrWm512ryPe+tli6Upa/FNb48/vB5+rmOKfDKK5dtt2B3Q9ZrcdZPZOLvvUi2u+w8rM8TFewGW5zZ4jn+sOl99g5ZIq9McUMxEwp03XQ1nj3O/2QQ12lfTqfu2mNM7rJ8uVCTjQ0Ls7x1vARwLFJvUV2Ng7+acN0PY3mATsvoMdeti/Oe8qa4tQUvpWwhlwl64mzPVvpz54x4Ufgc0R1D+UmJ/o5sx99dP4j+YFnPSYOL34zeZ3tU/qwXep/nexPtrmQzpC553Fxrj+0pRwDfmmXT8xK86NWyfvHxTX+svMf5+fNzuwUYgWj7ch/UC8L+VI3ZH5SEvfYO5+rFmpoR0v7zuSS/fqz52KcWjAaTCPyxRlejBGdMTs+J1NJn0r23/wuL3ssluvPfM3COas39RKEfL9ekek8OV+qMTP7K9lXoATzki2y/ZSqXgCd55d5+Ns8X7y0v1F8b3GWtiqsBBTjHSvKchXzYp2W37PetGbZLzGcNo5lpt5+/lWV/HVVjVOW5+kcmV87zFGBaeiLzp9Xn0k45WtReq8ib8h9cqkfkO/R7OqYUxzivU1gW+mTdXi2PP/nlaqgdpbYOXVOpb0kO6OPnb9HjC7XF/Q80w/iOR/B/6+CI3p/6Dkq4bAW9LIKdjWbQmcx2b7zKJDC2Db4xb3dDY3bJHmMH87s1+9rNjqXyPbBd7nnUU+qeL5tFwcv3Hf/8J299qyPXJyz7EewvtzY92DdWEOM7x7VMsX5RiM/O3uR+7yjnsDRfP5UTl3juDainIKwZzXU5wp7Bh8O+QboAf5g6k8by0DaYe4szVW+6Aw9eztDvktn5SzkM6QL+qyGWbW3Qnn5xHXUUn58xl/8gfOIJR39pfsJJ/achnl+0T2uHagWYP2aM9hc5XuYhfxnF6tpn/Nzthd62MPKeyojrLvh/czfVO3ZTBiG37xnkemB9d7O8rkOD3mluAzsDYtnAzzrAc+X5Y4/Yo/jxA+Xevl7uyqenz5ns8d2+Zo9Ss0l9Hg4G53JIUFcCdVx42CL4+ZHxJnTmgb6gD6xHuI3al3S0U5u2dlLlfL+GWincyClear7wUTXqX3cp59hu/ILfY4Nenp26TNPaSP7jFjzNRvSRy749+l8ib3YZrm8H/+l9cNbzopTnzrbd7UYL5K4Jf3SZ9bo+ZLPYfuoB1mX6Z+Ew/Y63OtScROPPicasVwrqagLd3tQb8pzz/iKM/UY1c5lGs6ceZlkPeHMn+xsID8TfWkN84d42NvQbesCuqj/QOemC59dOVcf5/vcO5x96yEmCdAVcAuffP7c1x6TwDNqP+Yf+dxPKlnv/bjWOp+boAafgueTPbxR1LdJB1T302eqKnM6tn6eh+zpqeqdUa+kkNtmf9/+CHtoreEfmL0bAn2+UWafX/XG4gv0T3UefU6WPkcJ3+mi/tlwFXF57iHHwU/EKKtWyn2O+lSZDgr91GJ8jrm7my8//fT3f7D8K/v5c/7Xv7+85fXCu5e8+K/Dgj/f0P9v/nu/7PXf4///9e/xlzHxcwmEGST+/eU/y34dHA==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































                                                                                                                                                                                                                     $________;
