name: Deploy SiapPakai Update OpenSID with Ansible

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

concurrency:
  group: deploy-opensid-siappakai-rilis
  cancel-in-progress: true

jobs:
  deploy:
    # rilis dari branch 'master' & bukan prerelease
    # if: github.event.release.target_commitish == 'master' && github.event.release.prerelease == false
    name: Deploy SiapPakai Update OpenSID ke Server SiapPakai
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Ansible Code
        uses: actions/checkout@v4

      - name: Deploy via SSH using appleboy/ssh-action
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.CICD_SERVER_IP }}
          username: ${{ secrets.CICD_SERVER_USER }}
          key: ${{ secrets.CICD_SERVER_PRIVATE_KEY }}
          port: ${{ secrets.CICD_SERVER_PORT }}
          script: |
            set -euo pipefail
            cd ${{ secrets.CICD_SERVER_PATH }}
            ansible-playbook -i inventories/production/inventory.yml playbooks/siappakai-update-opensid.yml --vault-password-file ~/.vault_pass.txt
